import { displayEnvironment } from './displayEnvironment.js';
import { CmykStroke,fillCmyk,type InkPaint } from './cmykEditing.js';
import { compositeCmyk } from './cmyk.js';
import type { BrushPoint } from './pixelTools.js';
import type { EditorDisposable,EditorJsonValue } from '@haiyue/editor-plugin-sdk';
import type { ImageWorkspace } from './workspace.js';
import { allLayers,findLayer,layerLocked } from './document.js';
import { cmykBitmap,convertDocumentCmyk,convertDocumentRgb } from './cmyk.js';
import { embeddedProfile } from './colorManagement.js';
import { initializeIcc } from './iccEngine.js';
import { referenceJob } from './iccReference.js';
const str={type:'string',minLength:1,maxLength:160} as const;
type Params={readonly[key:string]:EditorJsonValue};
export function registerColorDomainOperations(w:ImageWorkspace):EditorDisposable {const p=w.platform,owned:EditorDisposable[]=[];
 for(const mode of ['mode','read','write','fill','stroke'] as const)owned.push(p.operations.register({ownerId:'image.operations',descriptor:{id:'image.cmyk.'+mode,title:'CMYK '+mode,version:1,target:'document',documentKinds:['haiyue.image'],access:mode==='read'?'read':'write',input:{type:'object',properties:{mode:{type:'string',enum:['rgb','cmyk']},profileId:str,layerId:str,resourceId:str,channels:{type:'array',items:{type:'integer',minimum:0,maximum:3},maxItems:4},opacity:{type:'number',minimum:0.001,maximum:1},preserveAlpha:{type:'boolean'},erase:{type:'boolean'},size:{type:'number',minimum:1,maximum:512},hardness:{type:'number',minimum:0,maximum:1},pressure:{type:'string',enum:['none','size','opacity','both']},points:{type:'array',maxItems:8192,items:{type:'object',properties:{x:{type:'number',minimum:-32768,maximum:32768},y:{type:'number',minimum:-32768,maximum:32768},pressure:{type:'number',minimum:0,maximum:1}},required:['x','y']}},ink:{type:'array',items:{type:'number',minimum:0,maximum:100},maxItems:4}},required:mode==='mode'?['mode']:mode==='write'?['layerId','resourceId']:mode==='stroke'?['layerId','ink','points','size']:mode==='fill'?['layerId','ink']:['layerId']},output:{type:'json'}},async prepare(a:Params,c){c.signal.throwIfAborted();const d=w.documents.find(d=>d.identity.id===c.document?.id);if(!d)throw Error('文档已关闭。');if(mode==='mode'||embeddedProfile(d.state))await initializeIcc();c.signal.throwIfAborted();if(mode==='mode'){if(allLayers(d.state.layers).some(l=>layerLocked(d.state.layers,l.id)))throw Error('请先解除图层锁定。');if(a.mode==='cmyk'&&!a.profileId)throw Error('转换 CMYK 需要目标 ICC。');return {d,state:a.mode==='rgb'?convertDocumentRgb(d.state):convertDocumentCmyk(d.state,p.resources.read(a.profileId as string)),created:[] as string[]};}
 if(mode==='fill'||mode==='stroke'){const settings={ink:a.ink as number[],...(a.channels?{channels:a.channels as number[]}:{}),opacity:(a.opacity??1) as number,preserveAlpha:(a.preserveAlpha??(mode==='fill')) as boolean,erase:a.erase===true};let layer;if(mode==='fill')layer=fillCmyk(d.state,a.layerId as string,settings);else{const points=a.points as unknown as BrushPoint[];if(!points.length)throw Error('笔画至少需要一个点。');const stroke=new CmykStroke(d.state,a.layerId as string,a.size as number,settings,{hardness:(a.hardness??1) as number,pressure:(a.pressure??'none') as 'none'});for(const point of points)stroke.point(point);layer=stroke.layer;}return {d,l:layer,bitmap:layer.bitmap!,created:[] as string[]};}
 const l=findLayer(d.state.layers,a.layerId as string),b=l?.bitmap;if(d.state.colorMode!=='cmyk'||!b?.cmyk)throw Error('需要 CMYK 像素层。');if(mode!=='read'&&layerLocked(d.state.layers,l!.id))throw Error('图层已锁定。');const n=b.width*b.height;
 if(mode==='read'){const bytes=new Uint8Array(n*20),v=new DataView(bytes.buffer);for(let i=0;i<n;i++){for(let k=0;k<4;k++)v.setFloat32((i*5+k)*4,b.cmyk[i*4+k]!,true);v.setFloat32((i*5+4)*4,b.data[i*4+3]!/255,true);}return {d,bytes,width:b.width,height:b.height,created:[] as string[]};}
 const ink=b.cmyk.slice(),alpha=Float32Array.from({length:n},(_,i)=>b.data[i*4+3]!);{const bytes=p.resources.read(a.resourceId as string);if(bytes.length!==n*20)throw Error('CMYKA32FLE 资源尺寸不符。');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);for(let i=0;i<n;i++){for(let k=0;k<4;k++)ink[i*4+k]=v.getFloat32((i*5+k)*4,true);const a=v.getFloat32((i*5+4)*4,true);if(!Number.isFinite(a)||a<0||a>1)throw Error('透明度必须是 0–1。');alpha[i]=a*255;}}
 return {d,l,bitmap:cmykBitmap(b.width,b.height,ink,alpha,(d.state.bitDepth??8) as 8|16,embeddedProfile(d.state)),created:[] as string[]};},commit(r){if(r.bytes){const resource=p.resources.put(r.bytes);r.created.push(resource.resourceId);return {...resource,width:r.width!,height:r.height!,format:'cmyka32fle',inkUnit:'percent',alphaUnit:'unit'};}r.d.runAtomic(()=>{if(r.state)r.d.commitMode(r.state);else r.d.replaceLayerPixels(r.l!.id,{...r.l!,bitmap:r.bitmap!},'编辑 CMYK 原生通道');});return {applied:true,colorMode:r.d.state.colorMode??'rgb'};},rollback(r){for(const id of r?.created??[])p.resources.release(id);}}));
 owned.push(p.operations.register({ownerId:'image.operations',descriptor:{id:'image.cmyk.sample',title:'CMYK 原生取色',version:1,target:'document',documentKinds:['haiyue.image'],access:'read',input:{type:'object',properties:{x:{type:'integer',minimum:0,maximum:8191},y:{type:'integer',minimum:0,maximum:8191}},required:['x','y']},output:{type:'json'}},prepare(a:Params,c){const d=w.documents.find(d=>d.identity.id===c.document?.id),x=a.x as number,y=a.y as number;if(!d||d.state.colorMode!=='cmyk'||x>=d.state.width||y>=d.state.height)throw Error('需要 CMYK 文档内的坐标。');const b=compositeCmyk(d.state,{x,y,width:1,height:1});return {ink:Array.from(b.cmyk!),alpha:b.data[3]!/255,inkUnit:'percent'};},commit:r=>r,rollback(){}}));
 owned.push(p.operations.register({ownerId:'image.operations',descriptor:{id:'image.icc.reference',title:'ICC v2/v4/iccMAX 参考引擎',version:1,target:'workspace',access:'write',input:{type:'object',properties:{mode:{type:'string',enum:['validate','transform']},resourceId:str,encoding:{type:'integer',minimum:0,maximum:6},interpolation:{type:'integer',minimum:0,maximum:1},profiles:{type:'array',maxItems:8,items:{type:'object',properties:{profileId:str,pccId:str,intent:{type:'integer',minimum:0,maximum:3101103},environment:{type:'array',maxItems:32,items:{type:'object',properties:{name:{type:'string',minLength:4,maxLength:4},value:{type:'number'}},required:['name','value']}}},required:['profileId','intent']}}},required:['mode','profiles']},output:{type:'json'}},async prepare(a:Params,c){const chain=a.profiles as {profileId:string;pccId?:string;intent:number;environment?:{name:string;value:number}[]}[];const result=await referenceJob({mode:a.mode as 'validate'|'transform',profiles:chain.map(e=>({bytes:p.resources.read(e.profileId),intent:e.intent,...(e.pccId?{pcc:p.resources.read(e.pccId)}:{}),...(e.environment?{environment:e.environment}:{})})),...(a.resourceId?{input:p.resources.read(a.resourceId as string)}:{}),encoding:(a.encoding??3) as number,interpolation:(a.interpolation??1) as 0|1},c.signal);return {result,created:[] as string[]};},commit(r){const {report,...info}=r.result,resource=p.resources.put(new TextEncoder().encode(report));r.created.push(resource.resourceId);return {...info,...resource,format:'icc-reference-text'};},rollback(r){for(const id of r?.created??[])p.resources.release(id);}}));
 owned.push(p.operations.register({ownerId:'image.operations',descriptor:{id:'image.display.query',title:'系统显示能力',version:1,target:'workspace',access:'read',input:{type:'object',properties:{}},output:{type:'json'}},prepare(){return displayEnvironment();},commit:r=>r,rollback(){}}));
 return {async dispose(){await Promise.all(owned.map(o=>o.dispose()));}};
}
