import type { ImageDocument, Bitmap } from './document.js';
import { layerLocked } from './document.js';
import type { InkPaint } from './cmykEditing.js';
export function nativeInkEnabled(){return (document.getElementById('native-ink-brush') as HTMLInputElement|null)?.checked??true;}
export function inkSettings():InkPaint {return {ink:[0,1,2,3].map(c=>Number((document.getElementById('ink-'+c) as HTMLInputElement).value)),channels:[0,1,2,3].filter(c=>(document.getElementById('ink-channel-'+c) as HTMLInputElement).checked),preserveAlpha:(document.getElementById('ink-alpha') as HTMLInputElement).checked};}
export function setInkValues(ink:readonly number[]){ink.forEach((v,c)=>{(document.getElementById('ink-'+c) as HTMLInputElement).value=String(Math.round(v*100)/100);});}
/** Tool settings stay local; only document edits enter history. */
export class CmykPanel {
 private root=document.createElement('section');private previous:Bitmap|null|undefined;
 constructor(private active:()=>ImageDocument|undefined,fill:()=>void,notify:(s:string,error?:boolean)=>void){this.root.id='cmyk-channels';this.root.className='cmyk-panel';this.root.hidden=true;this.root.innerHTML=`<div class="panel-title">CMYK 原生通道</div><p class="muted">勾选要编辑的分色；未选通道保持不变。</p><div class="ink-grid">${['C 青','M 洋红','Y 黄','K 黑'].map((name,c)=>`<label><span><input id="ink-channel-${c}" type="checkbox" checked>${name}</span><canvas width="96" height="40" aria-label="${name}通道预览"></canvas><span><input id="ink-${c}" aria-label="${name}油墨百分比" type="number" min="0" max="100" step="0.1" value="${c===3?100:0}"> %</span></label>`).join('')}</div><label><input id="native-ink-brush" type="checkbox" checked>画笔、填充与吸管使用原生油墨</label><label><input id="ink-alpha" type="checkbox">保留透明度</label><button id="ink-fill">填充所选通道</button><p class="muted">软硬度、笔压、不透明度使用画笔设置。其他 RGB 颜色工具通过文档 ICC 重新分色。粘贴 CMYK 时保留油墨数值。</p>`;document.querySelector('.sidebar')!.prepend(this.root);this.root.querySelector('#ink-fill')!.addEventListener('click',()=>{try{(document.getElementById('native-ink-brush') as HTMLInputElement).checked=true;fill();}catch(e){notify(e instanceof Error?e.message:String(e),true);}});}
 sync(){const d=this.active();this.root.hidden=d?.state.colorMode!=='cmyk';if(this.root.hidden)return;const l=d?.selected,b=l?.bitmap;(this.root.querySelector('#ink-fill') as HTMLButtonElement).disabled=!l||l.kind!=='pixel'||!!l.content||layerLocked(d!.state.layers,l.id,'pixels');if(b===this.previous)return;this.previous=b;
 this.root.querySelectorAll('canvas').forEach((canvas,c)=>{const ctx=canvas.getContext('2d')!,img=ctx.createImageData(canvas.width,canvas.height);for(let y=0;y<canvas.height;y++)for(let x=0;x<canvas.width;x++){const i=(y*canvas.width+x)*4,p=b?(Math.min(b.height-1,Math.floor(y*b.height/canvas.height))*b.width+Math.min(b.width-1,Math.floor(x*b.width/canvas.width)))*4:0,a=b?b.data[p+3]!/255:0,tone=b?.cmyk?255*(1-b.cmyk[p+c]!/100):255,v=tone*a+255*(1-a);img.data.set([v,v,v,255],i);}ctx.putImageData(img,0,0);});}
 dispose(){this.root.remove();}
}
