import { iccDocumentInfo } from './iccWorkflow.js';
import { embeddedProfile } from './colorManagement.js';
import type { ImageWorkspace } from './workspace.js';
import type { EditorJsonValue } from '@haiyue/editor-plugin-sdk';
/** Document precision, preview and ICC settings use the same public operation contract as IPC. */
export class ColorPanel {
 private boundId:string|undefined;private lastState:unknown;private urls=new Set<string>();
 private dialog=document.createElement('dialog');private hdrChanged=(e:Event)=>{this.dialog.querySelector('#hdr-output-status')!.textContent=(e as CustomEvent).detail.reason;};
 constructor(private workspace:ImageWorkspace,private notify:(s:string,error?:boolean)=>void){
 this.dialog.id='document-color-dialog';this.dialog.innerHTML=`<h2>位深、HDR 与 ICC</h2><p>32 位使用线性浮点像素；显示曝光和色调映射仅影响预览。PNG/JPEG 输出为 sRGB 8 位，PSD/工程保留文档位深。</p>
 <label>文档位深 <select id="document-depth"><option value="8">8 位</option><option value="16">16 位</option><option value="32">32 位浮点 HDR</option></select></label><label><input id="depth-loss" type="checkbox">确认降低位深时裁切高光并量化</label><button data-command="depth">转换位深</button>
 <label>显示输出 <select id="hdr-output"><option value="sdr">SDR 色调映射</option><option value="auto">自动系统 HDR／EDR</option><option value="hdr">系统 HDR／EDR（不可用时回退）</option></select></label><p id="hdr-output-status"></p><button data-command="display-report">导出 HDR 环境报告</button><label>显示曝光 EV <input id="hdr-display-ev" type="number" min="-20" max="20" step="0.25" value="0"></label><label>色调映射 <select id="hdr-display-map"><option value="clip">裁切</option><option value="reinhard">Reinhard</option><option value="aces">ACES 近似</option></select></label><button data-command="display">更新预览</button>
 <hr><p id="icc-document-summary" role="status"></p><label>目标配置 <select id="icc-preset"><option value="file">ICC 文件（RGB／CMYK）</option><option value="srgb">sRGB</option><option value="display-p3">Display P3</option><option value="adobe-rgb">Adobe RGB</option><option value="linear-srgb">线性 sRGB</option></select></label><label>工作配置（RGB／CMYK） <input id="icc-working-file" type="file" accept=".icc,.icm"></label><label>转换意图 <select id="icc-intent"><option value="0">感知</option><option value="1" selected>相对色度</option><option value="2">饱和度</option><option value="3">绝对色度</option></select></label><label><input id="icc-bpc" type="checkbox" checked>黑点补偿</label><button data-command="validate">检查 ICC／iccMAX</button><button data-command="assign">指定配置（保留数值）</button><button data-command="convert">转换到配置（调整像素数值）</button><button data-command="remove">移除工作配置（保留数值）</button><button data-command="read">导出当前 ICC</button><p class="muted">指定配置会改变颜色解释；转换配置尝试保持外观。未标记的 RGB 按 sRGB（32 位按线性 sRGB）解释，CMYK 未指定配置时只能近似预览。</p>
 <hr><p>CMYK 保留原生四通道，支持像素层、九种混合模式和蒙版。选择 CMYK ICC 后可转换；RGB 工具会对修改区域重新分色。</p><button data-command="cmyk">转换 CMYK</button><button data-command="rgb">转换 sRGB</button><label>C/M/Y/K（%） <input id="cmyk-ink" value="0,0,0,100"></label><button data-command="ink">填充当前层原生油墨</button><hr><label><input id="icc-proof-enabled" type="checkbox">启用软打样（关闭后保留配置）</label><label>打样意图 <select id="icc-proof-intent"><option value="0">感知</option><option value="1">相对色度</option><option value="2">饱和度</option><option value="3">绝对色度／纸白模拟</option></select></label><label>打样配置 <input id="icc-proof-file" type="file" accept=".icc,.icm"></label><label>显示器配置 <input id="icc-monitor-file" type="file" accept=".icc,.icm"></label><label><input id="icc-gamut" type="checkbox">色域警告</label><button data-command="proof">更新打样（空文件保留现有配置）</button><button data-command="clear-proof">移除打样配置</button><button data-command="clear-monitor">移除显示器配置</button><p class="muted">显示器配置用于预览模拟；浏览器仍负责最终系统显示转换。打样与色域警告不写入导出的图片像素。</p><p id="document-color-status" role="status"></p><div class="dialog-actions"><button data-close>关闭</button></div>`;
 this.input('icc-proof-file').addEventListener('change',()=>{if(this.input('icc-proof-file').files?.length)this.input('icc-proof-enabled').checked=true;});
 document.body.append(this.dialog);window.addEventListener('haiyue-hdr-status',this.hdrChanged);this.dialog.querySelector('[data-close]')!.addEventListener('click',()=>this.dialog.close());for(const b of this.dialog.querySelectorAll<HTMLButtonElement>('[data-command]'))b.onclick=()=>void this.apply(b.dataset.command!);
 }
 private input(id:string){return this.dialog.querySelector<HTMLInputElement>('#'+id)!;}
 open(){const d=this.workspace.active;if(!d)throw Error('请先打开文档。');this.boundId=d.identity.id;this.lastState=undefined;for(const id of ['icc-working-file','icc-proof-file','icc-monitor-file'])this.input(id).value='';this.input('icc-preset').value='file';this.dialog.querySelector('#document-color-status')!.textContent='';this.dialog.showModal();this.sync();}
 sync(){if(!this.dialog.open)return;const d=this.workspace.active;if(!d||d.identity.id!==this.boundId){this.dialog.close();return;}if(this.lastState===d.state)return;this.lastState=d.state;const info=iccDocumentInfo(d.state);
 this.dialog.querySelector('#icc-document-summary')!.textContent=`${info.colorMode.toUpperCase()} · ${d.state.bitDepth??8} 位 · ${info.working?info.working.name+' / ICC '+info.working.version:'未嵌入 ICC：'+(info.effective==='approximate-cmyk'?'CMYK 近似预览':info.effective==='assumed-linear-srgb'?'按线性 sRGB 解释':'按 sRGB 解释')}${info.reason?' · '+info.reason:''}\n打样：${info.proof?.name??'无'}（${info.proofEnabled?'启用':'关闭'}） · 显示器模拟：${info.monitor?.name??'无'}`;
 this.input('hdr-output').value=d.state.display?.output??'sdr';this.dialog.querySelector('#hdr-output-status')!.textContent=JSON.parse(document.querySelector('#image-canvas')?.getAttribute('data-hdr-status')??'{}').reason??'';this.input('depth-loss').checked=false;this.input('icc-intent').value=String(info.intent);this.input('icc-bpc').checked=info.bpc;this.input('icc-gamut').checked=info.gamutWarning;this.input('icc-proof-enabled').checked=info.proofEnabled;this.input('icc-proof-intent').value=String(info.proofIntent);this.input('document-depth').value=String(d.state.bitDepth??8);this.input('hdr-display-ev').value=String(d.state.display?.exposure??0);this.input('hdr-display-map').value=d.state.display?.operator??'clip';
 }
 private async apply(mode:string){const d=this.workspace.active;if(!d||d.identity.id!==this.boundId)return;const revision=d.revision;const resources:string[]=[],buttons=[...this.dialog.querySelectorAll<HTMLButtonElement>('button')],status=this.dialog.querySelector('#document-color-status')!;buttons.forEach(b=>b.disabled=true);const value=(id:string)=>this.input(id).value;
 try{const load=async(id:string,required=false)=>{const file=this.input(id).files?.[0];if(!file){if(required)throw Error('请选择 ICC 文件。');return undefined;}if(file.size>4*1024*1024)throw Error('ICC 文件超过 4 MiB。');const r=this.workspace.platform.resources.put(new Uint8Array(await file.arrayBuffer()));resources.push(r.resourceId);return r.resourceId;};
 let operation:string,params:EditorJsonValue;
 if(mode==='depth'){operation='document.depth';params={depth:Number(value('document-depth')),allowLoss:this.input('depth-loss').checked};}
 else if(mode==='display-report'){operation='display.query';params={};}
 else if(mode==='display'){operation='document.display';params={output:value('hdr-output'),exposure:Number(value('hdr-display-ev')),operator:value('hdr-display-map')};}
 else if(mode==='validate'){operation='icc.reference';params={mode:'validate',profiles:[{profileId:(await load('icc-working-file',true))!,intent:1}]};}
 else if(mode==='cmyk'||mode==='rgb'){operation='cmyk.mode';params={mode,...(mode==='cmyk'?{profileId:(await load('icc-working-file',true))!}:{})};}
 else if(mode==='ink'){operation='cmyk.fill';params={layerId:d.state.selectedId,ink:value('cmyk-ink').split(',').map(Number)};}
 else if(mode==='remove'||mode==='read'){operation='icc.'+mode;params=mode==='read'?{slot:'working'}:{};}
 else if(mode==='clear-proof'||mode==='clear-monitor'){operation='icc.proof';params=mode==='clear-proof'?{clearProof:true}:{clearMonitor:true};}
 else {operation='icc.'+mode;const preset=value('icc-preset'),profileId=mode==='proof'||preset!=='file'?undefined:await load('icc-working-file',true),proofProfile=mode==='proof'?await load('icc-proof-file'):undefined,monitorProfile=mode==='proof'?await load('icc-monitor-file'):undefined;params={intent:Number(value('icc-intent')),bpc:this.input('icc-bpc').checked,...(mode==='proof'?{proofIntent:Number(value('icc-proof-intent')),gamutWarning:this.input('icc-gamut').checked,proofEnabled:this.input('icc-proof-enabled').checked}:{}),...(mode!=='proof'&&preset!=='file'?{preset}:{}),...(profileId?{profileId}:{}),...(proofProfile?{proofProfile}:{}),...(monitorProfile?{monitorProfile}:{})};}
 const result=await this.workspace.platform.operations.execute({apiVersion:'1',requestId:crypto.randomUUID(),operation:'image.'+operation,...(mode==='validate'||mode==='display-report'?{}:{documentId:d.identity.id,expectedRevision:revision}),params});if(result.status!=='completed')throw Error(result.error.message);if(mode==='validate'){const value=result.value as {resourceId:string;status:string};resources.push(value.resourceId);const report=new TextDecoder().decode(this.workspace.platform.resources.read(value.resourceId));status.textContent=value.status+'\n'+report.slice(0,12000)+(report.length>12000?'\n（界面只显示前 12000 字；API 可读取完整报告）':'');}else if(mode==='display-report'){const url=URL.createObjectURL(new Blob([JSON.stringify(result.value,null,2)],{type:'application/json'})),link=document.createElement('a');this.urls.add(url);link.href=url;link.download='haiyue-hdr-environment.json';link.click();setTimeout(()=>{URL.revokeObjectURL(url);this.urls.delete(url);},30000);status.textContent='已导出浏览器能力和当前显示后端；不包含物理亮度认证。';}else if(mode==='read'){const value=result.value as {resourceId:string};resources.push(value.resourceId);const url=URL.createObjectURL(new Blob([this.workspace.platform.resources.read(value.resourceId).slice().buffer],{type:'application/vnd.iccprofile'})),link=document.createElement('a');this.urls.add(url);link.href=url;link.download='haiyue-document.icc';link.click();setTimeout(()=>{URL.revokeObjectURL(url);this.urls.delete(url);},30000);status.textContent='已导出原始 ICC 配置。';}else {this.sync();status.textContent='已应用，可撤销。';}
 }catch(e){status.textContent=e instanceof Error?e.message:String(e);this.notify(status.textContent,true);}finally{resources.forEach(id=>this.workspace.platform.resources.release(id));buttons.forEach(b=>b.disabled=false);}}
 dispose(){for(const url of this.urls)URL.revokeObjectURL(url);this.urls.clear();window.removeEventListener('haiyue-hdr-status',this.hdrChanged);this.dialog.remove();}
}
