import { diskPager, readDiskPixels, type DiskRef } from './diskPager.js';
import { compositeHalo, compositeRegion, type CompositeRect } from './compositor.js';
import type { Bitmap, ImageState, ImageLayer } from './document.js';
import { PAGE_SIZE, bitmapRegion, type PixelPages } from './pagedPixels.js';
export function bitmapRefs(b:Bitmap,rect:CompositeRect={x:0,y:0,width:b.width,height:b.height}):DiskRef[]{const result:DiskRef[]=[];const visit=(p:PixelPages,index:number)=>{if(p.kind==='disk'){result.push(...p.tiles[index]!.chunks,...(p.inks?.[index]?.chunks??[]));}else if(p.kind==='overlay'&&!p.tiles.some(t=>t.index===index))visit(p.base,index);};if(!b.pages||!rect.width||!rect.height)return result;const columns=Math.ceil(b.width/PAGE_SIZE);for(let y=Math.floor(rect.y/PAGE_SIZE);y<=Math.floor((rect.y+rect.height-1)/PAGE_SIZE);y++)for(let x=Math.floor(rect.x/PAGE_SIZE);x<=Math.floor((rect.x+rect.width-1)/PAGE_SIZE);x++)visit(b.pages,y*columns+x);return result;}
export async function bitmapRegionAsync(b:Bitmap,rect:CompositeRect,signal?:AbortSignal){if(![rect.x,rect.y,rect.width,rect.height].every(Number.isInteger)||rect.x<0||rect.y<0||rect.width<1||rect.height<1||rect.x+rect.width>b.width||rect.y+rect.height>b.height)throw Error('异步像素区域无效。');const release=await diskPager.lease(bitmapRefs(b,rect),signal);try{return await readDiskPixels(()=>bitmapRegion(b,rect.x,rect.y,rect.width,rect.height),signal);}finally{release();}}
export async function compositeRegionAsync(state:ImageState,rect:CompositeRect,signal?:AbortSignal){const halo=Math.ceil(compositeHalo(state.layers)),refs:DiskRef[]=[];const walk=(layers:readonly ImageLayer[],px=0,py=0)=>{for(const l of layers){if(!l.visible||!l.opacity)continue;const left=px+l.x,top=py+l.y,b=l.bitmap;if(b){const x=Math.max(0,rect.x-halo-left),y=Math.max(0,rect.y-halo-top),right=Math.min(b.width,rect.x+rect.width+halo-left),bottom=Math.min(b.height,rect.y+rect.height+halo-top);if(right>x&&bottom>y)refs.push(...bitmapRefs(b,l.smartFilters?.some(f=>f.enabled)?undefined:{x,y,width:right-x,height:bottom-y}));}walk(l.children,left,top);}};walk(state.layers);const release=await diskPager.lease(refs,signal);try{signal?.throwIfAborted();return await readDiskPixels(()=>compositeRegion(state,rect),signal);}finally{release();}}
export async function forEachCompositeTileAsync(state:ImageState,visit:(bitmap:Bitmap,rect:CompositeRect)=>void|Promise<void>,signal?:AbortSignal,size=128,region:CompositeRect={x:0,y:0,width:state.width,height:state.height}){if(![region.x,region.y,region.width,region.height].every(Number.isInteger)||region.x<0||region.y<0||region.width<1||region.height<1||region.x+region.width>state.width||region.y+region.height>state.height)throw Error('异步合成区域无效。');if(!Number.isInteger(size)||size<16||size>1024)throw Error('异步合成块大小无效。');for(let y=region.y;y<region.y+region.height;y+=size)for(let x=region.x;x<region.x+region.width;x+=size){signal?.throwIfAborted();const rect={x,y,width:Math.min(size,region.x+region.width-x),height:Math.min(size,region.y+region.height-y)},b=await compositeRegionAsync(state,rect,signal);signal?.throwIfAborted();await visit(b,rect);}}
export async function compositeStateAsync(state:ImageState,signal?:AbortSignal):Promise<Bitmap>{const bytes=state.width*state.height*((state.bitDepth??8)===8?4:16);if(bytes>128*1024*1024)throw Error('合成输出超过 128 MiB；请使用分块合成接口。');const data=(state.bitDepth??8)===8?new Uint8ClampedArray(state.width*state.height*4):new Float32Array(state.width*state.height*4),inks=state.colorMode==='cmyk'?new Float32Array(data.length):undefined;if(bytes+(inks?.byteLength??0)>128*1024*1024)throw Error('分色合成输出超过 128 MiB；请使用分块合成接口。');await forEachCompositeTileAsync(state,(b,r)=>{for(let y=0;y<r.height;y++){const offset=((r.y+y)*state.width+r.x)*4;data.set(b.data.subarray(y*r.width*4,(y+1)*r.width*4),offset);if(inks)inks.set(b.cmyk!.subarray(y*r.width*4,(y+1)*r.width*4),offset);}},signal);return {width:state.width,height:state.height,data,...(state.bitDepth?{depth:state.bitDepth}:{}),...(inks?{cmyk:inks}:{})};}
