/** Immutable content-addressed pages. Disk writes complete before references can replace RAM. */
export interface DiskRef {key:string;bytes:number}
export interface DiskBlob {bytes:number;chunks:DiskRef[]}
export interface PageStore {read(key:string):Promise<Uint8Array|undefined>;write(key:string,bytes:Uint8Array):Promise<void>}
export const DISK_PAGE_SIZE=256*1024;
const keyOf=async(bytes:Uint8Array)=>'page:'+Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as Uint8Array<ArrayBuffer>)),v=>v.toString(16).padStart(2,'0')).join('');
export function validateDiskRef(r:DiskRef){if(!r||!/^page:[a-f0-9]{64}$/.test(r.key)||!Number.isSafeInteger(r.bytes)||r.bytes<1||r.bytes>DISK_PAGE_SIZE)throw Error('磁盘页引用无效。');}
export function validateDiskBlob(b:DiskBlob){if(!b||!Number.isSafeInteger(b.bytes)||b.bytes<0||b.bytes>128*1024*1024||!Array.isArray(b.chunks)||b.chunks.length!==Math.ceil(b.bytes/DISK_PAGE_SIZE))throw Error('磁盘块目录无效。');b.chunks.forEach((r,i)=>{validateDiskRef(r);if(r.bytes!==Math.min(DISK_PAGE_SIZE,b.bytes-i*DISK_PAGE_SIZE))throw Error('磁盘块长度不符。');});}
function cancellable<T>(promise:Promise<T>,signal?:AbortSignal):Promise<T>{if(!signal)return promise;signal.throwIfAborted();return new Promise<T>((resolve,reject)=>{const abort=()=>{signal.removeEventListener('abort',abort);reject(signal.reason??new DOMException('已取消','AbortError'));};signal.addEventListener('abort',abort,{once:true});promise.then(value=>{signal.removeEventListener('abort',abort);resolve(value);},error=>{signal.removeEventListener('abort',abort);reject(error);});});}
export class DiskPageMiss extends Error {constructor(readonly ref:DiskRef){super('像素页尚未载入；请使用异步像素接口。');}}
export class IndexedDbPageStore implements PageStore {
 private connection:Promise<IDBDatabase>|undefined;
 private db(){return this.connection??=new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('haiyue.image-editor.v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('recovery');r.onerror=()=>{this.connection=undefined;reject(r.error);};r.onblocked=()=>{this.connection=undefined;reject(Error('本地磁盘页数据库被占用。'));};r.onsuccess=()=>{const db=r.result;db.onversionchange=()=>{db.close();this.connection=undefined;};resolve(db);};});}
 async read(key:string){const db=await this.db();return new Promise<Uint8Array|undefined>((resolve,reject)=>{const tx=db.transaction('recovery'),r=tx.objectStore('recovery').get(key);tx.oncomplete=()=>resolve(r.result);tx.onabort=tx.onerror=()=>reject(tx.error??Error('磁盘页读取失败。'));});}
 async write(key:string,bytes:Uint8Array){const db=await this.db();await new Promise<void>((resolve,reject)=>{const tx=db.transaction('recovery','readwrite');tx.objectStore('recovery').put(bytes,key);tx.oncomplete=()=>resolve();tx.onabort=tx.onerror=()=>reject(tx.error??Error('磁盘页写入失败，可能没有足够空间。'));});}
}
interface Entry {data:Uint8Array;pins:number}
export class DiskPager {
 private cache=new Map<string,Entry>();private pending=new Map<string,Promise<Uint8Array>>();private reservations=new Map<string,number>();private serial:Promise<unknown>=Promise.resolve();
 private resident=0;private held=0;private counters={reads:0,writes:0,hits:0,evictions:0,peakBytes:0};
 constructor(readonly store:PageStore,readonly budget=16*1024*1024,readonly workingBudget=128*1024*1024){if(!Number.isSafeInteger(budget)||budget<DISK_PAGE_SIZE||!Number.isSafeInteger(workingBudget)||workingBudget<budget)throw Error('磁盘页缓存预算无效。');}
 stats(){return {...this.counters,residentBytes:this.resident,budget:this.budget,workingBudget:this.workingBudget,pinnedBytes:this.held,pendingReads:this.pending.size};}
 private trim(){for(const [key,e] of this.cache){if(this.resident<=this.budget)break;if(!e.pins){this.cache.delete(key);this.resident-=e.data.length;this.counters.evictions++;}}}
 clear(){for(const [key,e] of this.cache)if(!e.pins){this.cache.delete(key);this.resident-=e.data.length;}}
 private remember(ref:DiskRef,data:Uint8Array){const old=this.cache.get(ref.key);if(old){this.resident-=old.data.length;this.cache.delete(ref.key);}this.cache.set(ref.key,{data,pins:this.reservations.get(ref.key)??0});this.resident+=data.length;this.trim();this.counters.peakBytes=Math.max(this.counters.peakBytes,this.resident);}
 peek(ref:DiskRef):Uint8Array {validateDiskRef(ref);const e=this.cache.get(ref.key);if(!e)throw new DiskPageMiss(ref);if(e.data.length!==ref.bytes)throw Error('磁盘页长度不符。');this.cache.delete(ref.key);this.cache.set(ref.key,e);this.counters.hits++;return e.data;}
 async read(ref:DiskRef,signal?:AbortSignal):Promise<Uint8Array>{validateDiskRef(ref);signal?.throwIfAborted();const hit=this.cache.get(ref.key);if(hit)return this.peek(ref);let p=this.pending.get(ref.key);if(!p){p=this.serial.then(async()=>{const bytes=await this.store.read(ref.key);if(!(bytes instanceof Uint8Array)||bytes.length!==ref.bytes||await keyOf(bytes)!==ref.key)throw Error('磁盘页缺失或校验失败。');this.counters.reads++;this.remember(ref,bytes);return bytes;});this.serial=p.catch(()=>{});this.pending.set(ref.key,p);void p.finally(()=>this.pending.delete(ref.key)).catch(()=>{});}const result=await cancellable(p,signal);signal?.throwIfAborted();if(result.length!==ref.bytes)throw Error('磁盘页引用长度冲突。');return result;}
 async write(bytes:Uint8Array,signal?:AbortSignal):Promise<DiskBlob>{const refs:DiskRef[]=[];for(let i=0;i<bytes.length;i+=DISK_PAGE_SIZE){signal?.throwIfAborted();const start=i,job=this.serial.then(async()=>{signal?.throwIfAborted();const part=bytes.slice(start,start+DISK_PAGE_SIZE),key=await keyOf(part),ref={key,bytes:part.length};await this.store.write(key,part);this.counters.writes++;return ref;});this.serial=job.catch(()=>{});refs.push(await cancellable(job,signal));}signal?.throwIfAborted();return {bytes:bytes.length,chunks:refs};}
 /** A lease reserves its entire working set before any I/O; other readers cannot evict it. */
 async lease(refs:readonly DiskRef[],signal?:AbortSignal){const unique=new Map<string,DiskRef>();for(const ref of refs){validateDiskRef(ref);const old=unique.get(ref.key);if(old&&old.bytes!==ref.bytes)throw Error('磁盘页引用长度冲突。');unique.set(ref.key,ref);}const extra=[...unique.values()].reduce((n,r)=>n+(this.reservations.has(r.key)?0:r.bytes),0);if(this.held+extra>this.workingBudget)throw Error('操作工作集超过换页预算；请缩小操作区域或分批处理。');this.held+=extra;for(const r of unique.values()){this.reservations.set(r.key,(this.reservations.get(r.key)??0)+1);const e=this.cache.get(r.key);if(e)e.pins++;}let released=false;const release=()=>{if(released)return;released=true;for(const r of unique.values()){const n=this.reservations.get(r.key)!-1;if(n)this.reservations.set(r.key,n);else{this.reservations.delete(r.key);this.held-=r.bytes;}const e=this.cache.get(r.key);if(e)e.pins=Math.max(0,e.pins-1);}this.trim();};try{for(const r of unique.values())await this.read(r,signal);return release;}catch(e){release();throw e;}}
 async blob(b:DiskBlob,signal?:AbortSignal){validateDiskBlob(b);const result=new Uint8Array(b.bytes);let offset=0;for(const r of b.chunks){result.set(await this.read(r,signal),offset);offset+=r.bytes;}return result;}
 syncBlob(b:DiskBlob){validateDiskBlob(b);if(b.chunks.length===1)return this.peek(b.chunks[0]!);const result=new Uint8Array(b.bytes);let offset=0;for(const r of b.chunks){result.set(this.peek(r),offset);offset+=r.bytes;}return result;}
}
export const diskPager=new DiskPager(new IndexedDbPageStore());
export function diskRefs(value:unknown):DiskRef[]{const refs=new Map<string,DiskRef>(),seen=new Set<object>();const walk=(v:unknown)=>{if(!v||typeof v!=='object'||seen.has(v)||ArrayBuffer.isView(v))return;seen.add(v);if('key'in v&&'bytes'in v&&typeof v.key==='string'&&v.key.startsWith('page:')){validateDiskRef(v as DiskRef);refs.set(v.key,v as DiskRef);return;}Object.values(v).forEach(walk);};walk(value);return [...refs.values()];}
export async function withDiskPages<T>(value:unknown,read:()=>T|Promise<T>,signal?:AbortSignal):Promise<T>{const refs=diskRefs(value);if(!refs.length)return read();const release=await diskPager.lease(refs,signal);try{signal?.throwIfAborted();return await read();}finally{release();}}
/** Retry only pure reads; never use this to replay document mutations or external side effects. */
export async function readDiskPixels<T>(read:()=>T,signal?:AbortSignal):Promise<T>{const releases:(()=>void)[]=[];const seen=new Set<string>();try{for(;;){signal?.throwIfAborted();try{return read();}catch(e){if(!(e instanceof DiskPageMiss))throw e;if(seen.has(e.ref.key))throw Error('磁盘页工作集无法稳定载入。');seen.add(e.ref.key);releases.push(await diskPager.lease([e.ref],signal));}}}finally{for(const release of releases)release();}}

export interface DiskBacking {inline?:Uint8Array;disk?:DiskBlob}
export function hydrateArchive<T extends {psdArchive?:Uint8Array;psdArchiveStore?:DiskBacking}>(state:T):T {
 if(state.psdArchiveStore){if(!Object.getOwnPropertyDescriptor(state,'psdArchive'))Object.defineProperty(state,'psdArchive',{enumerable:false,configurable:true,get:()=>state.psdArchiveStore!.inline??diskPager.syncBlob(state.psdArchiveStore!.disk!)});}
 else if(state.psdArchive){const bytes=state.psdArchive;delete state.psdArchive;state.psdArchiveStore={inline:bytes};hydrateArchive(state);}
 return state;
}
export const archiveBytes=(state:{psdArchive?:Uint8Array;psdArchiveStore?:DiskBacking})=>state.psdArchiveStore?.disk?.bytes??state.psdArchiveStore?.inline?.byteLength??state.psdArchive?.byteLength??0;
