import { diskPager, diskRefs, withDiskPages, hydrateArchive, type DiskRef } from './diskPager.js';
import { allLayers, type ImageState } from './document.js';
import { spillBitmap, clearPagedPixelCache, hasDiskPixels } from './pagedPixels.js';
const spilling=new WeakMap<object,Promise<void>>();
export async function spillState(state:ImageState,signal?:AbortSignal){
 hydrateArchive(state);if(state.paging)state.paging.enabled=true;
 for(const layer of allLayers(state.layers))for(const bitmap of [layer.bitmap,layer.content?.type==='smart'?layer.content.source:null])if(bitmap){if(bitmap.pages?.kind==='disk')continue;let job=spilling.get(bitmap);if(!job){job=withDiskPages(bitmap,()=>spillBitmap(bitmap,signal),signal);spilling.set(bitmap,job);void job.finally(()=>spilling.delete(bitmap)).catch(()=>{});}await job;signal?.throwIfAborted();}
 const archive=state.psdArchiveStore;if(archive?.inline){const original=archive.inline,stored=await diskPager.write(original,signal);signal?.throwIfAborted();archive.disk=stored;delete archive.inline;}
 clearPagedPixelCache();diskPager.clear();return diskPager.stats();
}
export function storageInfo(state:ImageState){const refs=diskRefs(state);return {mode:hasDiskPixels(state)?'disk':state.layers.some(l=>l.bitmap?.pages)?'paged':'dense',pages:refs.length,diskBytes:refs.reduce((n,r)=>n+r.bytes,0),pager:diskPager.stats()};}
const encode=(b:Uint8Array)=>{const parts:string[]=[];for(let i=0;i<b.length;i+=24576)parts.push(btoa(String.fromCharCode(...b.subarray(i,i+24576))));return parts.join('');};
/** Portable export embeds every disk page; it never exports machine-local references alone. */
export async function serializeDiskProject(state:ImageState,signal?:AbortSignal):Promise<string>{const {serializeProject}=await import('./projectFile.js');const refs=diskRefs(state);if(!refs.length)return serializeProject(state);if(refs.reduce((n,r)=>n+r.bytes,0)>128*1024*1024)throw Error('便携工程超过 128 MiB 导出预算，请分批导出。');const pages:Record<string,string>={};for(const ref of refs){signal?.throwIfAborted();pages[ref.key]=encode(await diskPager.read(ref,signal));}return JSON.stringify({format:'haiyue-image',version:14,project:serializeProject(state,true),pages});}
export async function deserializeDiskProject(source:string,newIdentity=false,signal?:AbortSignal):Promise<ImageState>{const {deserializeProject}=await import('./projectFile.js');if(source.length>210*1024*1024)throw Error('工程文件过大。');const envelope=JSON.parse(source);if(envelope.version!==14)return deserializeProject(source,newIdentity);if(envelope.format!=='haiyue-image'||typeof envelope.project!=='string'||!envelope.pages||typeof envelope.pages!=='object'||Array.isArray(envelope.pages))throw Error('磁盘工程包无效。');const state=deserializeProject(envelope.project,newIdentity,true),refs=diskRefs(state);if(Object.keys(envelope.pages).length!==refs.length||refs.reduce((n,r)=>n+r.bytes,0)>128*1024*1024)throw Error('磁盘工程目录超出预算。');for(const ref of refs){signal?.throwIfAborted();const text=envelope.pages[ref.key];if(typeof text!=='string'||text.length!==4*Math.ceil(ref.bytes/3)||!/^[A-Za-z0-9+/]*={0,2}$/.test(text))throw Error('磁盘工程页编码无效。');const bytes=Uint8Array.from(atob(text),c=>c.charCodeAt(0));await install(ref,bytes,signal);}return state;}
async function install(ref:DiskRef,bytes:Uint8Array,signal?:AbortSignal){const hash='page:'+Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as Uint8Array<ArrayBuffer>)),v=>v.toString(16).padStart(2,'0')).join('');if(bytes.length!==ref.bytes||hash!==ref.key)throw Error('磁盘工程页校验失败。');await diskPager.write(bytes,signal);}
