import type { Bitmap } from './document.js';
import { cmykBitmap } from './cmyk.js';
import { readPsd, writePsdUint8Array, type Psd, type Layer, type PixelData, type ReadOptions } from 'ag-psd';
import { Inflate } from 'pako';
import { concatBytes, psdSections } from './psdResources.js';
import { normalizeExportedLevels } from './psdLevels.js';
import { checkSize, IMAGE_LIMITS } from './document.js';
const u32=(n:number)=>{const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n);return b;};
const section=(b:Uint8Array)=>concatBytes([u32(b.length),b]);
const tag=(key:string,b:Uint8Array)=>concatBytes([new TextEncoder().encode('8BIM'+key),u32(b.length),b,new Uint8Array(b.length%2)]);
/** Decode one plane with a strict output bound, including ZIP prediction and byte-order differences. */
export function decodePsdPlane(input:Uint8Array,compression:number,width:number,height:number,depth:number):Uint8Array {
 const row=width*depth/8,length=row*height;let out:Uint8Array;
 if(compression===0){if(input.length!==length)throw Error('PSD 原始通道长度不符。');out=input.slice();}
 else if(compression===1){out=new Uint8Array(length);const v=new DataView(input.buffer,input.byteOffset,input.byteLength);if(input.length<height*2)throw Error('PSD RLE 行表截断。');let p=height*2;for(let y=0;y<height;y++){const end=p+v.getUint16(y*2);if(end>input.length)throw Error('PSD RLE 行截断。');let x=0;while(p<end){const n=input[p++]!;if(n<128){const size=n+1;if(x+size>row||p+size>end)throw Error('PSD RLE 字面量无效。');out.set(input.subarray(p,p+size),y*row+x);x+=size;p+=size;}else if(n>128){const size=257-n;if(x+size>row||p>=end)throw Error('PSD RLE 重复段无效。');out.fill(input[p++]!,y*row+x,y*row+x+size);x+=size;}}if(x!==row)throw Error('PSD RLE 行宽不符。');}if(p!==input.length)throw Error('PSD RLE 尾部数据无效。');}
 else if(compression===2||compression===3){out=new Uint8Array(length);let offset=0;const decoder=new Inflate({chunkSize:65536});decoder.onData=chunk=>{if(offset+chunk.length>length)throw Error('PSD ZIP 超出声明像素预算。');out.set(chunk,offset);offset+=chunk.length;};if(!decoder.push(input,true)||decoder.err)throw Error('PSD ZIP 校验失败：'+(decoder.msg||'数据损坏或截断')+'。');if(offset!==length)throw Error('PSD ZIP 解码长度与声明尺寸不符。');
  if(compression===3){if(depth===16){const v=new DataView(out.buffer);for(let y=0;y<height;y++)for(let x=1;x<width;x++){const i=(y*width+x)*2;v.setUint16(i,(v.getUint16(i)+v.getUint16(i-2))&65535);}}else{for(let y=0;y<height;y++)for(let x=1;x<row;x++){const i=y*row+x;out[i]=(out[i]!+out[i-1]!)&255;}if(depth===32){const copy=out.slice();for(let y=0;y<height;y++)for(let x=0;x<width;x++)for(let c=0;c<4;c++)out[(y*width+x)*4+c]=copy[y*row+c*width+x]!;}}}
 }else throw Error('PSD 压缩方式无效。');return out;
}
function numeric(bytes:Uint8Array,depth:number):Uint8Array|Uint16Array|Float32Array {const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);return depth===8?bytes:depth===16?Uint16Array.from({length:bytes.length/2},(_,i)=>v.getUint16(i*2)):Float32Array.from({length:bytes.length/4},(_,i)=>v.getFloat32(i*4));}
function nativeMergedAlpha(bytes:Uint8Array):boolean {
 const sec=psdSections(bytes).layers,v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(sec.end-sec.data<4)return false;const length=v.getUint32(sec.data);if(length){if(length<2||sec.data+4+length>sec.end)throw Error('PSD 图层信息截断。');return v.getInt16(sec.data+4)<0;}let p=sec.data+4;if(p+4>sec.end)return false;p+=4+v.getUint32(p);while(p+12<=sec.end){while(p<sec.end&&bytes[p]===0)p++;if(p+12>sec.end)break;const sig=v.getUint32(p),wide=sig===0x38423634;if(sig!==0x3842494d&&!wide)throw Error('PSD 全局块签名无效。');const h=wide?16:12;if(p+h>sec.end)throw Error('PSD 全局块截断。');const n=wide?Number(v.getBigUint64(p+8)):v.getUint32(p+8);if(!Number.isSafeInteger(n)||p+h+n>sec.end)throw Error('PSD 全局块长度无效。');if(v.getUint32(p+4)===0x4c723136)return n>=2&&v.getInt16(p+h)<0;p+=h+n+n%2;}return false;
}
/** CMYK uses the RGB metadata reader only; channel interpretation stays native. */
export function readPsdMetadata(bytes:Uint8Array,options:ReadOptions={}):Psd {
 const cmyk=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint16(24)===4;
 const metadata=cmyk?bytes.slice():bytes;if(cmyk)new DataView(metadata.buffer,metadata.byteOffset).setUint16(24,3);
 return readPsd(metadata,{...options,useRawData:true,skipCompositeImageData:true,skipThumbnail:true,totalMemoryLimit:IMAGE_LIMITS.bytes});
}
export function readHighPsd(bytes:Uint8Array,options:{metadata?:Psd;compositeOnly?:boolean}={}):Psd {
 const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),depth=v.getUint16(22),channels=v.getUint16(12),cmyk=v.getUint16(24)===4;if(!(cmyk?[8,16].includes(depth):[16,32].includes(depth))||![3,4].includes(v.getUint16(24))||channels<(cmyk?4:3)||channels>(cmyk?5:4))throw Error('高位深 PSD 目前需要 RGB，3 或 4 通道。');
 // ag-psd rejects the CMYK header even in raw mode. Only its metadata reader sees this RGB header; every channel is decoded below without RGB conversion.
 if(cmyk&&channels===5&&!nativeMergedAlpha(bytes))throw Error('CMYK 第五通道未声明合并透明度；额外 Alpha／专色不可当作透明通道。');
 const psd=options.metadata??readPsdMetadata(bytes),layers=psd.children??[];checkSize(psd.width,psd.height);const pixelBytes=(depth===8?4:16)+(cmyk?16:0);let budget=psd.width*psd.height*pixelBytes,count=0;
 if(budget>IMAGE_LIMITS.bytes)throw Error('PSD 合并图解码超过文档预算。');
 const make=(w:number,h:number):PixelData=>{checkSize(w,h);budget+=w*h*pixelBytes;if(budget>IMAGE_LIMITS.bytes)throw Error('高位深 PSD 解码超过文档预算。');const data=depth===8?new Uint8ClampedArray(w*h*4):depth===16?new Uint16Array(w*h*4):new Float32Array(w*h*4);for(let i=3;i<data.length;i+=4)data[i]=depth===8?255:depth===16?65535:1;return {width:w,height:h,data,...(cmyk?{cmyk:new Float32Array(w*h*4)}:{})};};
 const visit=(items:Layer[],nest=0)=>{if(nest>16)throw Error('PSD 图层嵌套过深。');for(const l of items){if(++count>128)throw Error('PSD 图层过多。');const raw=l.rawData;const w=(l.right??0)-(l.left??0),h=(l.bottom??0)-(l.top??0);if(w<0||h<0)throw Error('PSD 图层范围无效。');const bitmap=w&&h&&!l.children?make(w,h):undefined;for(const c of raw?.channels??[]){if(!c.data)continue;const mask=c.id===-2?l.mask:c.id===-3?l.realMask:undefined;if(c.id< -1&&!mask)throw Error('未知高位深通道。');let target=bitmap;if(mask){const mw=(mask.right??0)-(mask.left??0),mh=(mask.bottom??0)-(mask.top??0);if(mw<0||mh<0)throw Error('PSD 蒙版范围无效。');if(!mw||!mh)continue;target=make(mw,mh);mask.imageData=target;}if(!target)continue;const samples=numeric(decodePsdPlane(c.data,c.compression,target.width,target.height,depth),depth),channel=c.id===-1?3:c.id;for(let i=0;i<samples.length;i++){if(mask)for(let k=0;k<3;k++)target.data[i*4+k]=samples[i]!;else if(cmyk&&c.id>=0&&c.id<4)(target as unknown as Bitmap).cmyk![i*4+c.id]=(1-samples[i]!/(depth===8?255:65535))*100;else if(channel>=0&&channel<4)target.data[i*4+channel]=samples[i]!;else throw Error('不支持额外高位深通道。');}}
 if(bitmap){if(cmyk){if(![0,1,2,3].every(id=>raw?.channels.some(c=>c.id===id&&c.data)))throw Error('CMYK 图层缺少原生通道。');const b=cmykBitmap(bitmap.width,bitmap.height,(bitmap as unknown as Bitmap).cmyk!,Array.from({length:bitmap.width*bitmap.height},(_,i)=>bitmap.data[i*4+3]!/(depth===8?1:257)),depth as 8|16);for(let i=0;i<b.data.length;i++)bitmap.data[i]=b.data[i]!*(depth===8?1:257);}l.imageData=bitmap;}delete l.rawData;visit(l.children??[],nest+1);}};if(!options.compositeOnly)visit(layers);
 const start=psdSections(bytes).composite,compression=v.getUint16(start),w=psd.width,h=psd.height,n=w*h,plane=n*depth/8,data=depth===8?new Uint8ClampedArray(n*4):depth===16?new Uint16Array(n*4):new Float32Array(n*4);let planes:Uint8Array[]=[];
 if(compression===0){if(start+2+plane*channels!==bytes.length)throw Error('PSD 高位深合成长度不符。');planes=Array.from({length:channels},(_,c)=>bytes.subarray(start+2+c*plane,start+2+(c+1)*plane));}
 else if(compression===1){let p=start+2+channels*h*2;if(p>bytes.length)throw Error('PSD 合成行表截断。');for(let c=0;c<channels;c++){let length=0;for(let y=0;y<h;y++)length+=v.getUint16(start+2+(c*h+y)*2);const table=bytes.slice(start+2+c*h*2,start+2+(c+1)*h*2);if(p+length>bytes.length)throw Error('PSD 合成 RLE 截断。');planes.push(decodePsdPlane(concatBytes([table,bytes.subarray(p,p+length)]),1,w,h,depth));p+=length;}if(p!==bytes.length)throw Error('PSD 合成尾部数据无效。');}
 else {const unpacked=decodePsdPlane(bytes.subarray(start+2),compression,w,h*channels,depth);planes=Array.from({length:channels},(_,c)=>unpacked.subarray(c*plane,(c+1)*plane));}
 const ink=cmyk?new Float32Array(n*4):undefined;for(let i=3;i<data.length;i+=4)data[i]=depth===8?255:depth===16?65535:1;for(let c=0;c<channels;c++){const values=numeric(planes[c]!,depth);for(let i=0;i<n;i++){if(ink&&c<4)ink[i*4+c]=(1-values[i]!/(depth===8?255:65535))*100;else data[i*4+(ink?3:c)]=values[i]!;}}
 if(ink){const max=depth===8?255:65535;for(let i=0;i<n;i++){const a=data[i*4+3]!/max;if(a>0&&a<1)for(let c=0;c<4;c++)ink[i*4+c]=Math.max(0,Math.min(100,ink[i*4+c]!/a));}const b=cmykBitmap(w,h,ink,Array.from({length:n},(_,i)=>data[i*4+3]!/max*255),depth as 8|16);for(let i=0;i<data.length;i++)data[i]=b.data[i]!/255*max;psd.imageData={width:w,height:h,data,...{cmyk:ink}};return psd;}

 // PSD merged transparency is white-matted. Layer channels remain straight.
 if(channels===4)for(let i=0;i<data.length;i+=4){const max=depth===16?65535:1,a=data[i+3]!/max;if(a>0&&a<1)for(let c=0;c<3;c++)data[i+c]=(data[i+c]!/max-(1-a))/a*max;}
 psd.imageData={width:w,height:h,data};return psd;
}
export function writeHighPsd(psd:Psd,depth:8|16|32,cmyk=false):Uint8Array {
 const preview=(b:PixelData):PixelData=>({width:b.width,height:b.height,data:Uint8ClampedArray.from(b.data,v=>v)});
 const convert=(ls:Layer[]):Layer[]=>ls.map(l=>({...l,...(l.imageData?{imageData:preview(l.imageData)}:{}),...(l.children?{children:convert(l.children)}:{})}));
 const image=psd.imageData!;const low=preview(image);if(image.data.some((v,i)=>i%4===3&&v<255))low.data[3]=Math.min(low.data[3]!,254);
 const encoded=normalizeExportedLevels(writePsdUint8Array({...psd,bitsPerChannel:8,children:convert(psd.children??[]),imageData:low},{noBackground:true,compress:true})),sec=psdSections(encoded),view=new DataView(encoded.buffer,encoded.byteOffset,encoded.byteLength),flat:(Layer|undefined)[]=[];
 const flatten=(ls:Layer[])=>{for(const l of ls){if(l.children){flat.push(undefined);flatten(l.children);flat.push(l);}else flat.push(l);}};flatten(psd.children??[]);
 let p=sec.layers.data+4;const count=Math.abs(view.getInt16(p));if(count!==flat.length)throw Error('高位深 PSD 编码器记录数不符。');const head=encoded.slice(p,p+2);if(cmyk)new DataView(head.buffer).setInt16(0,-count);p+=2;const records:Uint8Array[]=[],planes:Uint8Array[]=[];
 const plane=(b:PixelData|undefined,c:number)=>{if(!b)return new Uint8Array(2);const bytes=new Uint8Array(2+b.width*b.height*depth/8),v=new DataView(bytes.buffer);for(let i=0;i<b.width*b.height;i++){const n=b.data[i*4+c]!;if(depth===8)bytes[2+i]=Math.round(Math.max(0,Math.min(255,n)));else if(depth===16)v.setUint16(2+i*2,Math.round(Math.max(0,Math.min(255,n))*257));else v.setFloat32(2+i*4,n/255);}return bytes;};
 for(let i=0;i<count;i++){const from=p,ch=view.getUint16(p+16),channelAt=p+18;p=channelAt+ch*6+12;const size=view.getUint32(p);p+=4+size;const original=encoded.slice(from,p),ov=new DataView(original.buffer),l=flat[i],ids=Array.from({length:ch},(_,c)=>ov.getInt16(18+c*6));if(cmyk&&l?.imageData)ids.splice(ids.indexOf(2)+1,0,3);const prefix=original.slice(0,18);new DataView(prefix.buffer).setUint16(16,ids.length);const entries=new Uint8Array(ids.length*6),ev=new DataView(entries.buffer);
 for(let c=0;c<ids.length;c++){const id=ids[c]!,b=id===-2?l?.mask?.imageData:id===-3?l?.realMask?.imageData:l?.imageData;let bytes:Uint8Array;if(cmyk&&b&&id>=0&&id<4){const ink=(b as unknown as Bitmap).cmyk;if(!ink)throw Error('缺少 CMYK 原生通道。');bytes=new Uint8Array(2+b.width*b.height*depth/8);const bv=new DataView(bytes.buffer);for(let j=0;j<b.width*b.height;j++){const n=1-ink[j*4+id]!/100;if(depth===8)bytes[2+j]=Math.round(n*255);else bv.setUint16(2+j*2,Math.round(n*65535));}}else bytes=plane(b,id< -1?0:id===-1?3:id);ev.setInt16(c*6,id);ev.setUint32(c*6+2,bytes.length);planes.push(bytes);}records.push(concatBytes([prefix,entries,original.subarray(18+ch*6)]));}

 const info=concatBytes([head,...records,...planes]),padded=concatBytes([info,new Uint8Array((4-info.length%4)%4)]),oldEnd=sec.layers.data+4+view.getUint32(sec.layers.data),globals=encoded.subarray(oldEnd,sec.layers.end),layerSection=section(depth===8?concatBytes([section(padded),globals]):concatBytes([u32(0),globals,tag(depth===16?'Lr16':'Lr32',padded),tag(depth===16?'Mt16':'Mt32',new Uint8Array())]));
 const header=encoded.slice(0,sec.layers.start);new DataView(header.buffer).setUint16(22,depth);if(cmyk){new DataView(header.buffer).setUint16(24,4);new DataView(header.buffer).setUint16(12,5);}const channels=cmyk?5:view.getUint16(12),n=image.width*image.height,composite=new Uint8Array(2+n*channels*depth/8),cv=new DataView(composite.buffer);
 for(let c=0;c<channels;c++)for(let i=0;i<n;i++){const a=image.data[i*4+3]!/255,value=cmyk?(c<4?(1-(image as unknown as Bitmap).cmyk![i*4+c]!/100*a)*255:image.data[i*4+3]!):c<3&&a>0&&a<1?image.data[i*4+c]!*a+255*(1-a):image.data[i*4+c]!;if(depth===8)composite[2+c*n+i]=Math.round(Math.max(0,Math.min(255,value)));else if(depth===16)cv.setUint16(2+(c*n+i)*2,Math.round(Math.max(0,Math.min(255,value))*257));else cv.setFloat32(2+(c*n+i)*4,value/255);}

 return concatBytes([header,layerSection,composite]);
}
