/** Official ICC reference CMM in an isolated worker; never accepts host paths or CLI arguments. */
export interface IccChainEntry { bytes:Uint8Array; intent:number; pcc?:Uint8Array; environment?:{name:string;value:number}[] }
export interface IccReferenceRequest {mode:'validate'|'transform';profiles:IccChainEntry[];input?:Uint8Array;encoding?:number;interpolation?:0|1}
export interface IccReferenceResult {engine:string;status:'valid'|'warnings'|'invalid'|'transformed';report:string;profileVersions:number[]}
export interface ReferenceModule { FS:{writeFile(path:string,data:Uint8Array):void};callMain(args:string[]):number }
export type ReferenceFactory=(options:{noInitialRun:boolean;print:(s:string)=>void;printErr:(s:string)=>void;locateFile:(s:string)=>string})=>Promise<ReferenceModule>;
export function referenceHeader(bytes:Uint8Array){if(!(bytes instanceof Uint8Array)||bytes.length<132||bytes.length>4*1024*1024)throw Error('ICC 配置应为 132 B–4 MiB。');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(v.getUint32(0)!==bytes.length||v.getUint32(36)!==0x61637370||![2,4,5].includes(bytes[8]!))throw Error('需要有效的 ICC v2/v4/iccMAX v5 头。');const n=v.getUint32(128);if(n>1024||132+n*12>bytes.length)throw Error('ICC 标签表无效。');for(let i=0;i<n;i++){const p=132+i*12,a=v.getUint32(p+4),b=v.getUint32(p+8);if(a<132+n*12||a+b>bytes.length||b<8)throw Error('ICC 标签超出边界。');}return bytes[8]!;}
export function admitReference(r:IccReferenceRequest){if(!['validate','transform'].includes(r.mode)||!Array.isArray(r.profiles)||!r.profiles.length||r.profiles.length>8||r.mode==='validate'&&r.profiles.length!==1)throw Error('配置链数量无效。');let bytes=0;for(const p of r.profiles){referenceHeader(p.bytes);bytes+=p.bytes.length;if(p.pcc){referenceHeader(p.pcc);bytes+=p.pcc.length;}if(!Number.isInteger(p.intent)||p.intent<0||p.intent>3101103)throw Error('ICC 转换意图无效。');if(p.environment&&(p.environment.length>32||p.environment.some(e=>! /^[A-Za-z0-9]{4}$/.test(e.name)||!Number.isFinite(e.value))))throw Error('ICC 环境签名或数值无效。');}if(bytes>32*1024*1024||r.input&&r.input.length>1024*1024)throw Error('ICC 参考任务超出预算。');if(r.mode==='transform'&&(!r.input?.length||!Number.isInteger(r.encoding??3)||(r.encoding??3)<0||(r.encoding??3)>6||![0,1].includes(r.interpolation??1)))throw Error('ICC 数据编码／插值无效。');}
export async function executeReference(r:IccReferenceRequest,factory:ReferenceFactory):Promise<IccReferenceResult>{admitReference(r);const lines:string[]=[];let size=0;const print=(s:string)=>{size+=s.length;if(size>8*1024*1024)throw Error('ICC 报告超出预算。');lines.push(s);};const m=await factory({noInitialRun:true,print,printErr:print,locateFile:s=>new URL('./'+s,import.meta.url).href});
 const args:string[]=r.mode==='validate'?['-v','/profile0.icc']:['/samples.txt',String(r.encoding??3)+':9:12',String(r.interpolation??1)];if(r.input)m.FS.writeFile('/samples.txt',r.input);
 r.profiles.forEach((p,i)=>{const path='/profile'+i+'.icc';m.FS.writeFile(path,p.bytes);if(r.mode==='transform'){for(const e of p.environment??[])args.push('-ENV:'+e.name,String(e.value));args.push(path,String(p.intent));if(p.pcc){const pcc='/pcc'+i+'.icc';m.FS.writeFile(pcc,p.pcc);args.push('-PCC',pcc);}}});const code=m.callMain(args),report=lines.join('\n');let status:IccReferenceResult['status'];
 if(r.mode==='validate'){status=code!==0||/non.?compliant|critical error|not valid|invalid profile/i.test(report)?'invalid':/Profile is valid for version/i.test(report)?'valid':'warnings';if(!report.includes('Validation Report'))throw Error('ICC 引擎未返回校验报告。');}
 else{if(code!==0||!report.includes(';Profiles applied')||!report.includes(';Source Data Format:')||!/^\s*(?:[-+]?(?:\d|\.\d)|\{\s*").*\t;\s*/m.test(report))throw Error('ICC 转换失败：'+report.slice(-2000));status='transformed';}
 return {engine:'ICC iccDEV 2.3.23',status,report,profileVersions:r.profiles.map(p=>referenceHeader(p.bytes))};}
export function referenceJob(request:IccReferenceRequest,signal:AbortSignal):Promise<IccReferenceResult>{admitReference(request);signal.throwIfAborted();return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./icc-reference-worker.js',import.meta.url),{type:'module'});const finish=()=>{clearTimeout(timer);signal.removeEventListener('abort',abort);worker.terminate();};const abort=()=>{finish();reject(signal.reason??Error('ICC 任务已取消。'));};const timer=setTimeout(()=>{finish();reject(Error('ICC 参考任务超过 60 秒。'));},60000);signal.addEventListener('abort',abort,{once:true});worker.onerror=()=>{finish();reject(Error('ICC 参考引擎加载失败。'));};worker.onmessage=e=>{finish();e.data.ok?resolve(e.data.value):reject(Error(e.data.error));};worker.postMessage(request);});}
