import { allLayers, type ImageLayer, type ImageState } from './document.js';
import { layerBounds, selectedRoots } from './dailyEditing.js';
import type { Point, Rect } from './pixelTools.js';
function targets(state:ImageState,excluded:readonly string[]){const l=state.layout,x:number[]=[],y:number[]=[];if(!l?.snap)return {x,y};for(const g of l.guides)(g.axis==='x'?x:y).push(g.position);if(l.canvas){x.push(0,state.width/2,state.width);y.push(0,state.height/2,state.height);}const visible=(layers:readonly ImageLayer[]):ImageLayer[]=>layers.flatMap(l=>l.visible?[l,...visible(l.children)]:[]);if(l.layers)for(const layer of visible(state.layers)){if(!layer.bitmap&&!allLayers(layer.children).some(c=>c.bitmap))continue;if(!layer.visible||excluded.includes(layer.id)||allLayers(layer.children).some(c=>excluded.includes(c.id)))continue;const b=layerBounds(state,layer);x.push(b.x,b.x+b.width/2,b.x+b.width);y.push(b.y,b.y+b.height/2,b.y+b.height);}return {x,y};}
function correction(values:readonly number[],dest:readonly number[],limit:number){let delta=0,best=limit+1e-8;for(const v of values)for(const d of dest)if(Math.abs(d-v)<best){delta=d-v;best=Math.abs(delta);}return delta;}
export function snapPoint(state:ImageState,p:Point,zoom=1):Point {if(!state.layout?.snap)return p;const t=targets(state,[]),limit=(state.layout?.tolerance??0)/Math.max(.05,zoom);return {x:Math.round(p.x+correction([p.x],t.x,limit)),y:Math.round(p.y+correction([p.y],t.y,limit))};}
export function snapMove(state:ImageState,ids:readonly string[],delta:Point,zoom=1):Point {
 if(!state.layout?.snap)return delta;const roots=selectedRoots(state,ids),exclude=roots.flatMap(l=>[l.id,...allLayers(l.children).map(c=>c.id)]),bounds=roots.filter(l=>l.bitmap||allLayers(l.children).some(c=>c.bitmap)).map(l=>layerBounds(state,l));if(!bounds.length)return delta;const b:Rect={x:Math.min(...bounds.map(b=>b.x)),y:Math.min(...bounds.map(b=>b.y)),width:0,height:0};b.width=Math.max(...bounds.map(b=>b.x+b.width))-b.x;b.height=Math.max(...bounds.map(b=>b.y+b.height))-b.y;const t=targets(state,exclude),limit=state.layout.tolerance/Math.max(.05,zoom);return {x:Math.round(delta.x+correction([b.x,b.x+b.width/2,b.x+b.width].map(x=>x+delta.x),t.x,limit)),y:Math.round(delta.y+correction([b.y,b.y+b.height/2,b.y+b.height].map(y=>y+delta.y),t.y,limit))};
}
