import { displayBitmap } from './pixelFormat.js';
import { findLayer, layerLocked, uid, type ImageDocument, type ImageLayer, type ImageState, type Bitmap } from './document.js';
import { BLEND_MODES, type LayerMask } from './layerFeatures.js';
import { FILTERS, type FilterKind } from './filters.js';
import { validateSmartFilters, validateBlendIf, primeFilterStack, type SmartFilter, type BlendIf } from './liveEffects.js';
import { validateMask } from './maskEffects.js';
import { maskFromSelection } from './maskTools.js';
import { replacePixel } from './pixelTools.js';
import { pixelJob } from './pixelJobs.js';
import type { EditingTools } from './editingTools.js';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const value=(id:string)=>$<HTMLInputElement>(id).value,number=(id:string)=>Number(value(id));
type Mode='filters'|'mask'|'blend';
export class LiveEffectsPanel {
 private session:{doc:ImageDocument;before:ImageState;layer:ImageLayer;draft:ImageLayer;mode:Mode}|undefined;
 private controller:AbortController|undefined;private timer:ReturnType<typeof setTimeout>|undefined;private generation=0;private selected=0;private invalid=false;
 constructor(private active:()=>ImageDocument|undefined,private editing:EditingTools){
  document.querySelector('.advanced-actions')!.insertAdjacentHTML('beforeend','<button data-action="smart-filters" data-needs-layer>智能滤镜</button><button data-action="mask-properties" data-needs-layer>蒙版属性</button><button data-action="blend-if" data-needs-layer>Blend If</button>');
  const options=(o:Record<string,string>)=>Object.entries(o).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');
  document.body.insertAdjacentHTML('beforeend',`<dialog id="live-dialog"><h2 id="live-title"></h2><canvas id="live-preview" width="480" height="220" aria-label="非破坏性效果预览"></canvas><label><input id="live-original" type="checkbox">对比原图</label>
  <section id="live-filters"><p class="muted">处理顺序从上到下。原始像素保留；滤镜蒙版控制整组效果。</p><select id="live-filter-list" size="4" aria-label="智能滤镜堆栈"></select><div class="dialog-actions"><button id="live-add">添加</button><button id="live-delete">删除</button><button id="live-up">上移</button><button id="live-down">下移</button></div><fieldset id="live-filter-settings"><label><input id="live-enabled" type="checkbox">启用滤镜</label><label>效果<select id="live-kind">${Object.entries(FILTERS).map(([k,c])=>`<option value="${k}">${c.name}</option>`).join('')}</select></label><label>参数<input id="live-amount" type="number"><span id="live-unit"></span></label><div id="live-usm"><label>半径 σ<input id="live-radius" type="number" min="0.1" max="32" step="0.1" value="2"></label><label>阈值<input id="live-threshold" type="number" min="0" max="255" value="0"></label></div><label>不透明度 %<input id="live-opacity" type="number" min="0" max="100" value="100"></label><label>混合模式<select id="live-blend">${options(BLEND_MODES)}</select></label></fieldset></section>
  <section id="live-mask"><label>目标<select id="live-mask-target"><option value="layer">图层蒙版</option><option value="filter">滤镜蒙版</option></select></label><p id="live-mask-info"></p><div class="dialog-actions"><button id="live-mask-create">从选区创建／替换</button><button id="live-mask-invert">反相</button><button id="live-mask-remove">移除</button></div><fieldset id="live-mask-settings"><label><input id="live-mask-enabled" type="checkbox">启用蒙版</label><label>密度 %<input id="live-density" type="range" min="0" max="100" value="100"><output id="live-density-value"></output></label><label>羽化 σ（px）<input id="live-feather" type="number" min="0" max="64" step="0.1" value="0"></label></fieldset><p class="muted">密度 0 完全显示；羽化保留原蒙版，可随时改回。没有选区时创建全白蒙版。</p><button id="live-mask-paint">应用并绘制蒙版</button></section>
  <section id="live-blend-if"><label><input id="live-blend-enabled" type="checkbox">启用 Blend If</label><label>通道<select id="live-channel"><option value="gray">灰色</option><option value="red">红</option><option value="green">绿</option><option value="blue">蓝</option></select></label>${['source','underlying'].map((kind,i)=>`<fieldset><legend>${i?'下方图层':'本图层'}</legend>${['黑场起点','黑场终点','白场起点','白场终点'].map((label,j)=>`<label>${label}<input type="range" min="0" max="255" step="1" id="live-${kind}-${j}"><output id="live-${kind}-${j}-value"></output></label>`).join('')}</fieldset>`).join('')}<p class="muted">四个端点保持递增；黑场与白场各两个端点之间平滑过渡。</p><button id="live-blend-reset">重置颜色带</button></section>
  <p id="live-status" role="status"></p><p id="live-error" role="alert" class="dialog-error"></p><div class="dialog-actions"><button data-close-dialog>取消</button><button id="live-apply" class="primary" disabled>应用</button></div></dialog>`);
  $('live-filter-list').onchange=()=>{this.selected=Number(value('live-filter-list'));this.fields();};
  $('live-add').onclick=()=>this.guard(()=>{const filters=this.filters();if(filters.length>=16)throw new Error('智能滤镜最多 16 个。');filters.push({id:uid(),enabled:true,settings:{kind:'gaussian',amount:2},opacity:1,blend:'normal'});this.selected=filters.length-1;this.setFilters(filters);});
  $('live-delete').onclick=()=>this.guard(()=>{const filters=this.filters();filters.splice(this.selected,1);this.selected=Math.max(0,this.selected-1);this.setFilters(filters);});
  for(const [id,delta] of [['live-up',-1],['live-down',1]] as const)$(id).onclick=()=>this.guard(()=>{const filters=this.filters(),next=this.selected+delta;if(next<0||next>=filters.length)return;[filters[this.selected],filters[next]]=[filters[next]!,filters[this.selected]!];this.selected=next;this.setFilters(filters);});
  $('live-kind').onchange=()=>{const c=FILTERS[value('live-kind') as FilterKind];$<HTMLInputElement>('live-amount').value=String(c.value);this.filterInputs();};
  for(const id of ['live-enabled','live-amount','live-radius','live-threshold','live-opacity','live-blend'])$(id).addEventListener('input',()=>this.filterInputs());
  $('live-mask-target').onchange=()=>this.maskFields();
  $('live-mask-create').onclick=()=>this.guard(()=>{const s=this.current();this.setMask(maskFromSelection(s.before,s.layer.id));});
  $('live-mask-invert').onclick=()=>this.guard(()=>{const mask=this.mask();if(mask)this.setMask({...mask,data:mask.data.map(v=>255-v),defaultColor:255-mask.defaultColor});});
  $('live-mask-remove').onclick=()=>this.guard(()=>this.setMask(undefined));
  for(const id of ['live-mask-enabled','live-density','live-feather'])$(id).oninput=()=>this.guard(()=>{const mask=this.mask();if(mask)this.setMask({...mask,disabled:!$<HTMLInputElement>('live-mask-enabled').checked,density:number('live-density')/100,feather:number('live-feather')},false);});
  $('live-blend-if').oninput=()=>this.guard(()=>{const rule:BlendIf={enabled:$<HTMLInputElement>('live-blend-enabled').checked,channel:value('live-channel') as BlendIf['channel'],source:[0,1,2,3].map(i=>number('live-source-'+i)) as unknown as BlendIf['source'],underlying:[0,1,2,3].map(i=>number('live-underlying-'+i)) as unknown as BlendIf['underlying']};this.blendLabels();validateBlendIf(rule);this.current().draft={...this.current().draft,blendIf:rule};this.schedule();});
  $('live-blend-reset').onclick=()=>this.guard(()=>{this.current().draft={...this.current().draft,blendIf:{enabled:true,channel:'gray',source:[0,0,255,255],underlying:[0,0,255,255]}};this.blendFields();this.schedule();});
  $('live-original').onchange=()=>{if(!this.invalid)this.schedule();};$('live-apply').onclick=()=>this.guard(()=>this.commit());$('live-mask-paint').onclick=()=>this.guard(()=>{const target=value('live-mask-target') as 'layer'|'filter';if(!this.mask())throw new Error('请先创建蒙版。');if($<HTMLButtonElement>('live-apply').disabled)throw new Error('请等待有效预览。');this.commit();this.editing.setMaskEditing(true,target);});
  $('live-dialog').addEventListener('close',()=>{if(!$<HTMLDialogElement>('live-dialog').open)this.stop();});
 }
 private current(){const s=this.session;if(!s||this.active()!==s.doc||s.doc.state!==s.before)throw new Error('文档已变化，请重新打开效果面板。');return s;}
 private guard(action:()=>void){try{action();this.invalid=false;$('live-error').textContent='';}catch(e){this.invalid=true;this.cancelJob();$<HTMLButtonElement>('live-apply').disabled=true;$('live-error').textContent=e instanceof Error?e.message:String(e);}}
 open(mode:Mode){this.stop();this.invalid=false;const doc=this.active(),layer=doc?.selected;if(!doc||!layer||layerLocked(doc.state.layers,layer.id))throw new Error('请选择未锁定的图层。');if(mode==='filters'&&layer.content?.type!=='smart')throw new Error('请先将像素图层转为智能对象。');this.editing.cancel();this.session={doc,before:doc.state,layer,draft:{...layer},mode};this.selected=0;
  $('live-title').textContent={filters:'智能滤镜',mask:'蒙版属性',blend:'混合颜色带 · Blend If'}[mode];$('live-filters').hidden=mode!=='filters';$('live-mask').hidden=mode==='blend';$('live-blend-if').hidden=mode!=='blend';$<HTMLSelectElement>('live-mask-target').value=mode==='filters'?'filter':'layer';$<HTMLSelectElement>('live-mask-target').disabled=mode==='filters';$<HTMLSelectElement>('live-mask-target').querySelector<HTMLOptionElement>('option[value=filter]')!.disabled=layer.content?.type!=='smart';$<HTMLInputElement>('live-original').checked=false;$('live-error').textContent='';this.fields();this.maskFields();this.blendFields();$<HTMLDialogElement>('live-dialog').showModal();$('live-dialog').scrollTop=0;this.schedule();
 }
 private filters(){return structuredClone(this.current().draft.smartFilters??[]) as SmartFilter[];}
 private setFilters(filters:SmartFilter[]){validateSmartFilters(filters);this.current().draft={...this.current().draft,smartFilters:filters};this.fields();this.schedule();}
 private fields(){const filters=this.filters();$<HTMLSelectElement>('live-filter-list').replaceChildren(...filters.map((f,i)=>new Option(`${i+1}. ${f.enabled?'':'[停用] '}${FILTERS[f.settings.kind].name}`,String(i),false,i===this.selected)));const f=filters[this.selected];$<HTMLFieldSetElement>('live-filter-settings').disabled=!f;$<HTMLButtonElement>('live-delete').disabled=!f;$<HTMLButtonElement>('live-up').disabled=!f||this.selected===0;$<HTMLButtonElement>('live-down').disabled=!f||this.selected===filters.length-1;$<HTMLButtonElement>('live-add').disabled=filters.length>=16;if(!f)return;
  $<HTMLInputElement>('live-enabled').checked=f.enabled;for(const [id,v] of Object.entries({kind:f.settings.kind,amount:f.settings.amount,radius:f.settings.radius??2,threshold:f.settings.threshold??0,opacity:f.opacity*100,blend:f.blend}))$<HTMLInputElement>('live-'+id).value=String(v);this.filterBounds();
 }
 private filterBounds(){const kind=value('live-kind') as FilterKind,c=FILTERS[kind],input=$<HTMLInputElement>('live-amount');input.min=String(c.min);input.max=String(c.max);input.step=kind==='gaussian'?'0.1':'1';$('live-unit').textContent=c.unit;$('live-usm').hidden=kind!=='usm';}
 private filterInputs(){this.guard(()=>{this.filterBounds();const filters=this.filters(),f=filters[this.selected];if(!f)return;const kind=value('live-kind') as FilterKind;filters[this.selected]={...f,enabled:$<HTMLInputElement>('live-enabled').checked,opacity:number('live-opacity')/100,blend:value('live-blend') as SmartFilter['blend'],settings:{kind,amount:number('live-amount'),...(kind==='usm'?{radius:number('live-radius'),threshold:number('live-threshold')}:{})}};validateSmartFilters(filters);this.current().draft={...this.current().draft,smartFilters:filters};const option=$<HTMLSelectElement>('live-filter-list').options[this.selected];if(option)option.textContent=`${this.selected+1}. ${filters[this.selected]!.enabled?'':'[停用] '}${FILTERS[kind].name}`;this.schedule();});}
 private key(){return value('live-mask-target')==='filter'?'filterMask':'mask';}
 private mask(){return this.current().draft[this.key()];}
 private setMask(mask:LayerMask|undefined,fields=true){if(mask)validateMask(mask);const s=this.current(),draft={...s.draft},key=this.key();delete draft[key];if(mask)draft[key]=mask;s.draft=draft;if(fields)this.maskFields();else $('live-density-value').textContent=value('live-density');this.schedule();}
 private maskFields(){const mask=this.mask();$('live-mask-info').textContent=mask?`${mask.width} × ${mask.height} · ${this.key()==='filterMask'?'滤镜蒙版':'图层蒙版'}`:'无蒙版';$<HTMLFieldSetElement>('live-mask-settings').disabled=!mask;for(const id of ['live-mask-invert','live-mask-remove','live-mask-paint'])$<HTMLButtonElement>(id).disabled=!mask;$<HTMLInputElement>('live-mask-enabled').checked=!mask?.disabled;$<HTMLInputElement>('live-density').value=String((mask?.density??1)*100);$('live-density-value').textContent=value('live-density');$<HTMLInputElement>('live-feather').value=String(mask?.feather??0);}
 private blendFields(){const b=this.current().draft.blendIf??{enabled:true,channel:'gray',source:[0,0,255,255],underlying:[0,0,255,255]};$<HTMLInputElement>('live-blend-enabled').checked=b.enabled;$<HTMLSelectElement>('live-channel').value=b.channel;for(const kind of ['source','underlying'] as const)for(let i=0;i<4;i++)$<HTMLInputElement>(`live-${kind}-${i}`).value=String(b[kind][i]);this.blendLabels();}
 private blendLabels(){for(const k of ['source','underlying'])for(let i=0;i<4;i++)$(`live-${k}-${i}-value`).textContent=value(`live-${k}-${i}`);}
 private cancelJob(){this.generation++;clearTimeout(this.timer);this.controller?.abort();this.controller=undefined;}
 private validateInputs(){for(const input of $('live-dialog').querySelectorAll<HTMLInputElement>('input[type=number]'))if(input.getClientRects().length&&!input.matches(':disabled')&&(!input.value.trim()||!Number.isFinite(Number(input.value))||input.validity.rangeUnderflow||input.validity.rangeOverflow))throw new Error('请检查数字参数的范围。');if(this.current().mode==='blend')validateBlendIf({enabled:true,channel:value('live-channel') as BlendIf['channel'],source:[0,1,2,3].map(i=>number('live-source-'+i)) as unknown as BlendIf['source'],underlying:[0,1,2,3].map(i=>number('live-underlying-'+i)) as unknown as BlendIf['underlying']});}
 private schedule(){this.validateInputs();this.cancelJob();$<HTMLButtonElement>('live-apply').disabled=true;$('live-status').textContent='正在生成预览…';this.timer=setTimeout(()=>void this.preview(),100);}
 private async preview(){const generation=this.generation,controller=this.controller=new AbortController();try{const s=this.current(),original=$<HTMLInputElement>('live-original').checked,state=original?s.before:{...s.before,layers:replacePixel(s.before.layers,s.layer.id,s.draft)},result=await pixelJob<{image:Bitmap;stack:Bitmap|null}>({kind:'effects',state,id:s.layer.id},controller.signal);if(generation!==this.generation)return;this.current();if(result.stack&&s.layer.bitmap&&s.draft.smartFilters&&!original)primeFilterStack(s.layer.bitmap,s.draft.smartFilters,result.stack);
   const canvas=$<HTMLCanvasElement>('live-preview'),ctx=canvas.getContext('2d')!,temp=document.createElement('canvas');temp.width=result.image.width;temp.height=result.image.height;temp.getContext('2d')!.putImageData(new ImageData(displayBitmap(result.image).data as Uint8ClampedArray<ArrayBuffer>,temp.width,temp.height),0,0);const scale=Math.min(canvas.width/temp.width,canvas.height/temp.height);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(temp,(canvas.width-temp.width*scale)/2,(canvas.height-temp.height*scale)/2,temp.width*scale,temp.height*scale);temp.width=temp.height=1;$('live-status').textContent='预览已更新 · 应用后可撤销';$<HTMLButtonElement>('live-apply').disabled=false;
  }catch(e){if(!controller.signal.aborted&&generation===this.generation){$('live-error').textContent=e instanceof Error?e.message:String(e);$('live-status').textContent='预览失败';}}}
 private commit(){this.validateInputs();const s=this.current();if($<HTMLButtonElement>('live-apply').disabled)throw new Error('请等待有效预览。');s.doc.commitLayers('非破坏性效果',replacePixel(s.before.layers,s.layer.id,s.draft),[s.layer.id],s.doc.selectedIds,s.before.revision);$<HTMLDialogElement>('live-dialog').close();this.stop();}
 private stop(){this.cancelJob();this.session=undefined;$<HTMLCanvasElement>('live-preview')?.getContext('2d')?.clearRect(0,0,480,220);}
 dispose(){this.stop();}
}
