import { diskPager, hydrateArchive, archiveBytes, validateDiskBlob, type DiskBlob } from './diskPager.js';
import { deflate, Inflate } from 'pako';
import type { Bitmap, ImageLayer, ImageState } from './document.js';
import type { Layer } from 'ag-psd';

export const PAGE_SIZE=256, PAGE_CACHE_BYTES=16*1024*1024, MATERIALIZED_CACHE_BYTES=64*1024*1024;
export type PixelPages = {kind:'disk';tiles:DiskBlob[];inks?:DiskBlob[];pngSource?:DiskBlob} | {kind:'overlay';base:PixelPages;tiles:{index:number;bytes:Uint8Array}[]} | {kind:'psd-rgb8';channels:NonNullable<Layer['rawData']>['channels']} | {kind:'rgba8';tiles:Uint8Array[]} | {kind:'png-rgba8';bytes:Uint8Array};
type Samples=Uint8ClampedArray|Float32Array;
interface Entry {value:Samples;bytes:number}
class Cache {
 private entries=new Map<object,Entry>();bytes=0;decodes=0;
 constructor(readonly budget:number){}
 get(key:object,decode:()=>Samples){const old=this.entries.get(key);if(old){this.entries.delete(key);this.entries.set(key,old);return old.value;}const value=decode();this.decodes++;while(this.bytes+value.byteLength>this.budget&&this.entries.size){const first=this.entries.keys().next().value!;this.bytes-=this.entries.get(first)!.bytes;this.entries.delete(first);}if(value.byteLength<=this.budget){this.entries.set(key,{value,bytes:value.byteLength});this.bytes+=value.byteLength;}return value;}
 clear(){this.entries.clear();this.bytes=0;this.decodes=0;}
}
const tiles=new Cache(PAGE_CACHE_BYTES),dense=new Cache(MATERIALIZED_CACHE_BYTES),keys=new WeakMap<object,object[]>(),rows=new WeakMap<object,Uint32Array>();
const inkKeys=new WeakMap<object,object>();
const valid=new WeakSet<object>(),pngChecked=new WeakSet<object>();
const crcTable=Uint32Array.from({length:256},(_,n)=>{for(let i=0;i<8;i++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]!^(crc>>>8);return (crc^0xffffffff)>>>0;}
export const pagedPixelStats=()=>({tileBytes:tiles.bytes,tileBudget:tiles.budget,tileDecodes:tiles.decodes,materializedBytes:dense.bytes,materializedBudget:dense.budget,materializations:dense.decodes});
export function clearPagedPixelCache(){tiles.clear();dense.clear();}
export function isPaged(b:Bitmap|undefined|null):boolean{return !!b?.pages&&!Object.hasOwn(Object.getOwnPropertyDescriptor(b,'data')??{},'value');}
export function inflateBounded(bytes:Uint8Array,length:number){const out=new Uint8Array(length);let offset=0;const z=new Inflate({chunkSize:65536});z.onData=part=>{if(offset+part.length>length)throw Error('像素分块解码超出声明长度。');out.set(part,offset);offset+=part.length;};if(!z.push(bytes,true)||z.err||offset!==length)throw Error('像素分块压缩数据损坏。');return out;}
export function validatePages(b:Bitmap){
 const p=b.pages;if(!p)throw Error('像素分块索引缺失。');if(valid.has(b))return;
 if((p.kind!=='disk'&&((b.depth??8)!==8||b.cmyk))||b.width<1||b.height<1||b.width>8192||b.height>8192||b.width*b.height>16777216||!Number.isInteger(b.width)||!Number.isInteger(b.height))throw Error('分块像素尺寸或格式无效。');
 if(p.kind==='disk'){if(![8,16,32].includes(b.depth??8)||p.tiles.length!==Math.ceil(b.width/PAGE_SIZE)*Math.ceil(b.height/PAGE_SIZE)||p.inks&&p.inks.length!==p.tiles.length)throw Error('磁盘像素目录无效。');for(const blob of [...p.tiles,...(p.inks??[]),...(p.pngSource?[p.pngSource]:[])])validateDiskBlob(blob);}
 else if(p.kind==='overlay'){if(p.base.kind==='overlay'||!Array.isArray(p.tiles)||p.tiles.length>Math.ceil(b.width/PAGE_SIZE)*Math.ceil(b.height/PAGE_SIZE)||new Set(p.tiles.map(t=>t.index)).size!==p.tiles.length||p.tiles.some(t=>!Number.isInteger(t.index)||t.index<0||t.index>=Math.ceil(b.width/PAGE_SIZE)*Math.ceil(b.height/PAGE_SIZE)||!(t.bytes instanceof Uint8Array)||!t.bytes.length||t.bytes.length>PAGE_SIZE*PAGE_SIZE*4+1024))throw Error('像素覆盖块无效。');validatePages({width:b.width,height:b.height,pages:p.base} as Bitmap);}
 else if(p.kind==='rgba8'){if(!Array.isArray(p.tiles)||p.tiles.length!==Math.ceil(b.width/PAGE_SIZE)*Math.ceil(b.height/PAGE_SIZE)||p.tiles.some(t=>!(t instanceof Uint8Array)||!t.length||t.length>PAGE_SIZE*PAGE_SIZE*4+1024))throw Error('像素分块目录无效。');}
 else if(p.kind==='psd-rgb8'){
  if(!Array.isArray(p.channels)||p.channels.length>4||new Set(p.channels.map(c=>c.id)).size!==p.channels.length||p.channels.some(c=>![-1,0,1,2].includes(c.id)||![0,1,2,3].includes(c.compression)))throw Error('按需 PSD 仅支持 RGB8 原始／RLE／ZIP 通道。');
  for(const c of p.channels){if(!c.data)continue;if(!(c.data instanceof Uint8Array))throw Error('PSD 通道索引无效。');if(c.compression===0){if(c.data.length!==b.width*b.height)throw Error('PSD 原始通道长度无效。');}else if(c.compression===1)rowOffsets(c.data,b.height);else if(!c.data.length)throw Error('PSD ZIP 通道为空。');}
 }else if(p.kind==='png-rgba8'){const info=pngInfo(p.bytes);if(info.width!==b.width||info.height!==b.height)throw Error('PNG 智能源尺寸不符。');}
 else throw Error('未知像素分块格式。');valid.add(b);
}
function rowOffsets(data:Uint8Array,height:number){let offsets=rows.get(data);if(offsets){if(offsets.length!==height+1)throw Error('PSD 通道行数不符。');return offsets;}if(data.length<height*2)throw Error('PSD 行表截断。');const v=new DataView(data.buffer,data.byteOffset,data.byteLength);offsets=new Uint32Array(height+1);offsets[0]=height*2;for(let y=0;y<height;y++)offsets[y+1]=offsets[y]!+v.getUint16(y*2);if(offsets[height]!==data.length)throw Error('PSD 通道行表长度不符。');rows.set(data,offsets);return offsets;}
function psdTile(b:Bitmap,p:Extract<PixelPages,{kind:'psd-rgb8'}>,x:number,y:number,w:number,h:number){const out=new Uint8ClampedArray(w*h*4);for(let i=3;i<out.length;i+=4)out[i]=255;
 for(const channel of p.channels){if(!channel.data)continue;const c=channel.id===-1?3:channel.id,bytes=channel.data;if(channel.compression===0){for(let row=0;row<h;row++)for(let col=0;col<w;col++)out[(row*w+col)*4+c]=bytes[(y+row)*b.width+x+col]!;continue;}
 if(channel.compression===2||channel.compression===3){const raw=dense.get(channel,()=>{const decoded=new Uint8ClampedArray(inflateBounded(bytes,b.width*b.height).buffer);if(channel.compression===3)for(let yy=0;yy<b.height;yy++)for(let xx=1;xx<b.width;xx++){const i=yy*b.width+xx;decoded[i]=(decoded[i]!+decoded[i-1]!)&255;}return decoded;});for(let row=0;row<h;row++)for(let col=0;col<w;col++)out[(row*w+col)*4+c]=raw[(y+row)*b.width+x+col]!;continue;}
 const offsets=rowOffsets(bytes,b.height);for(let row=0;row<h;row++){let at=offsets[y+row]!,end=offsets[y+row+1]!,col=0;while(at<end){const control=bytes[at++]!;if(control===128)continue;const count=control<128?control+1:257-control;if(col+count>b.width||at+(control<128?count:1)>end)throw Error('PSD RLE 行无效。');for(let k=Math.max(0,x-col);k<Math.min(count,x+w-col);k++)out[(row*w+col+k-x)*4+c]=bytes[at+(control<128?k:0)]!;at+=control<128?count:1;col+=count;}if(col!==b.width)throw Error('PSD RLE 行像素不完整。');}}
 return out;}
function tile(b:Bitmap,tx:number,ty:number):Samples{const p=b.pages!;if(p.kind==='overlay'){const index=ty*Math.ceil(b.width/PAGE_SIZE)+tx,entry=p.tiles.find(t=>t.index===index);if(!entry)return tile({width:b.width,height:b.height,pages:p.base} as Bitmap,tx,ty);return tiles.get(entry.bytes,()=>new Uint8ClampedArray(inflateBounded(entry.bytes,Math.min(PAGE_SIZE,b.width-tx*PAGE_SIZE)*Math.min(PAGE_SIZE,b.height-ty*PAGE_SIZE)*4).buffer));}let ids=keys.get(p);if(!ids){ids=[];keys.set(p,ids);}const index=ty*Math.ceil(b.width/PAGE_SIZE)+tx,key=ids[index]??(ids[index]={});return tiles.get(key,()=>{const x=tx*PAGE_SIZE,y=ty*PAGE_SIZE,w=Math.min(PAGE_SIZE,b.width-x),h=Math.min(PAGE_SIZE,b.height-y);if(p.kind==='disk'){const raw=inflateBounded(diskPager.syncBlob(p.tiles[index]!),w*h*4*((b.depth??8)===8?1:4));return decodeSamples(raw,b.depth??8); }if(p.kind==='rgba8')return new Uint8ClampedArray(inflateBounded(p.tiles[index]!,w*h*4).buffer);if(p.kind==='psd-rgb8')return psdTile(b,p,x,y,w,h);const full=dense.get(p,()=>decodePng(p.bytes)),out=new Uint8ClampedArray(w*h*4);for(let row=0;row<h;row++)out.set(full.subarray(((y+row)*b.width+x)*4,((y+row)*b.width+x+w)*4),row*w*4);return out;});}
export function bitmapRegion(b:Bitmap,x:number,y:number,width:number,height:number):Bitmap {
 const out:Samples=(b.depth??8)===8?new Uint8ClampedArray(width*height*4):new Float32Array(width*height*4);if(!isPaged(b)){const data=b.data;for(let row=0;row<height;row++)out.set(data.subarray(((y+row)*b.width+x)*4,((y+row)*b.width+x+width)*4),row*width*4);return {width,height,data:out,...(b.depth?{depth:b.depth}:{})};}
 for(let ty=Math.floor(y/PAGE_SIZE);ty<=Math.floor((y+height-1)/PAGE_SIZE);ty++)for(let tx=Math.floor(x/PAGE_SIZE);tx<=Math.floor((x+width-1)/PAGE_SIZE);tx++){const data=tile(b,tx,ty),left=tx*PAGE_SIZE,top=ty*PAGE_SIZE,tw=Math.min(PAGE_SIZE,b.width-left),x0=Math.max(x,left),x1=Math.min(x+width,left+tw);for(let row=Math.max(y,top);row<Math.min(y+height,top+PAGE_SIZE);row++)out.set(data.subarray(((row-top)*tw+x0-left)*4,((row-top)*tw+x1-left)*4),((row-y)*width+x0-x)*4);}
 return {width,height,data:out,...(b.depth?{depth:b.depth}:{}),...(b.pages?.kind==='disk'&&b.pages.inks?{cmyk:inkRegion(b,x,y,width,height)}:{})};
}
export function hydrateBitmap(b:Bitmap):Bitmap {if(b.pages?.kind==='disk'&&b.pages.inks&&!Object.hasOwn(b,'cmyk'))Object.defineProperty(b,'cmyk',{enumerable:false,configurable:true,get:()=>{let key=inkKeys.get(b.pages!);if(!key){key={};inkKeys.set(b.pages!,key);}return dense.get(key,()=>inkRegion(b,0,0,b.width,b.height));}});if(!b.pages||Object.hasOwn(Object.getOwnPropertyDescriptor(b,'data')??{},'value'))return b;validatePages(b);if(!Object.getOwnPropertyDescriptor(b,'data'))Object.defineProperty(b,'data',{configurable:true,enumerable:false,get:()=>dense.get(b.pages!,()=>b.pages!.kind==='png-rgba8'?decodePng(b.pages!.bytes):bitmapRegion(b,0,0,b.width,b.height).data)});return b;}
export function pagedBitmap(width:number,height:number,pages:PixelPages):Bitmap{return hydrateBitmap({width,height,pages} as Bitmap);}
export function packBitmap(b:Bitmap,previous?:Bitmap|null,bounds?:{x:number;y:number;width:number;height:number}):Bitmap {if(isPaged(b)||(b.depth??8)!==8||b.cmyk)return hydrateBitmap(b);if(previous&&isPaged(previous)&&bounds&&b.width===previous.width&&b.height===previous.height){const old=previous.pages!,overrides=new Map(old.kind==='overlay'?old.tiles.map(t=>[t.index,t.bytes] as const):[]),base=old.kind==='overlay'?old.base:old;const data=b.data;for(let ty=Math.floor(bounds.y/PAGE_SIZE);ty<=Math.floor((bounds.y+bounds.height-1)/PAGE_SIZE);ty++)for(let tx=Math.floor(bounds.x/PAGE_SIZE);tx<=Math.floor((bounds.x+bounds.width-1)/PAGE_SIZE);tx++){const x=tx*PAGE_SIZE,y=ty*PAGE_SIZE,w=Math.min(PAGE_SIZE,b.width-x),h=Math.min(PAGE_SIZE,b.height-y);if(x<0||y<0||w<=0||h<=0)continue;const part=new Uint8Array(w*h*4);for(let row=0;row<h;row++)part.set(data.subarray(((y+row)*b.width+x)*4,((y+row)*b.width+x+w)*4),row*w*4);overrides.set(ty*Math.ceil(b.width/PAGE_SIZE)+tx,deflate(part));}return pagedBitmap(b.width,b.height,{kind:'overlay',base,tiles:[...overrides].map(([index,bytes])=>({index,bytes}))});}const packed:Uint8Array[]=[],data=b.data;for(let y=0;y<b.height;y+=PAGE_SIZE)for(let x=0;x<b.width;x+=PAGE_SIZE){const w=Math.min(PAGE_SIZE,b.width-x),h=Math.min(PAGE_SIZE,b.height-y),part=new Uint8Array(w*h*4);for(let row=0;row<h;row++)part.set(data.subarray(((y+row)*b.width+x)*4,((y+row)*b.width+x+w)*4),row*w*4);packed.push(deflate(part));}return pagedBitmap(b.width,b.height,{kind:'rgba8',tiles:packed});}
export function hydratePixels<T>(value:T):T {const seen=new Set<object>();const visit=(v:unknown)=>{if(!v||typeof v!=='object'||seen.has(v)||ArrayBuffer.isView(v)||v instanceof ArrayBuffer)return;seen.add(v);if('psdArchiveStore'in v||'psdArchive'in v)hydrateArchive(v as ImageState);if('pages'in v&&'width'in v&&'height'in v){hydrateBitmap(v as Bitmap);return;}for(const child of Object.values(v))visit(child);};visit(value);return value;}
export function pagedState(state:ImageState):boolean{return !!state.paging?.enabled||!!archiveBytes(state)||state.layers.some(function has(l):boolean{return !!l.bitmap?.pages||l.content?.type==='smart'&&!!l.content.source.pages||l.children.some(has);});}
export function packLayers(layers:readonly ImageLayer[],previous:readonly ImageLayer[]=[],pixelId?:string,bounds?:{x:number;y:number;width:number;height:number}):readonly ImageLayer[]{return layers.map(l=>{const old=previous.find(p=>p.id===l.id);return {...l,bitmap:l.bitmap?packBitmap(l.bitmap,old?.bitmap,l.id===pixelId?bounds:undefined):null,...(l.content?.type==='smart'?{content:{...l.content,source:packBitmap(l.content.source)}}:{}),children:packLayers(l.children,old?.children,pixelId,bounds)};});}
export function pixelStorageBytes(b:Bitmap){return !isPaged(b)?b.data.byteLength+(b.cmyk?.byteLength??0):pageBuffers(b).reduce((s,p)=>s+p.byteLength,0);}


function pngInfo(bytes:Uint8Array){if(!(bytes instanceof Uint8Array)||bytes.length<33||[137,80,78,71,13,10,26,10].some((n,i)=>bytes[i]!==n))throw Error('PNG 智能源签名无效。');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),width=v.getUint32(16),height=v.getUint32(20);if(!width||!height||width>8192||height>8192||width*height>16777216||bytes[24]!==8||![2,6].includes(bytes[25]!)||bytes[26]||bytes[27]||bytes[28])throw Error('PNG 智能源仅支持非交错 RGB/RGBA 8 位。');if(!pngChecked.has(bytes)){let ended=false;for(let p=8;p+12<=bytes.length;){const n=v.getUint32(p);if(p+12+n>bytes.length||crc32(bytes.subarray(p+4,p+8+n))!==v.getUint32(p+8+n))throw Error('PNG 数据块校验失败。');if(v.getUint32(p+4)===0x49454e44){ended=true;break;}p+=12+n;}if(!ended)throw Error('PNG 结束块缺失。');pngChecked.add(bytes);}return {width,height,channels:bytes[25]===6?4:3};}
export function pngBitmap(bytes:Uint8Array){const {width,height}=pngInfo(bytes);return pagedBitmap(width,height,{kind:'png-rgba8',bytes});}
function decodePng(bytes:Uint8Array){const {width,height,channels}=pngInfo(bytes),v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),parts:Uint8Array[]=[];let end=false;for(let p=8;p+12<=bytes.length;){const n=v.getUint32(p);if(p+12+n>bytes.length)throw Error('PNG 数据截断。');const type=v.getUint32(p+4);if(type===0x49444154)parts.push(bytes.subarray(p+8,p+8+n));if(type===0x49454e44){end=true;break;}p+=12+n;}if(!end||!parts.length)throw Error('PNG 缺少图像数据。');const compressed=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let offset=0;for(const p of parts){compressed.set(p,offset);offset+=p.length;}const stride=width*channels,raw=inflateBounded(compressed,(stride+1)*height),out=new Uint8ClampedArray(width*height*4),previous=new Uint8Array(stride);for(let y=0;y<height;y++){const filter=raw[y*(stride+1)]!,row=raw.subarray(y*(stride+1)+1,(y+1)*(stride+1));if(filter>4)throw Error('PNG 滤波无效。');for(let i=0;i<stride;i++){const a=i>=channels?row[i-channels]!:0,b=previous[i]!,c=i>=channels?previous[i-channels]!:0,p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);row[i]=(row[i]!+(filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):filter===4?pa<=pb&&pa<=pc?a:pb<=pc?b:c:0))&255;}for(let x=0;x<width;x++){const i=(y*width+x)*4;out[i]=row[x*channels]!;out[i+1]=row[x*channels+1]!;out[i+2]=row[x*channels+2]!;out[i+3]=channels===4?row[x*channels+3]!:255;}previous.set(row);}return out;}

export function pageBuffers(b:Bitmap):Uint8Array[]{const p=b.pages!;return p.kind==='overlay'?[...pageBuffers({width:b.width,height:b.height,pages:p.base} as Bitmap),...p.tiles.map(t=>t.bytes)]:p.kind==='disk'?[]:p.kind==='rgba8'?p.tiles:p.kind==='png-rgba8'?[p.bytes]:p.channels.flatMap(c=>c.data?[c.data]:[]);}

function decodeSamples(raw:Uint8Array,depth:number):Samples {if(depth===8)return new Uint8ClampedArray(raw.buffer,raw.byteOffset,raw.byteLength);const v=new DataView(raw.buffer,raw.byteOffset,raw.byteLength);return Float32Array.from({length:raw.length/4},(_,i)=>{const n=v.getFloat32(i*4,true);if(!Number.isFinite(n)||Math.abs(n)>255*65504||(i%4===3||depth===16)&&(n<0||n>255))throw Error('磁盘浮点像素无效。');return n;});}
function encodeSamples(data:Samples){if(data instanceof Uint8ClampedArray)return new Uint8Array(data.buffer,data.byteOffset,data.byteLength);const bytes=new Uint8Array(data.length*4),view=new DataView(bytes.buffer);for(let i=0;i<data.length;i++)view.setFloat32(i*4,data[i]!,true);return bytes;}
/** Write each tile durably before atomically replacing this immutable bitmap's backing. */
export async function spillBitmap(bitmap:Bitmap,signal?:AbortSignal):Promise<void>{
 if(bitmap.pages?.kind==='disk')return;
 if(Object.isFrozen(bitmap)&&!bitmap.pages)throw Error('此位图需要先创建可换页存储。');
 const backing=bitmap.pages;
 if(backing?.kind==='overlay'&&backing.base.kind==='disk'){
  const refs=[...backing.base.tiles];for(const patch of backing.tiles)refs[patch.index]=await diskPager.write(patch.bytes,signal);signal?.throwIfAborted();
  const target=backing as unknown as Record<string,unknown>;for(const key of Object.keys(target))delete target[key];Object.assign(target,{kind:'disk',tiles:refs});clearPagedPixelCache();return;
 }
 if(backing?.kind==='rgba8'){
  const refs:DiskBlob[]=[];for(const bytes of backing.tiles)refs.push(await diskPager.write(bytes,signal));signal?.throwIfAborted();const target=backing as unknown as Record<string,unknown>;for(const key of Object.keys(target))delete target[key];Object.assign(target,{kind:'disk',tiles:refs});clearPagedPixelCache();return;
 }
 const pages:DiskBlob[]=[],inks:DiskBlob[]=[];
 for(let y=0;y<bitmap.height;y+=PAGE_SIZE)for(let x=0;x<bitmap.width;x+=PAGE_SIZE){signal?.throwIfAborted();const w=Math.min(PAGE_SIZE,bitmap.width-x),h=Math.min(PAGE_SIZE,bitmap.height-y),part=bitmapRegion(bitmap,x,y,w,h);pages.push(await diskPager.write(deflate(encodeSamples(part.data)),signal));if(bitmap.cmyk){const part=new Float32Array(w*h*4);for(let row=0;row<h;row++)part.set(bitmap.cmyk.subarray(((y+row)*bitmap.width+x)*4,((y+row)*bitmap.width+x+w)*4),row*w*4);inks.push(await diskPager.write(deflate(encodeSamples(part)),signal));}}
 const pngSource=backing?.kind==='png-rgba8'?await diskPager.write(backing.bytes,signal):undefined;signal?.throwIfAborted();const next:PixelPages={kind:'disk',tiles:pages,...(pngSource?{pngSource}:{}),...(inks.length?{inks}:{})};
 if(bitmap.pages){const target=bitmap.pages as unknown as Record<string,unknown>;for(const key of Object.keys(target))delete target[key];Object.assign(target,next);}else Object.defineProperty(bitmap,'pages',{enumerable:true,configurable:true,value:next});
 if(Object.getOwnPropertyDescriptor(bitmap,'data')?.configurable)delete (bitmap as unknown as Record<string,unknown>).data;
 if(inks.length&&Object.getOwnPropertyDescriptor(bitmap,'cmyk')?.configurable)delete (bitmap as unknown as Record<string,unknown>).cmyk;
 valid.delete(bitmap);clearPagedPixelCache();hydrateBitmap(bitmap);
}

function inkRegion(b:Bitmap,x:number,y:number,width:number,height:number):Float32Array {
 const p=b.pages;if(p?.kind!=='disk'||!p.inks)throw Error('磁盘分色目录缺失。');const out=new Float32Array(width*height*4),columns=Math.ceil(b.width/PAGE_SIZE);
 for(let ty=Math.floor(y/PAGE_SIZE);ty<=Math.floor((y+height-1)/PAGE_SIZE);ty++)for(let tx=Math.floor(x/PAGE_SIZE);tx<=Math.floor((x+width-1)/PAGE_SIZE);tx++){const tw=Math.min(PAGE_SIZE,b.width-tx*PAGE_SIZE),th=Math.min(PAGE_SIZE,b.height-ty*PAGE_SIZE),blob=p.inks[ty*columns+tx]!,data=tiles.get(blob,()=>decodeSamples(inflateBounded(diskPager.syncBlob(blob),tw*th*16),16)),left=tx*PAGE_SIZE,top=ty*PAGE_SIZE,x0=Math.max(x,left),x1=Math.min(x+width,left+tw);for(let row=Math.max(y,top);row<Math.min(y+height,top+th);row++)out.set(data.subarray(((row-top)*tw+x0-left)*4,((row-top)*tw+x1-left)*4),((row-y)*width+x0-x)*4);}
 return out;
}
export function hasDiskPixels(value:unknown):boolean {if(!value||typeof value!=='object'||ArrayBuffer.isView(value))return false;if('paging'in value&&(value as ImageState).paging?.enabled||'kind'in value&&value.kind==='disk'||'psdArchiveStore'in value&&(value as ImageState).psdArchiveStore?.disk)return true;return Object.values(value).some(hasDiskPixels);}
