import { isControlFocused } from './uiFocus.js';
import { makeLayer, findLayer, layerLocked, type ImageDocument } from './document.js';
import { type PathContent, type PathNode, validateContent } from './layerFeatures.js';
import { rasterContent } from './contentRaster.js';
import { replacePixel, parentOffset, type Point } from './pixelTools.js';
import type { EditingTools } from './editingTools.js';
import type { CanvasView } from './canvasView.js';
export class PathEditor {
 private draft:{doc:ImageDocument;revision:number;id:string|null;nodes:PathNode[];closed:boolean}|undefined;
 private drag:{pointer:number;index:number;handle:'anchor'|'in'|'out'|'new'}|undefined;
 private svg=document.createElementNS('http://www.w3.org/2000/svg','svg');private abort=new AbortController();
 constructor(private active:()=>ImageDocument|undefined,private view:CanvasView,private editing:EditingTools,private notify:(s:string,error?:boolean)=>void){
  this.svg.id='path-overlay';this.svg.style.pointerEvents='none';this.svg.style.display='none';view.artboard.append(this.svg);const signal=this.abort.signal;
  const guard=(f:()=>void)=>{try{f();}catch(e){notify(String(e),true);}};
  view.viewport.addEventListener('pointerdown',e=>guard(()=>{if(editing.tool!=='path'||e.button||view.canPan(e))return;if(!this.draft)this.start();const d=this.draft!,p=view.point(e);if(p.x<0||p.y<0||p.x>d.doc.state.width||p.y>d.doc.state.height)return;const distance=8/this.viewScale();let index=-1,handle:'anchor'|'in'|'out'|'new'='new';for(let i=0;i<d.nodes.length;i++){const n=d.nodes[i]!;for(const [h,x,y] of [['anchor',n.x,n.y],['in',n.inX,n.inY],['out',n.outX,n.outY]] as const)if(Math.hypot(p.x-x,p.y-y)<distance){index=i;handle=h;break;}if(index>=0)break;}
   if(index<0){if(d.nodes.length>=256)throw new Error('路径最多 256 个锚点。');d.nodes.push({x:p.x,y:p.y,inX:p.x,inY:p.y,outX:p.x,outY:p.y});index=d.nodes.length-1;}this.drag={pointer:e.pointerId,index,handle};view.viewport.setPointerCapture(e.pointerId);e.preventDefault();this.draw();}),{signal});
  view.viewport.addEventListener('pointermove',e=>guard(()=>this.move(e)),{signal});view.viewport.addEventListener('pointerup',e=>guard(()=>{if(this.drag?.pointer!==e.pointerId)return;this.move(e);this.drag=undefined;if(view.viewport.hasPointerCapture(e.pointerId))view.viewport.releasePointerCapture(e.pointerId);}),{signal});
  view.viewport.addEventListener('pointercancel',()=>this.cancel(),{signal});view.viewport.addEventListener('image-tool-change',()=>{if(editing.tool!=='path')this.cancel();},{signal});
  document.addEventListener('keydown',e=>{if(!this.draft||document.querySelector('dialog[open]')||isControlFocused())return;if(e.key==='Enter'||e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();guard(()=>e.key==='Enter'?this.apply():this.cancel());}else if(e.key==='Backspace'){e.preventDefault();e.stopImmediatePropagation();this.draft.nodes.pop();this.draw();}},{signal,capture:true});window.addEventListener('blur',()=>this.cancel(),{signal});
 }
 get busy(){return !!this.draft;}
 private viewScale(){return this.view.canvas.getBoundingClientRect().width/this.view.canvas.width;}
 start(edit=false){this.cancel();const doc=this.active();if(!doc)throw new Error('请先打开文档。');const layer=doc.selected,c=layer?.content;if(edit&&(c?.type!=='path'||layerLocked(doc.state.layers,layer!.id)))throw new Error('请选择未锁定的路径图层。');this.editing.setTool('path');const p=edit?parentOffset(doc.state.layers,layer!.id)!:{x:0,y:0};this.draft={doc,revision:doc.revision,id:edit?layer!.id:null,closed:edit?(c as PathContent).closed:true,nodes:edit?(c as PathContent).nodes.map(n=>({x:n.x+layer!.x+p.x,y:n.y+layer!.y+p.y,inX:n.inX+layer!.x+p.x,inY:n.inY+layer!.y+p.y,outX:n.outX+layer!.x+p.x,outY:n.outY+layer!.y+p.y})):[]};this.draw();this.notify('路径：点击加点／选点，拖出或调整控制柄，Enter 应用，Esc 取消。');}
 private move(e:PointerEvent){const d=this.draft,r=this.drag;if(!d||r?.pointer!==e.pointerId)return;const p=this.view.point(e),n=d.nodes[r.index]!;if(r.handle==='anchor'){const dx=p.x-n.x,dy=p.y-n.y;Object.assign(n,{x:p.x,y:p.y,inX:n.inX+dx,inY:n.inY+dy,outX:n.outX+dx,outY:n.outY+dy});}else if(r.handle==='in'){n.inX=p.x;n.inY=p.y;}else{n.outX=p.x;n.outY=p.y;if(r.handle==='new'){n.inX=2*n.x-p.x;n.inY=2*n.y-p.y;}}this.draw();}
 toggleClosed(){if(this.draft){this.draft.closed=!this.draft.closed;this.draw();}}
 apply(){const d=this.draft;if(!d)return;if(this.active()!==d.doc||d.revision!==d.doc.revision)throw new Error('文档已变化，请重新绘制路径。');if(d.nodes.length<2)throw new Error('路径至少需要两个锚点。');const old=d.id?findLayer(d.doc.state.layers,d.id):undefined,previous=old?.content?.type==='path'?old.content:undefined,strokeWidth=previous?.strokeWidth??2,pad=strokeWidth/2+1,x=Math.floor(Math.min(...d.nodes.flatMap(p=>[p.x,p.inX,p.outX]))-pad),y=Math.floor(Math.min(...d.nodes.flatMap(p=>[p.y,p.inY,p.outY]))-pad),right=Math.ceil(Math.max(...d.nodes.flatMap(p=>[p.x,p.inX,p.outX]))+pad),bottom=Math.ceil(Math.max(...d.nodes.flatMap(p=>[p.y,p.inY,p.outY]))+pad);
  const content:PathContent={type:'path',width:right-x,height:bottom-y,closed:d.closed,fill:previous?previous.fill:d.closed?(document.getElementById('paint-color') as HTMLInputElement).value:null,stroke:previous?.stroke??'#ffffff',strokeWidth,fillRule:previous?.fillRule??'evenodd',nodes:d.nodes.map(p=>({x:p.x-x,y:p.y-y,inX:p.inX-x,inY:p.inY-y,outX:p.outX-x,outY:p.outY-y}))};validateContent(content);const bitmap=rasterContent(content);
  if(old){const parent=parentOffset(d.doc.state.layers,old.id)!,left=x-parent.x,top=y-parent.y,layer={...old,x:left,y:top,content,bitmap,...(old.mask?{mask:{...old.mask,x:old.mask.x+old.x-left,y:old.mask.y+old.y-top}}:{})};d.doc.commitLayers('编辑贝塞尔路径',replacePixel(d.doc.state.layers,old.id,layer),[old.id]);}else d.doc.addLayer({...makeLayer('贝塞尔路径',bitmap),content,x,y},false);this.cancel();
 }
 private draw(){const d=this.draft;if(!d)return;this.svg.style.display='block';this.svg.setAttribute('viewBox',`0 0 ${d.doc.state.width} ${d.doc.state.height}`);this.svg.setAttribute('width',String(d.doc.state.width));this.svg.setAttribute('height',String(d.doc.state.height));this.svg.replaceChildren();const add=(type:string,attrs:Record<string,string>)=>{const n=document.createElementNS(this.svg.namespaceURI,type);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);this.svg.append(n);};let path='';d.nodes.forEach((p,i)=>{const a=d.nodes[i-1];path+=a?` C ${a.outX} ${a.outY} ${p.inX} ${p.inY} ${p.x} ${p.y}`:`M ${p.x} ${p.y}`;});if(d.closed&&d.nodes.length>1){const a=d.nodes.at(-1)!,b=d.nodes[0]!;path+=` C ${a.outX} ${a.outY} ${b.inX} ${b.inY} ${b.x} ${b.y} Z`;}add('path',{d:path,fill:'none',stroke:'#ffb17d','stroke-width':String(1/this.viewScale())});for(const p of d.nodes){add('path',{d:`M ${p.inX} ${p.inY} L ${p.x} ${p.y} L ${p.outX} ${p.outY}`,stroke:'#8bd5ff','stroke-width':String(1/this.viewScale()),fill:'none'});for(const [x,y,color] of [[p.inX,p.inY,'#8bd5ff'],[p.outX,p.outY,'#8bd5ff'],[p.x,p.y,'#ffb17d']] as const)add('circle',{cx:String(x),cy:String(y),r:String(3/this.viewScale()),fill:color});}}
 sync(){if(this.draft&&(this.active()!==this.draft.doc||this.draft.doc.revision!==this.draft.revision))this.cancel();}
 cancel(){const pointer=this.drag?.pointer;this.drag=undefined;this.draft=undefined;if(pointer!==undefined&&this.view.viewport.hasPointerCapture(pointer))this.view.viewport.releasePointerCapture(pointer);this.svg.style.display='none';this.svg.replaceChildren();}
 dispose(){this.cancel();this.abort.abort();this.svg.remove();}
}
