import type { EditorJsonValue } from '@haiyue/editor-plugin-sdk';
import type { ImageWorkspace } from './workspace.js';
import { uid, type ImageDocument } from './document.js';
import { defaultLayout, type ImageAction, type Layout } from './productivityModel.js';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const value=(id:string)=>$<HTMLInputElement>(id).value;
export class ProductivityPanel {
 private doc:ImageDocument|undefined;private revision=0;private request:string|undefined;private generation=0;private urls:string[]=[];private layout:Layout=defaultLayout();private overlay=document.createElementNS('http://www.w3.org/2000/svg','svg');
 constructor(private workspace:ImageWorkspace){
  document.querySelector('.advanced-actions')!.insertAdjacentHTML('beforeend','<button data-action="productivity" data-needs-document>通道／生产工具</button>');
  this.overlay.id='guide-overlay';this.overlay.setAttribute('aria-hidden','true');$('artboard').append(this.overlay);
  document.body.insertAdjacentHTML('beforeend',`<dialog id="production-dialog"><h2>通道与生产工具</h2><label>工具<select id="production-tab"><option value="channels">命名选区／Alpha 通道</option><option value="layout">参考线与吸附</option><option value="actions">参数化动作／模板输出</option></select></label>
  <section id="production-channels"><label>通道<select id="channel-list"></select></label><canvas id="channel-preview" width="480" height="180" aria-label="Alpha 通道灰度预览"></canvas><label>名称<input id="channel-name" value="选区 1" maxlength="160"></label><label>来源<select id="channel-source"><option value="selection">当前选区</option><option value="red">合成红通道</option><option value="green">合成绿通道</option><option value="blue">合成蓝通道</option><option value="alpha">合成透明度</option></select></label><div class="production-buttons"><button id="channel-save">新建通道</button><button id="channel-replace">替换所选</button><button id="channel-rename">重命名</button><button id="channel-invert">反相</button><button id="channel-delete">删除</button></div><label>载入方式<select id="channel-mode"><option value="replace">替换</option><option value="add">添加</option><option value="subtract">减去</option><option value="intersect">相交</option></select><button id="channel-load">载入选区</button></label><p class="muted">灰度保留软边覆盖率；白色为选中区域。载入后可用于蒙版或像素编辑。</p></section>
  <section id="production-layout" hidden><label><input id="guide-visible" type="checkbox">显示参考线</label><label><input id="guide-snap" type="checkbox">启用吸附</label><label><input id="guide-canvas" type="checkbox">吸附画布边缘／中心</label><label><input id="guide-layers" type="checkbox">吸附其他可见图层边缘／中心</label><label>吸附距离（屏幕像素）<input id="guide-tolerance" type="number" min="0" max="32" value="6"></label><select id="guide-list" size="5" aria-label="参考线列表"></select><label>方向<select id="guide-axis"><option value="x">垂直</option><option value="y">水平</option></select>位置 px<input id="guide-position" type="number" min="-32768" max="32768" value="0"></label><div class="production-buttons"><button id="guide-add">添加</button><button id="guide-update">更新所选</button><button id="guide-delete">删除所选</button><button id="guide-save" class="primary">应用参考线</button></div><p class="muted">用于图层移动、自由变换平移和矩形选区终点；按住 Alt 临时绕过。参考线不进入导出图像。</p></section>
  <section id="production-actions" hidden><label>动作<select id="action-list"></select><button id="action-new">新建示例</button><button id="action-delete">删除</button></label><label>动作定义 JSON<textarea id="action-json" rows="12" spellcheck="false" aria-label="动作定义 JSON"></textarea></label><p class="muted">步骤支持 layer.update、pixels.fill、filter.apply、text.replace、smart.filters、layer.transform。layerId 可用 $selected；参数引用写为 {"param":"参数名"}。文字模板请使用统一样式文字层。</p><button id="action-save">保存动作</button><label>本次参数 JSON<textarea id="action-values" rows="3" spellcheck="false">{}</textarea></label><button id="action-run" class="primary">运行已保存动作（可撤销）</button><hr><label>模板数据行 JSON<textarea id="template-rows" rows="6" spellcheck="false"></textarea></label><label>导入数据行<input id="template-file" type="file" accept=".json,application/json"></label><label>导出格式<select id="template-format"><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="project">保留图层的工程</option><option value="psd">PSD 副本</option></select></label><label><input id="template-consent" type="checkbox">允许 PSD 省略生产数据，并在必要时合并不支持的图层</label><button id="template-export">批量生成副本</button><p class="muted">每批最多 16 行。每行有 name 和 values；PNG／JPEG 可增加 width、height，按比例居中适配。原稿不变。</p><div id="template-results"></div></section>
  <p id="production-status" role="status"></p><p id="production-error" role="alert"></p><div class="dialog-actions"><button id="production-cancel" hidden>取消任务</button><button data-close-dialog>关闭</button></div></dialog>`);
  $('production-tab').onchange=()=>{for(const k of ['channels','layout','actions'])$('production-'+k).hidden=value('production-tab')!==k;};
  $('channel-list').onchange=()=>{const c=this.current().state.channels?.find(c=>c.id===value('channel-list'));if(c)$<HTMLInputElement>('channel-name').value=c.name;void this.previewChannel();};
  for(const [button,op,params] of [
   ['channel-save','channel.save',()=>({name:value('channel-name'),source:value('channel-source')})],['channel-replace','channel.save',()=>({id:value('channel-list'),name:value('channel-name'),source:value('channel-source')})],['channel-rename','channel.update',()=>({id:value('channel-list'),name:value('channel-name')})],['channel-invert','channel.update',()=>({id:value('channel-list'),invert:true})],['channel-delete','channel.delete',()=>({id:value('channel-list')})],['channel-load','channel.load',()=>({id:value('channel-list'),mode:value('channel-mode')})]
  ] as const)$(button).onclick=()=>void this.guard(async()=>{const result=await this.call(op,params());this.channels((result as {channelId?:string}).channelId);});
  $('guide-list').onchange=()=>{const g=this.layout.guides.find(g=>g.id===value('guide-list'));if(g){$<HTMLInputElement>('guide-axis').value=g.axis;$<HTMLInputElement>('guide-position').value=String(g.position);}};
  for(const action of ['add','update','delete'])$('guide-'+action).onclick=()=>void this.guard(async()=>{const id=value('guide-list'),guides=[...this.layout.guides],index=guides.findIndex(g=>g.id===id);if(action==='delete'){if(index>=0)guides.splice(index,1);}else{const position=Number(value('guide-position'));if(!value('guide-position')||!Number.isInteger(position)||Math.abs(position)>32768)throw new Error('参考线位置须为 -32768–32768 的整数。');const g={id:action==='update'?id:uid(),axis:value('guide-axis') as 'x'|'y',position};if(action==='update'){if(index<0)throw new Error('请选择参考线。');guides[index]=g;}else guides.push(g);}this.layout={...this.layout,guides};this.guideList();});
  $('guide-save').onclick=()=>void this.guard(async()=>{const layout={...this.layout,visible:$<HTMLInputElement>('guide-visible').checked,snap:$<HTMLInputElement>('guide-snap').checked,canvas:$<HTMLInputElement>('guide-canvas').checked,layers:$<HTMLInputElement>('guide-layers').checked,tolerance:Number(value('guide-tolerance'))};await this.call('layout.set',{layout:layout as unknown as EditorJsonValue});});
  $('action-list').onchange=()=>this.actionFields();$('action-new').onclick=()=>this.example();$('action-save').onclick=()=>void this.guard(async()=>{const a=JSON.parse(value('action-json'));await this.call('action.save',{action:a});this.actionList(a.id);});$('action-delete').onclick=()=>void this.guard(async()=>{await this.call('action.delete',{id:value('action-list')});this.actionList();});
  $('action-run').onclick=()=>void this.guard(async()=>{await this.call('action.run',{id:value('action-list'),values:JSON.parse(value('action-values'))});});
  $('template-file').onchange=()=>void this.guard(async()=>{const file=$<HTMLInputElement>('template-file').files?.[0];if(file){if(file.size>262144)throw new Error('模板数据超过 256 KiB。');const rows=JSON.parse(await file.text());if(!Array.isArray(rows))throw new Error('数据行须为 JSON 数组。');$<HTMLTextAreaElement>('template-rows').value=JSON.stringify(rows,null,2);}});
  $('template-export').onclick=()=>void this.guard(async()=>{this.clearDownloads();const results=await this.call('template.export',{actionId:value('action-list'),rows:JSON.parse(value('template-rows')),format:value('template-format'),allowRasterize:$<HTMLInputElement>('template-consent').checked}) as {name:string;resourceId?:string;error?:string}[];for(const r of results){const line=document.createElement('p');if(r.resourceId){try{const bytes=workspace.platform.resources.read(r.resourceId),url=URL.createObjectURL(new Blob([bytes.slice().buffer])),a=document.createElement('a');this.urls.push(url);a.href=url;a.download=r.name;a.textContent='下载 '+r.name;line.append(a);}finally{workspace.platform.resources.release(r.resourceId);}}else line.textContent=r.name+'：'+r.error;$('template-results').append(line);}});
  $('production-cancel').onclick=()=>{if(this.request)workspace.platform.operations.cancel(this.request);};$('production-dialog').addEventListener('close',()=>{if(!$<HTMLDialogElement>('production-dialog').open){if(this.request)workspace.platform.operations.cancel(this.request);this.generation++;this.doc=undefined;}});
 }
 private current(){if(!this.doc||this.workspace.active!==this.doc)throw new Error('文档已切换，请重新打开面板。');return this.doc;}
 private async call(operation:string,params:EditorJsonValue){const d=this.current();if(d.revision!==this.revision)throw new Error('文档已变化，请重新打开面板。');const id=this.request=uid();$('production-cancel').hidden=false;try{const result=await this.workspace.platform.operations.execute({apiVersion:'1',requestId:id,operation:'image.'+operation,documentId:d.identity.id,expectedRevision:this.revision,params});if(result.status!=='completed')throw new Error(result.error.message);this.revision=d.revision;return result.value;}finally{this.request=undefined;$('production-cancel').hidden=true;}}
 private async guard(action:()=>Promise<void>){if(this.request)return;$('production-error').textContent='';$('production-status').textContent='正在处理…';try{await action();$('production-status').textContent='已完成';}catch(e){$('production-status').textContent='';$('production-error').textContent=e instanceof Error?e.message:String(e);}}
 open(){const d=this.workspace.active;if(!d)throw new Error('请先打开文档。');this.doc=d;this.revision=d.revision;this.layout=structuredClone(d.state.layout??defaultLayout());for(const k of ['visible','snap','canvas','layers'] as const)$<HTMLInputElement>('guide-'+k).checked=this.layout[k];$<HTMLInputElement>('guide-tolerance').value=String(this.layout.tolerance);this.guideList();this.channels();this.actionList();$('production-error').textContent='';$('production-status').textContent='';$<HTMLDialogElement>('production-dialog').showModal();$('production-dialog').scrollTop=0;}
 private channels(id=value('channel-list')){$<HTMLSelectElement>('channel-list').replaceChildren(...(this.current().state.channels??[]).map(c=>new Option(c.name,c.id,false,c.id===id)));void this.previewChannel();}
 private async previewChannel(){const generation=++this.generation,canvas=$<HTMLCanvasElement>('channel-preview'),ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,canvas.width,canvas.height);const d=this.current(),c=d.state.channels?.find(c=>c.id===value('channel-list'));for(const id of ['channel-replace','channel-rename','channel-invert','channel-delete','channel-load'])$<HTMLButtonElement>(id).disabled=!c;if(!c)return;const temp=document.createElement('canvas');temp.width=d.state.width;temp.height=d.state.height;const rgba=Uint8ClampedArray.from({length:c.data.length*4},(_,i)=>i%4===3?255:c.data[Math.floor(i/4)]!);temp.getContext('2d')!.putImageData(new ImageData(rgba,temp.width,temp.height),0,0);if(generation===this.generation){const scale=Math.min(canvas.width/temp.width,canvas.height/temp.height);ctx.drawImage(temp,(canvas.width-temp.width*scale)/2,(canvas.height-temp.height*scale)/2,temp.width*scale,temp.height*scale);}temp.width=temp.height=1;}
 private guideList(){$<HTMLSelectElement>('guide-list').replaceChildren(...this.layout.guides.map(g=>new Option(`${g.axis==='x'?'垂直':'水平'} · ${g.position} px`,g.id)));}
 private actionList(id=value('action-list')){$<HTMLSelectElement>('action-list').replaceChildren(...(this.current().state.actions??[]).map(a=>new Option(a.name,a.id,false,a.id===id)));this.actionFields();}
 private actionFields(){const a=this.current().state.actions?.find(a=>a.id===value('action-list'));if(!a){this.example();return;}$<HTMLTextAreaElement>('action-json').value=JSON.stringify(a,null,2);$<HTMLTextAreaElement>('action-values').value=JSON.stringify(Object.fromEntries(a.parameters.map(p=>[p.name,p.default??(p.type==='number'?0:p.type==='boolean'?true:'')])),null,2);$<HTMLTextAreaElement>('template-rows').value=JSON.stringify([{name:'版本一',values:JSON.parse(value('action-values'))},{name:'版本二',values:JSON.parse(value('action-values'))}],null,2);}
 private example(){const text=this.current().selected?.content?.type==='text',a:ImageAction={id:uid(),name:text?'文字模板':'图层透明度模板',parameters:[text?{name:'title',type:'string',default:'海上生明月'}:{name:'opacity',type:'number',default:.8}],steps:[{operation:text?'text.replace':'layer.update',params:{layerId:this.current().selected?.id??'$selected',...(text?{text:{param:'title'}}:{patch:{opacity:{param:'opacity'}}})}}]};$<HTMLTextAreaElement>('action-json').value=JSON.stringify(a,null,2);$<HTMLTextAreaElement>('action-values').value=JSON.stringify(text?{title:'海上生明月'}:{opacity:.8});$<HTMLTextAreaElement>('template-rows').value=JSON.stringify(text?[{name:'月色',values:{title:'海上生明月'}},{name:'远方',values:{title:'天涯共此时'}}]:[{name:'版本一',values:{opacity:1}},{name:'版本二',values:{opacity:.5}}],null,2);}
 sync(){const s=this.workspace.active?.state;this.overlay.replaceChildren();this.overlay.style.display=s?.layout?.visible?'block':'none';if(!s)return;this.overlay.setAttribute('viewBox',`0 0 ${s.width} ${s.height}`);for(const g of s.layout?.guides??[]){const line=document.createElementNS(this.overlay.namespaceURI,'line');for(const [k,v] of Object.entries(g.axis==='x'?{x1:g.position,x2:g.position,y1:0,y2:s.height}:{x1:0,x2:s.width,y1:g.position,y2:g.position}))line.setAttribute(k,String(v));line.setAttribute('vector-effect','non-scaling-stroke');this.overlay.append(line);}}
 private clearDownloads(){for(const url of this.urls)URL.revokeObjectURL(url);this.urls=[];$('template-results').replaceChildren();}
 dispose(){if(this.request)this.workspace.platform.operations.cancel(this.request);this.clearDownloads();this.overlay.remove();this.doc=undefined;}
}
