import { RESAMPLING } from './resampling.js';
import type { EditorJsonValue } from '@haiyue/editor-plugin-sdk';
import type { ImageWorkspace } from './workspace.js';
import { FILTERS } from './filters.js';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export class ProfessionalPanel {
 private dialog=document.createElement('dialog');private controller:AbortController|undefined;private resources:string[]=[];private urls:string[]=[];
 constructor(private workspace:ImageWorkspace,private notify:(s:string,error?:boolean)=>void){
  this.dialog.id='professional-dialog';this.dialog.innerHTML=`<h2 id="professional-title"></h2>
  <section id="professional-refine"><p>利用图像亮度边缘细化当前选区；调整后可撤销。</p><label>半径 <input id="refine-radius" type="number" min="1" max="32" value="4"></label><label>对比度 <input id="refine-contrast" type="number" min="0" max="100" value="10"></label><label>边缘偏移 <input id="refine-shift" type="number" min="-32" max="32" value="0"></label><label><input id="refine-edge" type="checkbox" checked>图像引导</label></section>
  <section id="professional-color"><p>按源空间转换到 sRGB（ICC v2/v4 矩阵／曲线）。超出色域时裁切；调整层需先合成。</p><label>源空间 <select id="profile-source"><option value="embedded">文档嵌入的 ICC</option><option value="srgb">sRGB</option><option value="display-p3">Display P3</option><option value="adobe-rgb">Adobe RGB (1998)</option><option value="resource">导入 ICC 文件</option></select></label><input id="profile-file" type="file" accept=".icc,.icm"><p id="profile-info" class="muted"></p></section>
  <section id="professional-batch"><p>处理独立合成副本，原文件不变。每批 1–16 个文件、最多 128 MiB；带 ICC 的工程请先转为 sRGB。</p><input id="batch-files" type="file" accept=".png,.jpg,.jpeg,.psd,.hyimage" multiple><div class="dimension-fields"><label>限制宽度<input id="batch-width" type="number" min="1" max="8192" value="1920"></label><label>限制高度<input id="batch-height" type="number" min="1" max="8192" value="1080"></label></div><p class="muted">保持比例缩小，不放大小图。</p><label>重采样<select id="batch-resampling">${Object.entries(RESAMPLING).map(([k,v])=>`<option value="${k}" ${k==='bicubic'?'selected':''}>${v}</option>`).join('')}</select></label><label>滤镜<select id="batch-filter"><option value="">无</option>${Object.entries(FILTERS).map(([key,v])=>`<option value="${key}">${v.name}</option>`).join('')}</select></label><label>强度<input id="batch-amount" type="number" value="15"></label><div id="batch-usm" hidden><label>半径 σ<input id="batch-radius" type="number" min="0.1" max="32" step="0.1" value="2"></label><label>阈值<input id="batch-threshold" type="number" min="0" max="255" value="0"></label></div><label>输出<select id="batch-format"><option value="png">PNG</option><option value="jpeg">JPEG（白底）</option><option value="project">单层工程</option></select></label><div id="batch-results"></div></section>
  <p id="professional-status" role="status"></p><div class="dialog-actions"><button id="professional-close">关闭</button><button id="professional-stop" hidden>取消处理</button><button id="professional-run" class="primary">应用</button></div>`;
  document.body.append(this.dialog);$('professional-close').onclick=()=>this.dialog.close();$('professional-stop').onclick=()=>this.controller?.abort();this.dialog.addEventListener('close',()=>{this.controller?.abort();this.clear();});$('professional-run').onclick=()=>void this.execute();$('batch-filter').onchange=()=>{const kind=$<HTMLSelectElement>('batch-filter').value as keyof typeof FILTERS;const c=FILTERS[kind];$('batch-usm').hidden=kind!=='usm';if(c){const a=$<HTMLInputElement>('batch-amount');a.step=kind==='gaussian'?'0.1':'1';a.min=String(c.min);a.max=String(c.max);a.value=String(c.value);}};
 }
 private mode:'refine'|'color'|'batch'='refine';
 open(mode:'refine'|'color'|'batch'){if(this.controller)throw new Error('请先完成或取消正在处理的任务。');this.mode=mode;for(const m of ['refine','color','batch'])$('professional-'+m).hidden=m!==mode;$('professional-title').textContent={refine:'选区边缘细化',color:'色彩管理 · 转换到 sRGB',batch:'批处理'}[mode];$('professional-status').textContent='';$('profile-info').textContent=this.workspace.active?.state.colorManagement?'当前文档已转换到 sRGB。':'PSD 中的嵌入配置不会自动转换，请在此指定源空间。';this.dialog.showModal();}
 private clear(){for(const id of this.resources)this.workspace.platform.resources.release(id);this.resources=[];for(const url of this.urls)URL.revokeObjectURL(url);this.urls=[];$('batch-results').replaceChildren();}
 private async execute(){if(this.controller)return;this.clear();const controller=this.controller=new AbortController(),signal=controller.signal,requestId='professional-'+crypto.randomUUID(),platform=this.workspace.platform,doc=this.workspace.active,temporary:string[]=[];
  const subscription=platform.operations.subscribe(e=>{if(e.requestId===requestId&&e.progress)$('professional-status').textContent=`${e.progress.current} / ${e.progress.total??'?'} · ${e.progress.message??''}`;});
  $('professional-run').setAttribute('disabled','');$('professional-stop').hidden=false;$('professional-status').textContent='处理中…';
  try {const value=(id:string)=>$<HTMLInputElement>(id).value;let params:EditorJsonValue,operation:string;
   if(this.mode==='refine'){operation='selection.refine';params={radius:Number(value('refine-radius')),contrast:Number(value('refine-contrast')),shift:Number(value('refine-shift')),edgeAware:$<HTMLInputElement>('refine-edge').checked};}
   else if(this.mode==='color'){operation='color.convert';const source=value('profile-source');params={source};if(source==='resource'){const file=$<HTMLInputElement>('profile-file').files?.[0];if(!file||file.size>4*1024*1024)throw new Error('请选择不超过 4 MiB 的 ICC 文件。');const id=platform.resources.put(new Uint8Array(await file.arrayBuffer())).resourceId;temporary.push(id);params={source,resourceId:id};}}
   else {operation='batch.run';const files=Array.from($<HTMLInputElement>('batch-files').files??[]);if(!files.length||files.length>16||files.reduce((n,f)=>n+f.size,0)>128*1024*1024)throw new Error('请选择 1–16 个文件，合计不超过 128 MiB。');const inputs=[];for(const file of files){signal.throwIfAborted();const resourceId=platform.resources.put(new Uint8Array(await file.arrayBuffer())).resourceId;temporary.push(resourceId);inputs.push({resourceId,name:file.name.slice(0,160),format:/\.hyimage$/i.test(file.name)?'project':/\.psd$/i.test(file.name)?'psd':/\.png$/i.test(file.name)?'png':'jpeg'});}const steps:EditorJsonValue[]=[{type:'fit',width:Number(value('batch-width')),height:Number(value('batch-height')),resampling:value('batch-resampling')}];if(value('batch-filter'))steps.push({type:'filter',kind:value('batch-filter'),amount:Number(value('batch-amount')),...(value('batch-filter')==='usm'?{radius:Number(value('batch-radius')),threshold:Number(value('batch-threshold'))}:{})});params={inputs,steps,format:value('batch-format')};}
   signal.throwIfAborted();if(this.mode!=='batch'&&!doc)throw new Error('请先打开文档。');const result=await platform.operations.execute({apiVersion:'1',requestId,operation:'image.'+operation,params,...(this.mode!=='batch'&&doc?{documentId:doc.identity.id,expectedRevision:doc.revision}:{})},{signal});
   if(result.status!=='completed')throw new Error(result.error.message);
   if(signal.aborted&&this.mode==='batch'){for(const item of result.value as {resourceId?:string}[])if(item.resourceId)platform.resources.release(item.resourceId);signal.throwIfAborted();}
   if(this.mode==='batch'){for(const item of result.value as {name:string;resourceId?:string;error?:string}[]){const row=document.createElement('p');if(item.resourceId){this.resources.push(item.resourceId);const bytes=platform.resources.read(item.resourceId),url=URL.createObjectURL(new Blob([bytes.slice().buffer])),link=document.createElement('a');this.urls.push(url);link.href=url;link.download=item.name;link.textContent='下载 '+item.name;row.append(link);}else row.textContent=item.name+'：'+item.error;$('batch-results').append(row);}$('professional-status').textContent='批处理完成，点击结果下载。';}
   else{this.dialog.close();this.notify('已应用，可撤销。');}
  }catch(error){$('professional-status').textContent=signal.aborted?'已取消。':error instanceof Error?error.message:String(error);}
  finally{for(const id of temporary)platform.resources.release(id);void subscription.dispose();this.controller=undefined;$('professional-run').removeAttribute('disabled');$('professional-stop').hidden=true;}
 }
 dispose(){this.controller?.abort();this.clear();this.dialog.remove();}
}
