import type { TextContent, TextRun } from './layerFeatures.js';
export type RunStyle=Omit<TextRun,'start'|'end'>;
const same=(a:RunStyle,b:RunStyle)=>JSON.stringify(a)===JSON.stringify(b);
export function textStyles(content:TextContent):RunStyle[]{const styles=Array.from({length:content.text.length},()=>({}) as RunStyle);for(const r of content.runs??[])for(let i=r.start;i<r.end;i++){const {start,end,...style}=r;styles[i]=style;}return styles;}
export function compressRuns(styles:readonly RunStyle[]):TextRun[]{const runs:TextRun[]=[];for(let i=0;i<styles.length;){let end=i+1;while(end<styles.length&&same(styles[i]!,styles[end]!))end++;if(Object.keys(styles[i]!).length)runs.push({start:i,end,...styles[i]!});i=end;}if(runs.length>128)throw new Error('富文本最多包含 128 个样式片段。');return runs;}
export function formatRange(content:TextContent,start:number,end:number,style:RunStyle):TextRun[]{if(start<0||end>content.text.length||start>=end)throw new Error('请先选中文字范围。');const styles=textStyles(content);for(let i=start;i<end;i++)styles[i]={...styles[i],...style};return compressRuns(styles);}
export function rebaseRuns(content:TextContent,next:string):TextRun[]{const old=content.text,styles=textStyles(content);let a=0;while(a<old.length&&a<next.length&&old[a]===next[a])a++;let b=old.length,c=next.length;while(b>a&&c>a&&old[b-1]===next[c-1]){b--;c--;}const inherit=styles[a]??styles[a-1]??{};return compressRuns([...styles.slice(0,a),...Array.from({length:c-a},()=>inherit),...styles.slice(b)]);}
/** Grapheme-aware layout keeps style ranges as UTF-16 offsets, like textarea selection. */
export function rasterRichText(canvas:HTMLCanvasElement,content:TextContent){
 const ctx=canvas.getContext('2d')!,styles=textStyles(content),padding=Math.ceil(content.size*.5),limit=content.wrapWidth??8192-padding*2;
 type Glyph={text:string;style:TextContent&RunStyle;width:number;key:string};const lines:{glyphs:Glyph[];width:number;size:number}[]=[{glyphs:[],width:0,size:content.size}];
 const font=(s:TextContent&RunStyle)=>`${s.italic?'italic ':''}${s.bold?'bold ':''}${s.size}px ${s.fontName?'"'+s.fontName+'", ':''}${s.family}`;
 const segments=new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(content.text);
 for(const part of segments){const run=styles[part.index]!,style={...content,...run},text=part.segment;if(run.family&&run.family!==content.family&&!run.fontName)delete style.fontName;if(text==='\n'||text==='\r\n'){lines.push({glyphs:[],width:0,size:content.size});continue;}ctx.font=font(style);const key=ctx.font+'|'+style.color+'|'+Boolean(style.underline);let line=lines.at(-1)!,last=line.glyphs.at(-1),width=last?.key===key?ctx.measureText(last.text+text).width-last.width:ctx.measureText(text).width;if(line.glyphs.length&&line.width+width>limit){line={glyphs:[],width:0,size:content.size};lines.push(line);last=undefined;width=ctx.measureText(text).width;}if(last?.key===key){last.text+=text;last.width+=width;}else line.glyphs.push({text,style,width,key});line.width+=width;line.size=Math.max(line.size,style.size);}
 const width=Math.max(1,Math.ceil(content.wrapWidth??Math.max(...lines.map(l=>l.width)))+padding*2),height=Math.ceil(lines.reduce((n,l)=>n+l.size*1.4,0)+padding*2);
 if(width>8192||height>8192||width*height>16777216)throw new Error('富文本渲染尺寸超出限制。');canvas.width=width;canvas.height=height;ctx.textBaseline='alphabetic';let y=padding;
 for(const line of lines){let x=content.align==='left'?padding:content.align==='right'?width-padding-line.width:(width-line.width)/2;for(const glyph of line.glyphs){const s=glyph.style;ctx.font=font(s);ctx.fillStyle=s.color;ctx.fillText(glyph.text,x,y+line.size);if(s.underline)ctx.fillRect(x,y+line.size+Math.max(1,s.size*.08),glyph.width,Math.max(1,s.size*.06));x+=glyph.width;}y+=line.size*1.4;}
}
