import {createHash} from 'node:crypto';
import {importPsd} from '../dist/psdAdapter.js';
const hash=b=>createHash('sha256').update(b).digest('hex');
export function validatePhotoshopRun(manifest,receipt,read){
 if(![1,2].includes(manifest.schemaVersion)||receipt.schemaVersion!==1||receipt.runId!==manifest.runId||!receipt.application?.includes('Photoshop')||!receipt.version||hash(read('run-in-photoshop.jsx'))!==manifest.scriptSha256)throw Error('Invalid Photoshop receipt or script fingerprint.');
 const expected=manifest.schemaVersion===2?['rgb8.psd','rgb16.psd','rgb32.psd','cmyk8.psd','cmyk16.psd']:['rgb8.psd','rgb16.psd','rgb32.psd'];
 if(!Array.isArray(manifest.cases)||manifest.cases.length!==expected.length||new Set(manifest.cases.map(c=>c.name)).size!==expected.length||manifest.cases.some(c=>!expected.includes(c.name)||c.name!==`${c.colorMode??'rgb'}${c.depth}.psd`||c.width!==32||c.height!==24)||!Array.isArray(receipt.cases)||receipt.cases.length!==expected.length||new Set(receipt.cases.map(c=>c.name)).size!==expected.length)throw Error('Incomplete certification case set');
 const results=manifest.cases.map(c=>{if(!/^(rgb(8|16|32)|cmyk(8|16))\.psd$/.test(c.name)||c.output!==c.name.replace('.psd','-photoshop.psd'))throw Error('Unsafe manifest path');const original=read(c.name);if(hash(original)!==c.sha256)throw Error('Input hash changed');const record=receipt.cases.find(r=>r.name===c.name);if(!record?.ok)throw Error(`Photoshop failed ${c.name}: ${record?.error}`);const output=read(c.output),a=importPsd(original,c.name).layered,result=importPsd(output,c.output),b=result.layered;if(!a||!b)throw Error('Reimport requires fallback: '+result.blockers.join(';'));if((b.colorMode??'rgb')!==(c.colorMode??'rgb')||(b.bitDepth??8)!==c.depth||b.width!==c.width||b.height!==c.height||b.layers.length!==1||b.layers[0].name!=='Certified edit')throw Error('Native document properties changed');const x=a.layers[0].bitmap,y=b.layers[0].bitmap;if(!x||!y||x.data.length!==y.data.length)throw Error('Pixel geometry changed');const xx=c.colorMode==='cmyk'?x.cmyk:x.data,yy=c.colorMode==='cmyk'?y.cmyk:y.data;if(!xx||!yy||xx.length!==yy.length)throw Error('Native channel geometry changed');let max=0;for(let i=0;i<xx.length;i++)max=Math.max(max,Math.abs(xx[i]-yy[i]));if(c.colorMode==='cmyk'&&x.data.some((v,i)=>i%4===3&&Math.abs(v-y.data[i])>1/257))throw Error('CMYK alpha changed');const tolerance=c.colorMode==='cmyk'?200/(c.depth===8?255:65535)+1e-5:c.depth===8?0:c.depth===16?2/257:0.001;if(max>tolerance)throw Error(`${c.name} pixel drift ${max} > ${tolerance}`);return {name:c.name,sha256:hash(output),maxPixelError:max,status:'passed'};});
return results;
}
