import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';
import {ImageDocument,makeLayer} from '../dist/document.js';import {cmykBitmap,compositeCmyk,convertDocumentCmyk,convertDocumentRgb} from '../dist/cmyk.js';
import {serializeProject,deserializeProject} from '../dist/projectFile.js';import {RecoveryCodec,decodeRecovery} from '../dist/recoveryCodec.js';import {exportPsd,importPsd} from '../dist/psdAdapter.js';
import {initializeIcc} from '../dist/iccEngine.js';import {hdrAdmission,float16} from '../dist/hdrDisplay.js';import {ImageWorkspace} from '../dist/workspace.js';import {operationClient} from '../../scripts/editor-e2e/operationWorkflow.mjs';
import {executeReference,referenceHeader} from '../dist/iccReference.js';import apply from 'iccdev/IccApplyNamedCmm/iccApplyNamedCmm.js';import dump from 'iccdev/IccDumpProfile/iccDumpProfile.js';import fromXml from 'iccdev/IccFromXml/iccFromXml.js';
await initializeIcc(new Uint8Array(readFileSync(new URL('../../node_modules/lcms-wasm/dist/lcms.wasm',import.meta.url))));
const fixture=name=>new Uint8Array(readFileSync(new URL('../../node_modules/iccdev/Testing/'+name,import.meta.url)));
const factory=f=>options=>f({...options,locateFile:undefined});
function doc(depth){const b=cmykBitmap(2,1,new Float32Array([0,0,0,80,25.23,37.19,52.87,15.31]),[255,127.5],depth),l=makeLayer('原生 K',b);return new ImageDocument({id:crypto.randomUUID(),name:'CMYK',width:2,height:1,colorMode:'cmyk',bitDepth:depth,layers:[l],selectedId:l.id,revision:1});}
for(const depth of [8,16])test(`CMYK ${depth} native PSD, project, recovery, history preserve K`,async()=>{const d=doc(depth),before=d.state,ink=d.selected.bitmap.cmyk.slice();const saved=serializeProject(before);assert.equal(JSON.parse(saved).version,11);assert.deepEqual(deserializeProject(saved).layers[0].bitmap.cmyk,ink);const input={version:2,activeId:d.identity.id,documents:[{state:before,dirty:true}]},r=await new RecoveryCodec().encode(input,new Set());assert.equal(r.session.version,12);assert.deepEqual((await decodeRecovery(r.session,r.chunks)).documents[0].state.layers[0].bitmap.cmyk,ink);d.updateLayer(d.selected.id,{opacity:.6});d.history.undo();assert.equal(d.state,before);for(let i=0,state=before;i<2;i++){const out=exportPsd(state);assert.equal(new DataView(out.bytes.buffer).getUint16(24),4);const result=importPsd(out.bytes,'cmyk.psd');assert(result.layered,result.blockers.join());state=result.layered;assert.equal(state.colorMode,'cmyk');const next=state.layers[0].bitmap.cmyk;next.forEach((v,j)=>assert(Math.abs(v-ink[j])<100/(depth===8?255:65535)+1e-5,`${j}: ${v} != ${ink[j]}`));assert.equal(next[0],0);assert.equal(next[1],0);assert.equal(next[2],0);}d.dispose();});
test('CMYK native compositing, mask and alpha preserve separations; unsupported semantics fail atomically',()=>{const d=doc(16);const b=compositeCmyk(d.state);assert.equal(b.cmyk[3],80);const before=d.state;assert.throws(()=>d.updateLayer(d.selected.id,{clipping:true}),/CMYK/);assert.equal(d.state,before);assert.throws(()=>d.setDepth(32),/CMYK/);d.setDepth(8,true);assert.equal(d.selected.bitmap.cmyk[3],80);d.history.undo();assert.equal(d.state,before);d.setMask(d.selected.id,{width:2,height:1,x:0,y:0,data:new Uint8Array([128,255]),defaultColor:0,disabled:false});const masked=compositeCmyk(d.state);assert.equal(masked.cmyk[3],80);assert.equal(masked.data[3],128);d.dispose();});
test('HDR admission and half conversion cover headroom, fallback and boundaries',()=>{const d=doc(16);const s={...d.state,colorMode:'rgb',bitDepth:32,display:{output:'hdr',exposure:0,operator:'clip'}};assert.equal(hdrAdmission(s,true,true),'');assert.match(hdrAdmission(s,false,true),/HDR/);assert.match(hdrAdmission(s,true,false),/WebGPU/);assert.match(hdrAdmission({...s,icc:{monitorProfile:new Uint8Array(1)}},true,true),/SDR/);assert.equal(float16(1),0x3c00);assert.equal(float16(4),0x4400);assert.equal(float16(65504),0x7bff);assert.equal(float16(2**-24),1);assert.equal(float16(2**-25),0);assert.equal(float16(-1),0);d.dispose();});
test('ICC reference validates real v4 and transforms through LUTs',async()=>{const p=fixture('sRGB_v4_ICC_preference.icc');const info=await executeReference({mode:'validate',profiles:[{bytes:p,intent:1}]},factory(dump));assert.equal(info.status,'valid');const r=await executeReference({mode:'transform',profiles:[{bytes:p,intent:1},{bytes:p,intent:1}],input:fixture('ApplyDataFiles/rgbFloat.txt')},factory(apply));assert.equal(r.status,'transformed');assert.match(r.report,/icEncodeFloat/);assert.throws(()=>referenceHeader(new Uint8Array(132)));});
async function xmlProfile(path){const m=await fromXml({noInitialRun:true,print:()=>{},printErr:()=>{}});m.FS.writeFile('/p.xml',fixture(path));assert.equal(m.callMain(['/p.xml','/p.icc']),0);return m.FS.readFile('/p.icc');}
test('iccMAX calculator executes real v5 MPE instead of RGB fallback',async()=>{const p=await xmlProfile('Calc/srgbCalcTest.xml');assert.equal(referenceHeader(p),5);const r=await executeReference({mode:'transform',profiles:[{bytes:p,intent:3},{bytes:fixture('sRGB_v4_ICC_preference.icc'),intent:3}],input:fixture('Calc/srgbCalcTest.txt')},factory(apply));assert.equal(r.status,'transformed');assert.match(r.report,/1\.000/);});
const local='/System/Library/ColorSync/Profiles/Generic CMYK Profile.icc';
test('CMYK API mode, native ink read/write, RGB edit and undo use profile',async()=>{const w=new ImageWorkspace();await w.start();try{const d=ImageDocument.create('CMYK API',2,1,true);w.add(d);const call=operationClient(w.platform,d.identity.id),profile=w.platform.resources.put(await xmlProfile('V2/v2CmykLut16.xml'));await call('image.cmyk.mode',{mode:'cmyk',profileId:profile.resourceId});const id=d.selected.id;assert.equal((await call('image.document.query')).colorMode,'cmyk');await call('image.cmyk.fill',{layerId:id,ink:[0,0,0,75]});assert.deepEqual(Array.from(d.selected.bitmap.cmyk),[0,0,0,75,0,0,0,75]);const read=await call('image.cmyk.read',{layerId:id});assert.equal(read.format,'cmyka32fle');const before=d.state;await call('image.cmyk.write',{layerId:id,resourceId:read.resourceId});await call('image.history.undo');assert.equal(d.state,before);const b=d.selected.bitmap,data=b.data.slice();data[0]=250;d.replaceLayerPixels(id,{...d.selected,bitmap:structuredClone({...b,data})},'RGB worker 编辑');assert.deepEqual(d.selected.bitmap.cmyk.slice(4),b.cmyk.slice(4));assert.notDeepEqual(d.selected.bitmap.cmyk.slice(0,4),b.cmyk.slice(0,4));d.history.undo();await call('image.cmyk.mode',{mode:'rgb'});assert.equal(d.state.colorMode,'rgb');assert.equal(d.selected.bitmap.cmyk,undefined);await call('image.history.undo');assert.equal(d.state,before);w.platform.resources.release(read.resourceId);w.platform.resources.release(profile.resourceId);}finally{await w.dispose();}});

test('iccMAX named spectral colors and PCC transform with the official reference engine',async()=>{const named=await xmlProfile('Named/NamedColor.xml'),pcc=await xmlProfile('PCC/Lab_float-D50_2deg.xml');const r=await executeReference({mode:'transform',profiles:[{bytes:named,intent:3,pcc},{bytes:fixture('sRGB_v4_ICC_preference.icc'),intent:1}],input:fixture('Named/NamedColorTest.txt')},factory(apply));assert.equal(r.status,'transformed');assert.match(r.report,/Black/);const spectral=await xmlProfile('PCC/Spec400_10_700-D93_2deg-Abs.xml');const out=await executeReference({mode:'transform',profiles:[{bytes:named,intent:3,pcc:spectral},{bytes:pcc,intent:3}],input:fixture('Named/NamedColorTest.txt')},factory(apply));assert.equal(out.status,'transformed');assert.match(out.report,/Lab/);});
test('iccMAX DeviceLink environment, PQ/HLG and six-channel spectral inputs execute',async()=>{for(const name of ['BT2100PQSceneToDisplayLink','BT2100HlgSceneToDisplayLink']){const p=await xmlProfile('HDR/'+name+'.xml');const r=await executeReference({mode:'transform',profiles:[{bytes:p,intent:1}],input:fixture('ApplyDataFiles/rgbFloat.txt')},factory(apply));assert.equal(r.status,'transformed');}const gray=await xmlProfile('Display/GrayGSDF.xml');const g=await executeReference({mode:'transform',profiles:[{bytes:gray,intent:0,environment:[{name:'ambL',value:20}]}],input:fixture('Display/GrayTest.txt')},factory(apply));assert.equal(g.status,'transformed');const six=await xmlProfile('SpecRef/SixChanInputRef.xml');const r=await executeReference({mode:'transform',profiles:[{bytes:six,intent:3},{bytes:fixture('sRGB_v4_ICC_preference.icc'),intent:1}],input:fixture('SpecRef/sixChanTest.txt')},factory(apply));assert.equal(r.status,'transformed');});

test('CMYK tiled groups, partial native commits and malformed PSD alpha are bounded',()=>{const width=270,height=260,b=cmykBitmap(width,height,new Float32Array(width*height*4).fill(25),new Float32Array(width*height).fill(255),16),l=makeLayer('inks',b),g={...makeLayer('group',null,'group'),x:1,y:2,opacity:.5,children:[l]},state={id:'tiles',name:'tiles',width,height,colorMode:'cmyk',bitDepth:16,layers:[g],selectedId:l.id,revision:1},full=compositeCmyk(state),part=compositeCmyk(state,{x:256,y:256,width:14,height:4});for(let y=0;y<4;y++)for(let x=0;x<14;x++){assert.equal(part.cmyk[(y*14+x)*4],full.cmyk[((y+256)*width+x+256)*4]);assert.equal(part.data[(y*14+x)*4+3],full.data[((y+256)*width+x+256)*4+3]);}const d=doc(8),old=d.selected.bitmap,next=cmykBitmap(2,1,new Float32Array(8).fill(99),[255,255],8);d.replaceLayerPixels(d.selected.id,{...d.selected,bitmap:next},'partial',d.revision,{x:0,y:0,width:1,height:1});assert.deepEqual(d.selected.bitmap.cmyk.slice(4),old.cmyk.slice(4));const data=JSON.parse(serializeProject(d.state));data.version=10;assert.throws(()=>deserializeProject(JSON.stringify(data)),/版本/);const bytes=exportPsd(d.state).bytes,v=new DataView(bytes.buffer);let pos=26;pos+=4+v.getUint32(pos);pos+=4+v.getUint32(pos);v.setInt16(pos+8,Math.abs(v.getInt16(pos+8)));assert.throws(()=>importPsd(bytes,'extra-alpha.psd'),/第五通道/);d.dispose();});
