import test from 'node:test';import assert from 'node:assert/strict';
import {DiskPager,DISK_PAGE_SIZE,DiskPageMiss,diskPager,diskRefs,withDiskPages} from '../dist/diskPager.js';
import {spillBitmap,bitmapRegion,clearPagedPixelCache} from '../dist/pagedPixels.js';
import {bitmapRegionAsync,compositeRegionAsync} from '../dist/diskCompositor.js';
import {ImageDocument,makeLayer} from '../dist/document.js';
import {spillState,serializeDiskProject,deserializeDiskProject} from '../dist/diskImage.js';
import {RecoveryCodec,decodeRecovery} from '../dist/recoveryCodec.js';
const memory=()=>{const files=new Map();return {files,async read(k){return files.get(k)?.slice();},async write(k,b){files.set(k,b.slice());}};};
const storage=memory();diskPager.store.read=storage.read;diskPager.store.write=storage.write;
const noise=(size,seed=31)=>{const a=new Uint8Array(size);for(let i=0;i<size;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;a[i]=seed>>>24;}return a;};
test('async pager evicts and faults back exact pages, deduplicates concurrent reads and releases leases',async()=>{const store=memory(),p=new DiskPager(store,DISK_PAGE_SIZE,DISK_PAGE_SIZE*3),b=noise(DISK_PAGE_SIZE*4),ref=await p.write(b);assert.equal(p.stats().residentBytes,0);assert.deepEqual(await p.blob(ref),b);assert(p.stats().evictions>=3);assert(p.stats().residentBytes<=p.budget);p.clear();const first=ref.chunks[0],reads=p.stats().reads;await Promise.all([p.read(first),p.read(first),p.read(first)]);assert.equal(p.stats().reads,reads+1);const release=await p.lease(ref.chunks.slice(0,2));assert.equal(p.stats().pinnedBytes,DISK_PAGE_SIZE*2);await p.read(ref.chunks[3]);assert.equal(p.peek(first).length,DISK_PAGE_SIZE);release();release();assert.equal(p.stats().pinnedBytes,0);assert(p.stats().residentBytes<=p.budget);await assert.rejects(p.lease(ref.chunks),/工作集/);assert.equal(p.stats().pinnedBytes,0);});
test('page corruption, missing bytes, cancellation and failed writes do not produce valid references',async()=>{const store=memory(),p=new DiskPager(store,DISK_PAGE_SIZE),ref=await p.write(noise(32)),r=ref.chunks[0];store.files.get(r.key)[0]^=1;await assert.rejects(p.read(r),/校验/);store.files.clear();await assert.rejects(p.read(r),/缺失/);const abort=new AbortController();abort.abort();await assert.rejects(p.lease([r],abort.signal),e=>e.name==='AbortError');assert.equal(p.stats().pinnedBytes,0);store.write=async()=>{throw Error('quota');};await assert.rejects(p.write(noise(4)),/quota/);assert.equal(p.stats().writes,1);});
test('RGB8, RGB16, HDR and CMYK backing pages preserve exact regions without retained inline pixels',async()=>{for(const depth of [8,16,32]){const data=depth===8?new Uint8ClampedArray(noise(259*263*4)):Float32Array.from({length:259*263*4},(_,i)=>i%4===3?255:(i%97)/13*(depth===32?255:1));const b={width:259,height:263,data,...(depth!==8?{depth}:{})},expected=data.slice();await spillBitmap(b);assert.equal(b.pages.kind,'disk');assert.equal(Object.getOwnPropertyDescriptor(b,'data').enumerable,false);diskPager.clear();clearPagedPixelCache();assert.throws(()=>b.data,DiskPageMiss);const part=await bitmapRegionAsync(b,{x:250,y:250,width:9,height:13});for(let y=0;y<13;y++)assert.deepEqual(part.data.subarray(y*9*4,(y+1)*9*4),expected.subarray(((250+y)*259+250)*4,((250+y)*259+259)*4));assert.equal(diskPager.stats().pinnedBytes,0);}
 const b={width:17,height:19,data:new Uint8ClampedArray(17*19*4).fill(255),cmyk:Float32Array.from({length:17*19*4},(_,i)=>i%100)},ink=b.cmyk.slice();await spillBitmap(b);diskPager.clear();clearPagedPixelCache();const part=await bitmapRegionAsync(b,{x:0,y:0,width:17,height:19});assert.deepEqual(part.cmyk,ink);
});
test('failed spill leaves dense bitmap usable, not a half-written disk index',async()=>{const write=diskPager.store.write,b={width:513,height:3,data:new Uint8ClampedArray(noise(513*3*4))},before=b.data;let count=0;diskPager.store.write=async(...a)=>{if(++count===2)throw Error('quota');return write(...a);};try{await assert.rejects(spillBitmap(b),/quota/);assert.equal(b.pages,undefined);assert.equal(b.data,before);}finally{diskPager.store.write=write;}});
test('disk history, portable project and recovery reference pages without rehydrating all pixels',async()=>{const b={width:513,height:299,data:new Uint8ClampedArray(noise(513*299*4))},l=makeLayer('disk',b),d=new ImageDocument({id:'disk-doc',name:'disk',width:b.width,height:b.height,layers:[l],selectedId:l.id,revision:1});await spillState(d.state);const original=d.state;await withDiskPages(d.selected,()=>{const layer=d.selected,data=layer.bitmap.data.slice();data[4]=77;d.replaceLayerPixels(l.id,{...layer,bitmap:{...layer.bitmap,data}},'one pixel',d.revision,{x:1,y:0,width:1,height:1});});await spillState(d.state);const edited=d.state;diskPager.clear();clearPagedPixelCache();d.history.undo();assert.equal(d.state,original);assert.deepEqual((await compositeRegionAsync(d.state,{x:0,y:0,width:2,height:1})).data,(await bitmapRegionAsync(b,{x:0,y:0,width:2,height:1})).data);d.history.redo();assert.equal(d.state,edited);assert.equal((await bitmapRegionAsync(d.selected.bitmap,{x:1,y:0,width:1,height:1})).data[0],77);
 const saved=await serializeDiskProject(d.state);assert.equal(JSON.parse(saved).version,14);storage.files.clear();diskPager.clear();clearPagedPixelCache();const reopened=await deserializeDiskProject(saved);assert.equal((await bitmapRegionAsync(reopened.layers[0].bitmap,{x:1,y:0,width:1,height:1})).data[0],77);
 const encoded=await new RecoveryCodec().encode({version:2,activeId:d.identity.id,documents:[{state:reopened,dirty:true}]},new Set());assert.equal(encoded.session.version,14);assert([...encoded.chunks.values()].reduce((n,b)=>n+b.length,0)<4096);diskPager.clear();clearPagedPixelCache();const restored=await decodeRecovery(encoded.session,encoded.chunks);assert(diskRefs(restored).length>1);assert.equal(diskPager.stats().residentBytes,0);assert.equal((await bitmapRegionAsync(restored.documents[0].state.layers[0].bitmap,{x:1,y:0,width:1,height:1})).data[0],77);d.dispose();});

test('cold HDR and CMYK documents restore without materializing samples and render exact tiles',async()=>{for(const cmyk of [false,true]){const data=Float32Array.from({length:19*17*4},(_,i)=>i%4===3?255:33),b={width:19,height:17,depth:cmyk?16:32,data,...(cmyk?{cmyk:new Float32Array(data.length).fill(25)}:{})},l=makeLayer('precision',b),d=new ImageDocument({id:'precision-'+cmyk,name:'precision',width:19,height:17,bitDepth:b.depth,...(cmyk?{colorMode:'cmyk'}:{}),layers:[l],selectedId:l.id,revision:1}),before=await compositeRegionAsync(d.state,{x:0,y:0,width:19,height:17});await spillState(d.state);const cloned=structuredClone(d.state);diskPager.clear();clearPagedPixelCache();const restored=new ImageDocument(cloned);assert.equal(diskPager.stats().residentBytes,0);const after=await compositeRegionAsync(restored.state,{x:0,y:0,width:19,height:17});assert.deepEqual(after.data,before.data);if(cmyk)assert.deepEqual(after.cmyk,before.cmyk);d.dispose();restored.dispose();}});

test('metadata commands do not fault in an oversized disk document',async()=>{const {ImageWorkspace}=await import('../dist/workspace.js'),{pagedBitmap}=await import('../dist/pagedPixels.js');const w=new ImageWorkspace();await w.start();const layers=Array.from({length:10},(_,i)=>makeLayer('large '+i,pagedBitmap(2048,2048,{kind:'disk',tiles:Array.from({length:64},(_,j)=>({bytes:262144,chunks:[{key:'page:'+(i*64+j+1).toString(16).padStart(64,'0'),bytes:262144}]}))}))),d=new ImageDocument({id:'large-metadata',name:'large',width:128,height:128,layers,selectedId:layers[0].id,revision:1});w.add(d);const result=await w.api.execute({apiVersion:'1',requestId:'metadata-create',operation:'image.layer.create',documentId:d.identity.id,expectedRevision:d.revision,params:{name:'empty',kind:'pixel'}});assert.equal(result.status,'completed',JSON.stringify(result));assert.equal(d.state.layers.length,11);await w.dispose();});

test('cancelling an in-flight fault promptly releases pins without cancelling another reader',async()=>{const store=memory(),p=new DiskPager(store,DISK_PAGE_SIZE),b=await p.write(noise(128));let finish;const read=store.read;store.read=async key=>{await new Promise(resolve=>{finish=resolve;});return read(key);};const abort=new AbortController(),job=p.lease(b.chunks,abort.signal);await new Promise(resolve=>setTimeout(resolve,0));const peer=p.read(b.chunks[0]);abort.abort();await assert.rejects(job,e=>e.name==='AbortError');assert.equal(p.stats().pinnedBytes,0);finish();assert.equal((await peer).length,128);assert.equal(p.stats().reads,1);});

 test('dense smart sources share pageable backing across metadata history',async()=>{const source={width:9,height:7,data:new Uint8ClampedArray(noise(9*7*4))},expected=source.data.slice(),l=makeLayer('smart',{width:9,height:7,data:expected.slice()});l.content={type:'smart',sourceId:crypto.randomUUID(),name:'source',source,transform:{width:9,height:7,angle:0,flipX:false,flipY:false}};const d=new ImageDocument({id:'dense-smart',name:'smart',width:9,height:7,layers:[l],selectedId:l.id,revision:1}),first=d.state;d.rename('renamed');await spillState(d.state);assert.equal(first.layers[0].content.source.pages.kind,'disk');diskPager.clear();clearPagedPixelCache();assert.deepEqual((await bitmapRegionAsync(first.layers[0].content.source,{x:0,y:0,width:9,height:7})).data,expected);d.dispose();});

test('cold cross-layer cloning faults in source and target through the public dispatcher',async()=>{const {ImageWorkspace}=await import('../dist/workspace.js'),w=new ImageWorkspace();await w.start();const source=makeLayer('source',{width:4,height:4,data:new Uint8ClampedArray(64).fill(255)}),target=makeLayer('target',{width:4,height:4,data:new Uint8ClampedArray(64)}),d=new ImageDocument({id:'clone-disk',name:'clone',width:4,height:4,layers:[source,target],selectedId:target.id,revision:1});w.add(d);await spillState(d.state);const r=await w.api.execute({apiVersion:'1',requestId:'clone',operation:'image.retouch.stroke',documentId:d.identity.id,expectedRevision:d.revision,params:{layerId:target.id,sourceLayerId:source.id,kind:'clone',offset:{x:0,y:0},points:[{x:1.5,y:1.5}],size:1,hardness:1}});assert.equal(r.status,'completed',JSON.stringify(r));assert.deepEqual(Array.from((await bitmapRegionAsync(d.selected.bitmap,{x:1,y:1,width:1,height:1})).data),[255,255,255,255]);assert.equal(diskPager.stats().pinnedBytes,0);await w.dispose();});

test('render tolerates backing migrating to disk while waiting for its page lease',async()=>{const b={width:3,height:2,data:new Uint8ClampedArray(24).fill(199)},l=makeLayer('migrating',b),d=new ImageDocument({id:'migrating',name:'migrating',width:3,height:2,layers:[l],selectedId:l.id,revision:1}),lease=diskPager.lease;let migrated=false;diskPager.lease=async function(...args){const release=await lease.apply(this,args);if(!migrated){migrated=true;await spillBitmap(b);diskPager.clear();clearPagedPixelCache();}return release;};try{assert.deepEqual((await compositeRegionAsync(d.state,{x:0,y:0,width:3,height:2})).data,new Uint8ClampedArray(24).fill(199));assert.equal(diskPager.stats().pinnedBytes,0);}finally{diskPager.lease=lease;d.dispose();}});
