import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {runEditorBrowserScenario} from '../../scripts/editor-e2e/browserDriver.mjs';
const root=resolve(import.meta.dirname,'../..'),output=resolve(root,'imageEditor/artifacts/foundations');mkdirSync(output,{recursive:true});
const ready='Boolean(globalThis.haiyueEditor?.listOperations().some(e=>e.descriptor.id==="image.color.precision")&&document.querySelector("#app")?.getAttribute("aria-busy")==="false")';
const report=await runEditorBrowserScenario({root,route:'imageEditor/app-dist/index.html',downloadDirectory:output,failureScreenshotPath:resolve(output,'failure.png'),readinessExpression:ready,scenario:async driver=>{
 const {evaluate,cdp,nextPaint,waitFor}=driver;const click=async s=>{const e=`document.querySelector(${JSON.stringify(s)})`;await evaluate(`${e}.scrollIntoView({block:'center'})`);await nextPaint();await driver.click(e);};
 await evaluate(`globalThis.foundationId=null;globalThis.seq=0;globalThis.call=async(suffix,params={},docId=foundationId)=>{const d=haiyueEditor.listDocuments().documents.find(d=>d.identity.id===docId);const r=await haiyueEditor.execute({apiVersion:'1',requestId:'foundation-'+(++seq),operation:'image.'+suffix,params,...(d&&!['document.create','document.open','color.precision'].includes(suffix)?{documentId:docId,expectedRevision:d.revision}:{})});if(r.status!=='completed')throw Error(JSON.stringify(r));return r.value;};`);
 const call=(s,p={},id)=>evaluate(`call(${JSON.stringify(s)},${JSON.stringify(p)},${id?JSON.stringify(id):'foundationId'})`);
 const created=await call('document.create',{name:'第四批智能源验证',width:320,height:280});await evaluate(`foundationId=${JSON.stringify(created.documentId)}`);let q=await call('document.query'),id=q.selectedId;await call('pixels.fill',{layerId:id,color:'#284860'});await call('smart.convert',{layerId:id});
 await click('#smart-source-open');await waitFor(()=>evaluate(`haiyueEditor.listDocuments().activeId!==${JSON.stringify(created.documentId)}`),'source open');const sourceId=await evaluate('haiyueEditor.listDocuments().activeId');assert(sourceId&&sourceId!==created.documentId);
 let source=await call('document.query',{},sourceId);await call('pixels.fill',{layerId:source.selectedId,color:'#b45030'},sourceId);const added=await call('layer.create',{name:'第二层',kind:'pixel'},sourceId);source=await call('document.query',{},sourceId);assert.equal(source.layers.length,2);await call('pixels.fill',{layerId:source.selectedId,color:'#247bd0'},sourceId);await call('layer.update',{layerId:source.selectedId,patch:{opacity:.5}},sourceId);
 await click('#smart-source-apply');await waitFor(()=>evaluate(`haiyueEditor.listDocuments().activeId===${JSON.stringify(created.documentId)}`),'source apply');await nextPaint();q=await call('document.query');assert.equal(q.layers.find(l=>l.id===id).content.multilayer,true);const pixel=await evaluate("Array.from(document.querySelector('#image-canvas').getContext('2d').getImageData(0,0,1,1).data)");assert(pixel[3]===255);
 await call('history.undo');assert.equal((await call('document.query')).layers.find(l=>l.id===id).content.multilayer,false);await call('history.redo');
 const read=await call('smart.source.read',{layerId:id}),sourceProject=await evaluate(`JSON.parse(new TextDecoder().decode(haiyueEditor.readResource(${JSON.stringify(read.resourceId)})))`);assert.equal(sourceProject.document.layers.length,2);
 // Native PSD second-generation output and project bytes are saved for independent verification.
 const psd1=await call('document.export',{format:'psd'});const opened=await call('document.open',{format:'psd',resourceId:psd1.resourceId,name:'foundation.psd'});const psd2=await call('document.export',{format:'psd'},opened.documentId);
 for(const [name,ref] of [['generation1.psd',psd1],['generation2.psd',psd2]])writeFileSync(resolve(output,name),Buffer.from(await evaluate(`Array.from(haiyueEditor.readResource(${JSON.stringify(ref.resourceId)}))`)));
 await evaluate(`foundationId=${JSON.stringify(opened.documentId)}`);q=await call('document.query');assert(q.layers.some(l=>l.content?.multilayer));const project=await call('document.export',{format:'project'});writeFileSync(resolve(output,'multilayer.hyimage'),Buffer.from(await evaluate(`Array.from(haiyueEditor.readResource(${JSON.stringify(project.resourceId)}))`)));
 // Precision operation runs a real worker, preserves neighboring 16-bit values and supports cancellation.
 const precision=await evaluate(`(async()=>{const bytes=new Uint8Array(8),v=new DataView(bytes.buffer);[32767,32768,32769,43210].forEach((n,i)=>v.setUint16(i*2,n,true));const ref=haiyueEditor.putResource(bytes);const result=await call('color.precision',{resourceId:ref.resourceId,width:1,height:1,input:'rgba16le',output:'rgba16le',source:'srgb',target:'srgb'});const output=Array.from(haiyueEditor.readResource(result.resourceId));haiyueEditor.releaseResource(ref.resourceId);haiyueEditor.releaseResource(result.resourceId);return {input:Array.from(bytes),output};})()`);assert.deepEqual(precision.output,precision.input);
 const cancelled=await evaluate(`(async()=>{const ref=haiyueEditor.putResource(new Uint8Array(8));try{const p=haiyueEditor.execute({apiVersion:'1',requestId:'cancel-precision',operation:'image.color.precision',params:{resourceId:ref.resourceId,width:1,height:1,input:'rgba16le',output:'rgba16le',source:'srgb',target:'srgb'}});setTimeout(()=>haiyueEditor.cancel('cancel-precision'),0);return await p;}finally{haiyueEditor.releaseResource(ref.resourceId);}})()`);assert.equal(cancelled.status,'cancelled');
 await waitFor(()=>evaluate("document.querySelector('#recovery-status').textContent.includes('已存')"),'recovery');const time=await evaluate('performance.timeOrigin'),stop=cdp.on('Page.javascriptDialogOpening',()=>void cdp.call('Page.handleJavaScriptDialog',{accept:true}));await cdp.call('Page.reload');await waitFor(()=>evaluate(`performance.timeOrigin!==${time}&&${ready}`),'reload',30000);stop();
 const restored=await evaluate(`(async()=>{const d=haiyueEditor.listDocuments().documents.find(d=>d.identity.id===${JSON.stringify(opened.documentId)});return haiyueEditor.execute({apiVersion:'1',requestId:'restore-foundation',operation:'image.document.query',documentId:d.identity.id,params:{}});})()`);assert.equal(restored.status,'completed');assert(restored.value.layers.some(l=>l.content?.multilayer));assert.equal(await evaluate('haiyueEditor.listOperations().filter(o=>o.descriptor.id.startsWith("image.")).length'),68);driver.assertNoBrowserErrors();
 const shot=await cdp.call('Page.captureScreenshot',{format:'png'});writeFileSync(resolve(output,'source.png'),Buffer.from(shot.result.data,'base64'));
 return {status:'passed',cases:['UI-source-open-edit-apply-undo','multi-layer-native-PSD-two-generations','project-v9-recovery-v10','16-bit-real-worker-conversion','worker-cancellation','68-public-image-commands'],runner:{chrome:driver.chrome,angleBackend:driver.angleBackend,node:process.version,platform:process.platform,arch:process.arch},buildHash:JSON.parse(readFileSync(resolve(root,'imageEditor/app-dist/app-manifest.json'))).buildHash};
}});
const hash=b=>createHash('sha256').update(b).digest('hex');writeFileSync(resolve(output,'browser.json'),JSON.stringify({...report,schemaVersion:1,generatedAt:new Date().toISOString(),revision:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),dirty:true,sourceFingerprints:Object.fromEntries([...readdirSync(resolve(root,'imageEditor/src')).map(f=>'imageEditor/src/'+f),'imageEditor/test/foundations-browser.mjs','imageEditor/index.html','imageEditor/styles.css','imageEditor/rollup.config.js','imageEditor/app/descriptor.json'].map(f=>[f,hash(readFileSync(resolve(root,f)))]))},null,2));console.log(report);
