import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {ImageDocument,makeLayer} from '../dist/document.js';
import {exportPsd,importPsd} from '../dist/psdAdapter.js';
import {serializeProject,deserializeProject} from '../dist/projectFile.js';
import {RecoveryCodec,decodeRecovery} from '../dist/recoveryCodec.js';
import {withPixels,displayBitmap,convertDepth,exportPixelResource} from '../dist/pixelFormat.js';
import {compositeState} from '../dist/compositor.js';
import {initializeIcc,iccTransform,linearSrgbProfile,colorDisplay} from '../dist/iccEngine.js';
import {srgbProfileBytes,profileResource} from '../dist/colorManagement.js';
import {ImageWorkspace} from '../dist/workspace.js';import {operationClient} from '../../scripts/editor-e2e/operationWorkflow.mjs';
await initializeIcc(new Uint8Array(readFileSync(new URL('../../node_modules/lcms-wasm/dist/lcms.wasm',import.meta.url))));
const make=depth=>{const b=withPixels(2,1,new Float32Array(depth===16?[32767/257,32768/257,32769/257,12345/257,211,1,2,255]:[1020,.0255,-2,127.5,2550,255,0,255]),depth),l=makeLayer('precision',b);return new ImageDocument({id:crypto.randomUUID(),name:'precision',width:2,height:1,bitDepth:depth,layers:[l],selectedId:l.id,revision:1});};
for(const depth of [16,32]){
 test(`${depth}-bit project, recovery, history and composite retain fractional / HDR values`,async()=>{const d=make(depth),before=d.state;assert.deepEqual(deserializeProject(serializeProject(d.state)).layers[0].bitmap,d.selected.bitmap);const input={version:2,activeId:d.identity.id,documents:[{state:d.state,dirty:true}]},r=await new RecoveryCodec().encode(input,new Set());assert.deepEqual(await decodeRecovery(r.session,r.chunks),input);assert(compositeState(d.state).data instanceof Float32Array);d.setDisplay({exposure:-2,operator:'aces'});assert.equal(d.selected.bitmap,before.layers[0].bitmap);d.history.undo();assert.equal(d.state,before);assert.throws(()=>d.setDepth(8),/allowLoss/);d.setDepth(8,true);assert(d.selected.bitmap.data instanceof Uint8ClampedArray);d.history.undo();assert.deepEqual(d.selected.bitmap,before.layers[0].bitmap);d.dispose();});
 test(`${depth}-bit PSD survives two generations with native precision`,()=>{const d=make(depth);let state=d.state;for(let n=0;n<2;n++){const out=exportPsd(state);assert.equal(new DataView(out.bytes.buffer).getUint16(22),depth);const result=importPsd(out.bytes,'high.psd');assert(result.layered,result.blockers.join());state=result.layered;assert.equal(state.bitDepth,depth);for(let i=0;i<8;i++)assert(Math.abs(state.layers[0].bitmap.data[i]-d.selected.bitmap.data[i])<.002,`${i}: ${state.layers[0].bitmap.data[i]}`);}d.dispose();});
}
test('HDR display maps only previews and ICC float transform preserves alpha and highlights',()=>{const d=make(32),b=d.selected.bitmap,preview=displayBitmap(b,{exposure:-2,operator:'reinhard'});assert(preview.data instanceof Uint8ClampedArray);assert.equal(b.data[0],1020);const linear=linearSrgbProfile(),r=iccTransform(new Float32Array([4,.5,.0001]),linear,linear);assert(Math.abs(r.data[0]-4)<1e-5);const lab=iccTransform(new Float32Array([1,1,1]),'srgb','lab');assert(Math.abs(lab.data[0]-100)<.1);const inverse=iccTransform(lab.data,'lab','srgb');assert(inverse.data.every(v=>Math.abs(v-1)<.001));const view=colorDisplay(b,{...d.state,psdOrigin:{resources:profileResource(linear),sourceName:'x',flattened:false}});assert.equal(view.data[3],128);d.dispose();});
test('depth, HDR, ICC and resource commands share dispatch and undo contracts',async()=>{const w=new ImageWorkspace();await w.start();try{const d=make(32);w.add(d);const call=operationClient(w.platform,d.identity.id),id=d.selected.id,before=d.state;await call('image.hdr.exposure',{layerId:id,ev:1});assert.equal(d.selected.bitmap.data[0],2040);await call('image.history.undo');assert.equal(d.state,before);const copy=await call('image.pixels.copy',{layerId:id});assert.equal(copy.format,'rgba32fle');await call('image.pixels.paste',{resourceId:copy.resourceId,width:copy.width,height:copy.height,format:copy.format});assert.equal(d.selected.bitmap.data[0],1020);const profile=w.platform.resources.put(srgbProfileBytes());const info=await operationClient(w.platform)('image.icc.inspect',{profileId:profile.resourceId});assert.equal(info.space,'RGB');const checkpoint=d.state;await call('image.icc.proof',{intent:3,bpc:true});assert.equal(d.state.icc.intent,3);await call('image.history.undo');assert.equal(d.state,checkpoint);for(const r of [copy,profile])w.platform.resources.release(r.resourceId);}finally{await w.dispose();}});
import {filterBitmap} from '../dist/filters.js';import {resizeBitmap} from '../dist/resampling.js';import {adjustmentBitmap} from '../dist/nonDestructiveRender.js';import {convertSmart} from '../dist/smartObject.js';import {fillPixels,PixelStroke} from '../dist/pixelTools.js';import {maskStrokeState,maskFromStroke} from '../dist/maskTools.js';import {decodePsdPlane} from '../dist/highDepthPsd.js';import {deflateSync} from 'node:zlib';
for(const depth of [16,32])test(`${depth}-bit masks retain sub-byte coverage across PSD, project and recovery`,async()=>{const d=make(depth),mask={width:2,height:1,x:0,y:0,data:new Float32Array([127.501,80.125]),precision:'float32',disabled:false,defaultColor:0};d.setMask(d.selected.id,mask);const original=d.selected.mask;assert.deepEqual(deserializeProject(serializeProject(d.state)).layers[0].mask,original);const input={version:2,activeId:d.identity.id,documents:[{state:d.state,dirty:true}]},r=await new RecoveryCodec().encode(input,new Set());assert.deepEqual((await decodeRecovery(r.session,r.chunks)).documents[0].state.layers[0].mask,original);const result=importPsd(exportPsd(d.state).bytes,'mask.psd');assert(result.layered,result.blockers.join());assert(Math.abs(result.layered.layers[0].mask.data[0]-127.501)<.002);const state=maskStrokeState(d.state,d.selected.id),stroke=fillPixels(state,d.selected.id,[128,128,128]);assert.equal(maskFromStroke(d.selected,stroke).data[0],128);d.dispose();});
test('high precision resampling, Gaussian, identity curves and smart PSD do not quantize to bytes',()=>{const d=make(32),b=d.selected.bitmap;for(const out of [resizeBitmap(b,4,2,'bilinear'),filterBitmap(b,{kind:'gaussian',amount:1}),adjustmentBitmap(b,{type:'adjustment',filter:'curves',amount:100,curves:[{input:0,output:0},{input:255,output:255}]})]){assert(out.data instanceof Float32Array);assert(out.data.some((v,i)=>i%4!==3&&v>255));assert.equal(out.depth,32);}convertSmart(d,d.selected.id);const result=importPsd(exportPsd(d.state).bytes,'smart.psd');assert(result.layered,result.blockers.join());assert.deepEqual(result.layered.layers[0].content.source,d.selected.content.source);d.dispose();});
test('ZIP prediction decoding is endian correct and bounded; malformed inputs fail',()=>{const raw16=new Uint8Array([0x12,0x34,0,1,0,2]);assert.deepEqual(decodePsdPlane(deflateSync(raw16),3,3,1,16),new Uint8Array([0x12,0x34,0x12,0x35,0x12,0x37]));const raw32=new Uint8Array(8),v=new DataView(raw32.buffer);v.setFloat32(0,4);v.setFloat32(4,.5);const shuffled=new Uint8Array(8);for(let c=0;c<4;c++)for(let x=0;x<2;x++)shuffled[c*2+x]=raw32[x*4+c];for(let i=7;i>0;i--)shuffled[i]=(shuffled[i]-shuffled[i-1])&255;assert.deepEqual(decodePsdPlane(deflateSync(shuffled),3,2,1,32),raw32);assert.throws(()=>decodePsdPlane(deflateSync(new Uint8Array(1000)),2,1,1,32),/预算/);assert.throws(()=>decodePsdPlane(new Uint8Array([0,1,127]),1,1,1,16));});
test('ICC settings and profiles roundtrip, preserve source bytes and avoid side effects on failed conversions',async()=>{const d=make(16),profile=srgbProfileBytes();d.commitIcc(profileResource(profile),{intent:3,bpc:true,proofIntent:1,gamutWarning:false,proofProfile:profile,monitorProfile:profile});const before=d.state;assert.deepEqual(deserializeProject(serializeProject(before)).icc,before.icc);const input={version:2,activeId:d.identity.id,documents:[{state:before,dirty:true}]},r=await new RecoveryCodec().encode(input,new Set());assert.deepEqual((await decodeRecovery(r.session,r.chunks)).documents[0].state.icc,before.icc);d.setDepth(32);assert(d.selected.bitmap.data[0]<100);d.history.undo();assert.equal(d.state,before);assert.throws(()=>iccTransform(new Float32Array([NaN,0,0]),'srgb','lab'),/无效/);assert.throws(()=>iccTransform(new Float32Array([1,0,0]),new Uint8Array(132),'srgb'),/ICC/);d.dispose();});
