import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {ImageDocument,makeLayer} from '../dist/document.js';import {compositeDamage,compositeState,compositeRegion,forEachCompositeTile} from '../dist/compositor.js';import {initializeIcc,iccTransform,iccTransformStats,withIccTransforms,colorDisplay} from '../dist/iccEngine.js';import {builtinIcc,withDocumentProfile,applyIccPolicy} from '../dist/iccWorkflow.js';import {sampleBitmap,sampleColor} from '../dist/dailyEditing.js';import {bitmapHistogram,documentHistogram} from '../dist/histogram.js';import {PixelStroke,replacePixel} from '../dist/pixelTools.js';import {cmykBitmap} from '../dist/cmyk.js';
await initializeIcc(new Uint8Array(readFileSync(new URL('../../node_modules/lcms-wasm/dist/lcms.wasm',import.meta.url))));
const bitmap=(width,height,depth=8)=>({width,height,...(depth===8?{}:{depth}),data:(depth===8?Uint8ClampedArray:Float32Array).from({length:width*height*4},(_,i)=>i%251)});
const state=(width=530,height=280,depth=8)=>{const l=makeLayer('base',bitmap(width,height,depth));return {id:'test',name:'test',width,height,bitDepth:depth,revision:1,selectedId:l.id,layers:[l]};};
test('tiled ICC reuses identical profile contents, isolates settings and releases on exception',()=>{
 const source=builtinIcc('display-p3'),target=builtinIcc('srgb'),input=new Float32Array([.2,.6,.1]),expected=iccTransform(input,source,target),before=iccTransformStats();
 withIccTransforms(()=>{for(let i=0;i<12;i++)assert.deepEqual(iccTransform(input,source.slice(),target.slice()),expected);withIccTransforms(()=>iccTransform(input,source,target,{intent:3}));assert.equal(iccTransformStats().live,2);});
 assert.equal(iccTransformStats().created-before.created,2);assert.equal(iccTransformStats().reused-before.reused,11);assert.equal(iccTransformStats().live,0);
 assert.throws(()=>withIccTransforms(()=>{iccTransform(input,source,target);iccTransform(new Float32Array([NaN,0,0]),source,target);}));assert.equal(iccTransformStats().live,0);
 withIccTransforms(()=>{for(let i=0;i<12;i++){const p=source.slice();p[127]=i;iccTransform(input,p,target);assert(iccTransformStats().live<=8);}});assert.equal(iccTransformStats().live,0);
});
test('one ICC transform per tile traversal with pixel-identical output',()=>{
 const s=withDocumentProfile(state(),builtinIcc('display-p3')),expected=colorDisplay(compositeState(s),s),actual=new Uint8ClampedArray(expected.data.length),before=iccTransformStats();let tiles=0;
 forEachCompositeTile(s,(b,r)=>{tiles++;const v=colorDisplay(b,s);for(let y=0;y<r.height;y++)actual.set(v.data.subarray(y*r.width*4,(y+1)*r.width*4),((r.y+y)*s.width+r.x)*4);});
 assert(tiles>1);assert.deepEqual(actual,expected.data);assert.equal(iccTransformStats().created-before.created,1);assert.equal(iccTransformStats().reused-before.reused,tiles-1);assert.equal(iccTransformStats().live,0);
});
test('incremental damage includes nested offsets and styles and reconstructs full RGB8/16/32 output',()=>{
 for(const depth of [8,16,32]){let s=state(530,280,depth),l={...s.layers[0],x:-9,y:3,styles:{enabled:true,stroke:{color:'#0044ff',opacity:.8,size:3},shadow:{color:'#080808',opacity:.7,dx:9,dy:-8,blur:5}}};const g={...makeLayer('group',null,'group'),x:13,y:-6,children:[l]};s={...s,layers:[g],selectedId:l.id};const original=compositeState(s),stroke=new PixelStroke(s,l.id,14,.8,[255,10,90]);stroke.point({x:250,y:130});const next={...s,layers:replacePixel(s.layers,l.id,stroke.layer)},damage=compositeDamage(next,l.id,stroke.takeDirty());assert(damage.width*damage.height<s.width*s.height/10);const result=original.data.slice();forEachCompositeTile(next,(b,r)=>{for(let y=0;y<r.height;y++)result.set(b.data.subarray(y*r.width*4,(y+1)*r.width*4),((r.y+y)*s.width+r.x)*4);},32,damage);assert.deepEqual(result,compositeState(next).data);}
});
test('damage falls back for non-local smart filters and clips off-canvas updates',()=>{const s=state(),id=s.layers[0].id;assert.deepEqual(compositeDamage(s,id,{x:-30,y:-20,width:10,height:10}),{x:0,y:0,width:0,height:0});assert.equal(compositeDamage({...s,layers:[{...s.layers[0],smartFilters:[{enabled:true}]}]},id,{x:1,y:1,width:2,height:2}),undefined);assert.throws(()=>forEachCompositeTile(s,()=>{},256,{x:-1,y:0,width:3,height:3}));});
test('streamed histogram and point sampling match full composite with soft selection and nested layer offsets',()=>{
 const s=state(),l={...makeLayer('offset',bitmap(290,210,16)),x:210,y:45,opacity:.65},g={...makeLayer('group',null,'group'),x:-20,y:10,children:[l]};s.layers.push(g);s.selection={x:180,y:70,width:290,height:190,mask:Uint8Array.from({length:290*190},(_,i)=>i%256)};
 for(const id of [undefined,l.id,g.id])for(const selected of [false,true]){const expected=bitmapHistogram(sampleBitmap(s,id),selected?s.selection:null),actual=documentHistogram(s,id,selected);for(const k of Object.keys(expected)){if(Array.isArray(expected[k]))expected[k].forEach((v,i)=>assert(Math.abs(v-actual[k][i])<1e-7));else assert(Math.abs(expected[k]-actual[k])<1e-5,k);}}const full=sampleBitmap(s);for(const [x,y] of [[0,0],[255,255],[529,279]])assert.deepEqual(sampleColor(s,x,y),Array.from(full.data.subarray((y*s.width+x)*4,(y*s.width+x)*4+4)));
});
test('incremental CMYK tiles preserve ink and alpha across non-aligned boundaries',()=>{const w=530,h=280,b=cmykBitmap(w,h,new Float32Array(w*h*4).fill(25),new Float32Array(w*h).fill(200),16),l=makeLayer('ink',b),s={...state(w,h,16),colorMode:'cmyk',layers:[l],selectedId:l.id};const region={x:241,y:117,width:64,height:50},reference=compositeRegion(s,region);let pixels=0;forEachCompositeTile(s,(tile,r)=>{pixels+=r.width*r.height;for(let y=0;y<r.height;y++)for(let x=0;x<r.width;x++){const a=(y*r.width+x)*4,e=((y+r.y-region.y)*region.width+x+r.x-region.x)*4;assert.deepEqual(tile.cmyk.subarray(a,a+4),reference.cmyk.subarray(e,e+4));assert.deepEqual(tile.data.subarray(a,a+4),reference.data.subarray(e,e+4));}},32,region);assert.equal(pixels,region.width*region.height);});

test('committed damage supports reconstructed undo, native inks and no-op metadata; geometry/color changes repaint fully',async()=>{
 const {documentDamage}=await import('../dist/renderDamage.js');
 for(const depth of [8,16,32]){const a=state(530,280,depth),b={...a,layers:[{...a.layers[0],bitmap:{...a.layers[0].bitmap,data:a.layers[0].bitmap.data.slice()}}]};b.layers[0].bitmap.data[(101*530+277)*4]=222;assert.deepEqual(documentDamage(a,b),{x:277,y:101,width:1,height:1});assert.deepEqual(documentDamage(b,a),{x:277,y:101,width:1,height:1});assert.deepEqual(documentDamage(a,{...a,revision:2,name:'renamed'}),{x:0,y:0,width:0,height:0});assert.equal(documentDamage(a,{...b,icc:{intent:1}}),undefined);assert.equal(documentDamage(a,{...b,layers:[{...b.layers[0],x:1}]}),undefined);}
 const a=state(10,10,16);a.layers[0].bitmap.cmyk=new Float32Array(400);const b={...a,layers:[{...a.layers[0],bitmap:{...a.layers[0].bitmap,cmyk:a.layers[0].bitmap.cmyk.slice()}}]};b.layers[0].bitmap.cmyk[16]=40;assert.deepEqual(documentDamage(a,b),{x:4,y:0,width:1,height:1});
});

test('real frozen ICC document history preserves local damage through commit undo and redo',async()=>{
 const {documentDamage}=await import('../dist/renderDamage.js'),d=new ImageDocument(state());d.commitMode(await applyIccPolicy(d.state,'assign',builtinIcc('display-p3')));const before=d.state,stroke=new PixelStroke(before,d.selected.id,12,.8,[200,40,80]);stroke.point({x:270,y:100});d.replaceLayerPixels(d.selected.id,stroke.layer,'local',d.revision,stroke.changedBounds);const after=d.state,r=documentDamage(before,after);assert(r&&r.width*r.height<1000);d.history.undo();assert.deepEqual(documentDamage(after,d.state),r);d.history.redo();assert.deepEqual(documentDamage(before,d.state),r);d.dispose();
});
