import test from 'node:test';
import assert from 'node:assert/strict';
import { readPsd,writePsdUint8Array } from 'ag-psd';
import { ImageDocument,makeLayer,layerLocked } from '../dist/document.js';
import { effectiveLocks } from '../dist/layerLocks.js';
import { fillPixels,PixelStroke,replacePixel } from '../dist/pixelTools.js';
import { gradientPixels,moveLayers,alignLayers } from '../dist/dailyEditing.js';
import { transformedLayer,commitTransform } from '../dist/freeTransform.js';
import { filterLayer } from '../dist/filters.js';
import { importPsd,exportPsd } from '../dist/psdAdapter.js';
import { importPagedPsd } from '../dist/pagedPsd.js';
import { serializeProject,deserializeProject } from '../dist/projectFile.js';
import { packBitmap } from '../dist/pagedPixels.js';
import { fillCmyk,CmykStroke } from '../dist/cmykEditing.js';
import { cmykBitmap } from '../dist/cmyk.js';
const bitmap=(depth=8)=>({width:2,height:2,depth,data:new (depth===8?Uint8ClampedArray:Float32Array)([20,50,90,128,1,2,3,0,250,100,40,255,60,90,130,1])});
function doc(depth=8,paged=false){const d=ImageDocument.create('locks',8,8);if(depth!==8)d.setDepth(depth);d.addLayer({...makeLayer('L1',paged?packBitmap(bitmap()):bitmap(depth)),x:2,y:3},false);return d;}
const alpha=b=>Array.from(b.data).filter((_,i)=>i%4===3);
test('alpha lock protects fractional alpha, hidden RGB, bounds and history across fill, gradient, filters and raw API writes',()=>{
 for(const depth of [8,16,32])for(const paged of depth===8?[false,true]:[false]){const d=doc(depth,paged),id=d.selected.id;d.updateLayer(id,{locks:{transparency:true}});const original=d.selected.bitmap,originalAlpha=alpha(original);
 const paint=[()=>fillPixels(d.state,id,[255,0,0],.5),()=>gradientPixels(d.state,id,{x:0,y:0},{x:8,y:8},[0,0,0],[255,255,255],'linear'),()=>filterLayer(d.state,id,{kind:'gaussian',amount:1}),()=>({...d.selected,bitmap:{...bitmap(depth),data:new (depth===8?Uint8ClampedArray:Float32Array)(16).fill(255)}})];
 for(const run of paint){const before=d.state;d.replaceLayerPixels(id,run(),'paint');assert.deepEqual(alpha(d.selected.bitmap),originalAlpha);assert.deepEqual(Array.from(d.selected.bitmap.data.slice(4,8)),[1,2,3,0]);assert.deepEqual([d.selected.x,d.selected.y,d.selected.bitmap.width,d.selected.bitmap.height],[2,3,2,2]);d.history.undo();assert.equal(d.state,before);d.history.redo();}
 const before=d.state;d.replaceLayerPixels(id,fillPixels(d.state,id,null),'erase');assert.deepEqual(alpha(d.selected.bitmap),originalAlpha);d.history.undo();assert.equal(d.state,before);
 moveLayers(d,[id],1,1);assert.equal(d.selected.x,3);assert.equal(d.selected.y,4);d.dispose();}
});
test('alpha-locked brush blends color by coverage while leaving alpha unchanged in its preview',()=>{const d=doc(),id=d.selected.id;d.updateLayer(id,{locks:{transparency:true}});const stroke=new PixelStroke(d.state,id,2,.5,[220,50,90]);stroke.point({x:2.5,y:3.5});const i=(3*stroke.layer.bitmap.width+2)*4;assert.equal(stroke.layer.bitmap.data[i],120);assert.equal(stroke.layer.bitmap.data[i+3],128);const eraser=new PixelStroke(d.state,id,2,1,[0,0,0],true);eraser.point({x:2.5,y:3.5});assert.equal(eraser.changed,false);d.dispose();});
test('position lock permits paint, blocks move, align and transforms, and is inherited by descendants',()=>{const d=doc(),id=d.selected.id;d.updateLayer(id,{locks:{position:true}});d.replaceLayerPixels(id,fillPixels(d.state,id,[40,60,80]),'fill');d.history.undo();assert.throws(()=>moveLayers(d,[id],1,0),/位置/);assert.throws(()=>alignLayers(d,[id],'right','canvas'),/位置/);assert.throws(()=>transformedLayer(d.state,id,{width:3,height:3,angle:0,dx:0,dy:0}),/锁定/);assert.throws(()=>d.updateLayer(id,{x:1}),/位置/);d.dispose();
 const g=ImageDocument.create('groups',8,8);g.addLayer(makeLayer('g',null,'group'));const parent=g.selected.id;g.addLayer(makeLayer('child',bitmap()));const child=g.selected.id;g.updateLayer(parent,{locks:{position:true}});assert(layerLocked(g.state.layers,child,'position'));assert.throws(()=>g.updateLayer(child,{x:2}),/位置/);g.updateLayer(parent,{locks:{pixels:true}});assert.throws(()=>fillPixels(g.state,child,[0,0,0]),/锁定/);g.dispose();});
test('pixel lock allows positioning and transform but blocks pixel replacement including bulk commits',()=>{const d=doc(),id=d.selected.id;d.updateLayer(id,{locks:{pixels:true}});moveLayers(d,[id],1,0);assert.throws(()=>fillPixels(d.state,id,[0,0,0]),/锁定/);const next={...d.selected,bitmap:bitmap()};assert.throws(()=>d.replaceLayerPixels(id,next,'bypass'),/像素/);assert.throws(()=>d.commitLayers('bulk',replacePixel(d.state.layers,id,next),[]),/像素/);commitTransform(d,transformedLayer(d.state,id,{width:3,height:3,angle:0,dx:1,dy:0}));assert.equal(d.selected.bitmap.width,3);d.dispose();});
test('moving a group cannot bypass a descendant position lock; unrelated locks do not block transforms',()=>{const d=doc(),id=d.selected.id;d.updateLayer(id,{locks:{position:true}});d.addLayer(makeLayer('other',bitmap()),false);const other=d.selected.id;commitTransform(d,transformedLayer(d.state,other,{width:3,height:3,angle:0,dx:1,dy:0}));d.addLayer(makeLayer('group',null,'group'));const group=d.selected.id;d.addLayer(makeLayer('child',bitmap()));d.updateLayer(d.selected.id,{locks:{position:true}});assert.throws(()=>moveLayers(d,[group],2,0),/位置/);d.dispose();});
test('PSD header alpha lock and protection bits roundtrip through both dense and paged import',()=>{for(const input of [{transparencyProtected:true},{protected:{composite:true}},{protected:{position:true}},{protected:{transparency:true,position:true}},{protected:{transparency:true,composite:true,position:true}},{protected:{artboards:true}}]){const bytes=writePsdUint8Array({width:8,height:8,children:[{name:'L1',imageData:bitmap(),...input}]},{noBackground:true});const dense=importPsd(bytes,'locks.psd');assert(dense.layered,dense.blockers.join());assert(!dense.warnings.some(w=>w.includes('部分锁定')));for(const state of [dense.layered,importPagedPsd(bytes,'locks.psd',new Uint8Array())]){const before=effectiveLocks(state.layers,state.layers[0].id),out=exportPsd(state),after=importPsd(out.bytes,'again.psd');assert(after.layered,after.blockers.join());assert.deepEqual(effectiveLocks(after.layered.layers,after.layered.layers[0].id),before);const raw=readPsd(out.bytes,{skipLayerImageData:true,skipCompositeImageData:true,skipThumbnail:true}).children[0];if(input.transparencyProtected){assert.equal(raw.transparencyProtected,true);assert(!raw.protected?.composite);assert(!raw.protected?.position);}const restored=deserializeProject(serializeProject(state));assert.deepEqual(restored.layers[0].locks,state.layers[0].locks);}}});
test('CMYK alpha lock preserves alpha and hidden inks for fills and pressure strokes',()=>{const d=ImageDocument.create('inks',8,8),b=cmykBitmap(2,2,new Float32Array([10,20,30,40,1,2,3,4,20,30,40,50,40,30,20,10]),new Float32Array([128,0,255,1]),8);d.commitMode({...d.state,colorMode:'cmyk',layers:[{...makeLayer('ink',b),locks:{transparency:true}}],selectedId:null});const id=d.state.layers[0].id;d.select(id);const original=alpha(d.selected.bitmap),hidden=Array.from(d.selected.bitmap.cmyk.slice(4,8));for(const draw of [()=>fillCmyk(d.state,id,{ink:[100,0,0,0]}),()=>{const s=new CmykStroke(d.state,id,2,{ink:[0,100,0,0]});s.point({x:.5,y:.5});assert(s.changed);return s.layer;}]){d.replaceLayerPixels(id,draw(),'ink');assert.deepEqual(alpha(d.selected.bitmap),original);assert.deepEqual(Array.from(d.selected.bitmap.cmyk.slice(4,8)),hidden);}d.dispose();});
test('lock validation and undo are atomic; caller mutation cannot change stored locks',()=>{const d=doc(),id=d.selected.id,locks={pixels:true};d.updateLayer(id,{locks});locks.pixels=false;assert.equal(d.selected.locks.pixels,true);const before=d.state;assert.throws(()=>d.updateLayer(id,{locks:{position:'yes'}}),/锁定/);assert.equal(d.state,before);d.history.undo();assert.equal(d.selected.locks,undefined);d.history.redo();assert.equal(d.selected.locks.pixels,true);d.dispose();});
test('public API merges lock patches, queries inherited flags and rejects writes without changing history',async()=>{const {ImageWorkspace}=await import('../dist/workspace.js'),{operationClient}=await import('../../scripts/editor-e2e/operationWorkflow.mjs'),w=new ImageWorkspace();await w.start();try{const d=doc();w.add(d);const call=operationClient(w.platform,d.identity.id),id=d.selected.id;await call('image.layer.update',{layerId:id,patch:{locks:{transparency:true}}});await call('image.layer.update',{layerId:id,patch:{locks:{pixels:true}}});const q=await call('image.document.query'),l=q.layers.find(l=>l.id===id);assert(l.locks.transparency&&l.locks.pixels&&l.effectiveLocks.pixels);const before=d.state;await assert.rejects(()=>call('image.pixels.fill',{layerId:id,color:'#ff0000'}));assert.equal(d.state,before);await call('image.history.undo');await call('image.pixels.fill',{layerId:id,color:'#ff0000'});assert.deepEqual(alpha(d.selected.bitmap),[128,0,255,1]);}finally{await w.dispose();}});
test('binary recovery retains partial locks for dense and paged documents',async()=>{const {RecoveryCodec,decodeRecovery}=await import('../dist/recoveryCodec.js');for(const paged of [false,true]){const d=doc(8,paged);d.updateLayer(d.selected.id,{locks:{transparency:true,position:true}});const encoded=await new RecoveryCodec().encode({version:2,activeId:d.identity.id,documents:[{state:d.state,dirty:true}]},new Set());const restored=await decodeRecovery(encoded.session,encoded.chunks);assert.deepEqual(restored.documents[0].state.layers.at(-1).locks,d.selected.locks);d.dispose();}});
test('action API validates each step and commits an alpha-locked transform without reclipping it',async()=>{const {ImageWorkspace}=await import('../dist/workspace.js'),{operationClient}=await import('../../scripts/editor-e2e/operationWorkflow.mjs'),w=new ImageWorkspace();await w.start();try{const d=doc();w.add(d);const call=operationClient(w.platform,d.identity.id),id=d.selected.id;d.updateLayer(id,{locks:{transparency:true}});const action={id:'transform-alpha',name:'transform',parameters:[],steps:[{operation:'pixels.fill',params:{layerId:id,color:'#ff0000'}},{operation:'layer.transform',params:{layerId:id,width:4,height:4,angle:0,dx:0,dy:0}}]};await call('image.action.save',{action});const before=d.state;await call('image.action.run',{id:action.id});assert.equal(d.selected.bitmap.width,4);await call('image.history.undo');assert.equal(d.state,before);d.updateLayer(id,{locks:{position:true}});const locked=d.state;await assert.rejects(()=>call('image.action.run',{id:action.id}));assert.equal(d.state,locked);}finally{await w.dispose();}});
test('image pixel locks leave mask painting available; alpha lock prevents destructive mask application',async()=>{const {maskStrokeState,maskFromStroke}=await import('../dist/maskTools.js'),d=doc(),id=d.selected.id;d.setMask(id,{width:2,height:2,x:0,y:0,disabled:false,defaultColor:255,data:new Uint8Array(4).fill(255)});d.updateLayer(id,{locks:{pixels:true,transparency:true}});const result=fillPixels(maskStrokeState(d.state,id),id,[0,0,0]);d.setMask(id,maskFromStroke(d.selected,result));assert.equal(d.selected.mask.data[0],0);assert.throws(()=>d.applySelectedMask(),/锁定/);d.dispose();});
