import test from 'node:test';import assert from 'node:assert/strict';
import {writePsdUint8Array} from 'ag-psd';
import {projectiveBitmap,validateQuad} from '../dist/projective.js';
import {importPsd,exportPsd} from '../dist/psdAdapter.js';
import {readPsdMetadata} from '../dist/highDepthPsd.js';
import {ImageDocument,allLayers} from '../dist/document.js';
import {replaceSmart} from '../dist/smartObject.js';
import {serializeProject,deserializeProject} from '../dist/projectFile.js';
const image=(width=8,height=8,rgba=[40,80,120,255])=>({width,height,data:Uint8ClampedArray.from({length:width*height*4},(_,i)=>rgba[i%4])});
const quad=[1,1,7,2,6,7,0,6],vector={paths:[{open:false,operation:'combine',fillRule:'even-odd',knots:Array.from({length:4},(_,i)=>({linked:true,points:[quad[i*2],quad[i*2+1],quad[i*2],quad[i*2+1],quad[i*2],quad[i*2+1]]}))}],invert:false,notLink:false,disable:false,fillStartsWithAllPixels:false};
function fixture(){const source=writePsdUint8Array({width:8,height:8,imageData:image(),children:[{name:'source',imageData:image()}]},{noBackground:true}),id=crypto.randomUUID();return writePsdUint8Array({width:8,height:8,imageData:image(),linkedFiles:[{id,name:'source.psd',type:'8BPS',data:source}],children:[{name:'group',blendMode:'pass through',effects:{scale:1,bevel:{enabled:false,present:false}},children:[{name:'placed',imageData:image(),placedLayer:{id,type:'raster',width:8,height:8,transform:[0,0,8,0,8,8,0,8],nonAffineTransform:quad,warp:{style:'none'}},vectorMask:vector,mask:{left:0,top:0,defaultColor:0,fromVectorData:true,imageData:image(8,8,[255,255,255,255])}}]},{name:'text',imageData:image(),text:{text:'Hello',transform:[1.1,0,0,1.2,2.25,6.5],shapeType:'point',style:{font:{name:'ArialMT'},fontSize:12.25,tracking:-20,leading:13.5,autoLeading:false,fillColor:{r:0,g:0,b:0}}}}]},{noBackground:true});}
test('projective sampling preserves identity, float highlights and transparent outside; invalid quads reject',()=>{for(const depth of [8,32]){const b=depth===8?image():{...image(),depth:32,data:Float32Array.from(image().data,(v,i)=>i%4===3?v:v*9)};assert.deepEqual(projectiveBitmap(b,8,8,[0,0,8,0,8,8,0,8]).data,b.data);const mapped=projectiveBitmap(b,8,8,quad);assert.equal(mapped.data[3],0);assert.equal(mapped.data[(4*8+4)*4+3],255);assert.equal(mapped.data[(4*8+4)*4],b.data[0]);}for(const q of [[0,0,8,8,8,0,0,8],[0,0,0,0,8,8,0,8],[0,0,Infinity,0,8,8,0,8]])assert.throws(()=>validateQuad(q));});
test('scaled text and perspective smart object with vector mask preserve native descriptors and portable state',()=>{const bytes=fixture(),r=importPsd(bytes,'mockup.psd');assert(r.layered,r.blockers.join('\n'));const layers=allLayers(r.layered.layers),smart=layers.find(l=>l.content?.type==='smart'),text=layers.find(l=>l.content?.type==='text');assert.deepEqual(smart.content.transform.quad,quad);assert(smart.mask.vector);assert.equal(text.content.size,12.25);assert.equal(text.content.layout.scaleX,1.1);assert.equal(text.content.layout.tracking,-20);const restored=deserializeProject(serializeProject(r.layered)),out=exportPsd(restored).bytes,old=readPsdMetadata(bytes),next=readPsdMetadata(out);assert.deepEqual(next.children[0].children[0].placedLayer,old.children[0].children[0].placedLayer);assert.deepEqual(next.children[0].children[0].vectorMask,old.children[0].children[0].vectorMask);assert.deepEqual(next.children[1].text,old.children[1].text);assert.deepEqual(next.linkedFiles[0].data,old.linkedFiles[0].data);assert(importPsd(out,'again.psd').layered);});
test('source replacement retains perspective and mask; undo restores native data; painted mask drops stale vector',()=>{const r=importPsd(fixture(),'mockup.psd'),d=new ImageDocument(r.layered),l=allLayers(d.state.layers).find(l=>l.content?.type==='smart'),before=d.state;replaceSmart(d,l.id,image(4,4,[255,0,0,255]),'red');const edited=allLayers(d.state.layers).find(x=>x.id===l.id);assert.deepEqual(edited.content.transform.quad,quad);assert(edited.mask.vector);assert.equal(edited.bitmap.data[(4*8+4)*4],255);assert.equal(edited.bitmap.data[(4*8+4)*4+1],0);const result=importPsd(exportPsd(d.state).bytes,'changed.psd');assert(result.layered,result.blockers.join('\n'));assert.deepEqual(allLayers(result.layered.layers).find(x=>x.content?.type==='smart').content.transform.quad,quad);d.history.undo();assert.equal(d.state,before);d.setMask(l.id,{...l.mask,data:l.mask.data.map(v=>255-v)});assert.equal(allLayers(d.state.layers).find(x=>x.id===l.id).mask.vector,undefined);assert(!readPsdMetadata(exportPsd(d.state).bytes).children[0].children[0].vectorMask);d.history.undo();assert(allLayers(d.state.layers).find(x=>x.id===l.id).mask.vector);d.dispose();});

test('vector mask also survives a dense project without a native PSD archive',()=>{const d=ImageDocument.create('dense vector',8,8,true),mask={width:8,height:8,x:0,y:0,data:new Uint8Array(64).fill(255),defaultColor:0,disabled:false,vector};d.setMask(d.selected.id,mask);assert.deepEqual(deserializeProject(serializeProject(d.state)).layers[0].mask.vector,vector);d.dispose();});
