import test from 'node:test';import assert from 'node:assert/strict';
import {writePsdUint8Array,readPsd} from 'ag-psd';
import {pagedBitmap,packBitmap,bitmapRegion,hydratePixels,clearPagedPixelCache,pagedPixelStats,PAGE_CACHE_BYTES} from '../dist/pagedPixels.js';
import {ImageDocument,makeLayer,validateState} from '../dist/document.js';
import {serializeProject,deserializeProject} from '../dist/projectFile.js';
import {RecoveryCodec,decodeRecovery} from '../dist/recoveryCodec.js';
import {compositeState,compositeReference,forEachCompositeTile} from '../dist/compositor.js';
import {encodePixelArchive,decodePixelArchive} from '../dist/pixelArchive.js';
import {importPagedPsd} from '../dist/pagedPsd.js';
import {importPsd,exportPsd} from '../dist/psdAdapter.js';
const bitmap=(w,h)=>({width:w,height:h,data:Uint8ClampedArray.from({length:w*h*4},(_,i)=>i%4===3?((i/4|0)%7?255:87):(i*17+(i/11|0))%256)});
function source(w=513,h=299){const b=bitmap(w,h),bytes=writePsdUint8Array({width:w,height:h,children:[{id:17,name:'pixels',imageData:b}],imageData:b},{noBackground:true,compress:false}),raw=readPsd(bytes,{useRawData:true,skipCompositeImageData:true});return {b,bytes,page:pagedBitmap(w,h,{kind:'psd-rgb8',channels:raw.children[0].rawData.channels})};}
function documentOf(page){const l=makeLayer('paged',page);return new ImageDocument({id:'paged-doc',name:'paged',width:page.width,height:page.height,layers:[l],selectedId:l.id,revision:1});}

test('RLE regions cross tile boundaries without decoding full layers; cache obeys its bound',()=>{clearPagedPixelCache();const {b,page}=source();assert.equal(pagedPixelStats().materializations,0);for(const r of [[0,0,19,11],[250,249,263,50],[500,290,13,9]]){const actual=bitmapRegion(page,...r),expected=bitmapRegion(b,...r);assert.deepEqual(actual.data,expected.data);}assert.equal(pagedPixelStats().materializations,0);assert(pagedPixelStats().tileBytes<=PAGE_CACHE_BYTES);assert.deepEqual(page.data,b.data);});

test('worker cloning carries compressed pages, restores accessors, and preserves exact samples',()=>{const {b,page}=source(32,19);clearPagedPixelCache();const cloned=structuredClone({page});assert.equal(cloned.page.data,undefined);assert.equal(pagedPixelStats().materializations,0);hydratePixels(cloned);assert.deepEqual(cloned.page.data,b.data);});

test('partial edits retain immutable override tiles, undo/redo, and a compact project',async()=>{const {b,page}=source(),d=documentOf(page),original=d.state,data=b.data.slice();data[(260*513+260)*4]=177;d.replaceLayerPixels(d.selected.id,{...d.selected,bitmap:{width:513,height:299,data}},'paint',d.revision,{x:260,y:260,width:1,height:1});assert.equal(d.selected.bitmap.pages.kind,'overlay');assert.equal(d.selected.bitmap.pages.tiles.length,1);assert.deepEqual(d.selected.bitmap.data,data);const edited=d.state;d.history.undo();assert.equal(d.state,original);d.history.redo();assert.equal(d.state,edited);const text=serializeProject(d.state),reopened=deserializeProject(text);assert.equal(JSON.parse(text).version,13);assert.deepEqual(reopened.layers[0].bitmap.data,data);
 const codec=new RecoveryCodec(),encoded=await codec.encode({version:2,activeId:d.identity.id,documents:[{state:d.state,dirty:true}]},new Set());assert.equal(encoded.session.version,14);const restored=await decodeRecovery(encoded.session,encoded.chunks);assert.deepEqual(restored.documents[0].state.layers[0].bitmap.data,data);const repeat=await codec.encode(restored,encoded.used);assert.equal(repeat.chunks.size,0);const corrupt=new Map(encoded.chunks),[key,chunk]=corrupt.entries().next().value;const bad=chunk.slice();bad[0]^=1;corrupt.set(key,bad);await assert.rejects(decodeRecovery(encoded.session,corrupt),/校验/);d.dispose();});

test('archive encodes only referenced backing ranges and rejects invalid offsets',()=>{const buffer=new Uint8Array(100).fill(99),visible=buffer.subarray(10,20);visible.fill(2);const archive=encodePixelArchive({a:visible,b:visible.subarray(2)});assert.equal(archive.buffers[0].length,10);const copy=decodePixelArchive(archive.tree,archive.buffers);assert.deepEqual(copy.a,visible);assert.equal(copy.a.buffer,copy.b.buffer);assert.throws(()=>decodePixelArchive({$pixelBuffer:0,type:'Float32Array',offset:1,length:4},archive.buffers),/对齐/);});

test('pass-through groups blend against the existing backdrop, including group opacity',()=>{const base=makeLayer('base',{width:1,height:1,data:new Uint8ClampedArray([100,200,240,255])}),child={...makeLayer('multiply',{width:1,height:1,data:new Uint8ClampedArray([128,128,128,255])}),blend:'multiply'},group={...makeLayer('pass',null,'group'),passThrough:true,opacity:.5,children:[child]},state={id:'p',name:'p',width:1,height:1,layers:[base,group],selectedId:group.id,revision:1};validateState(state);assert.deepEqual([...compositeState(state).data],[75,150,180,255]);});

test('inner glow including noise is stable across tiled and full rendering',()=>{const l={...makeLayer('glow',bitmap(129,99)),styles:{enabled:true,overlay:{color:'#102030',opacity:.4},innerGlow:{color:'#ffffff',opacity:.25,size:0,choke:55,noise:.56,range:.5,source:'center',blend:'screen'}}},s={id:'g',name:'g',width:129,height:99,layers:[l],selectedId:l.id,revision:1},full=compositeReference(s),tiled=new Uint8ClampedArray(full.data.length);forEachCompositeTile(s,(b,r)=>{for(let y=0;y<b.height;y++)tiled.set(b.data.subarray(y*b.width*4,(y+1)*b.width*4),((r.y+y)*s.width+r.x)*4);},32);assert.deepEqual(tiled,full.data);});

test('paged native archive keeps layer records and supports byte-identical pixel PSD roundtrip',()=>{const {bytes,b}=source(33,27),state=importPagedPsd(bytes,'native.psd',new Uint8Array());clearPagedPixelCache();bytes.fill(0);assert.equal(pagedPixelStats().materializations,0);assert.deepEqual(state.layers[0].bitmap.data,b.data);const out=exportPsd(state),again=importPsd(out.bytes,'again.psd');assert(again.layered,again.blockers.join());assert.deepEqual(again.layered.layers[0].bitmap.data,b.data);});

test('native archive cannot override edited name, opacity, visibility, position or lock',()=>{const {bytes}=source(33,27),d=new ImageDocument(importPagedPsd(bytes,'native.psd',new Uint8Array()));d.updateLayer(d.selected.id,{name:'edited',opacity:.4,visible:false,locked:false,x:3,y:4});const raw=readPsd(exportPsd(d.state).bytes,{useRawData:true,skipCompositeImageData:true}).children[0];assert.equal(raw.name,'edited');assert.equal(raw.hidden,true);assert.equal(raw.opacity,.4);assert.equal(raw.left,3);assert.equal(raw.top,4);assert(!raw.protected?.composite);d.dispose();});

test('paged damage compares immutable override tiles without decoding whole layers',async()=>{const {documentDamage}=await import('../dist/renderDamage.js'),{b,page}=source(),d=documentOf(page),before=d.state,data=b.data.slice();data[(260*513+260)*4]=99;d.replaceLayerPixels(d.selected.id,{...d.selected,bitmap:{width:513,height:299,data}},'paint',d.revision,{x:260,y:260,width:1,height:1});clearPagedPixelCache();const damage=documentDamage(before,d.state);assert.deepEqual(damage,{x:256,y:256,width:256,height:43});assert.equal(pagedPixelStats().materializations,0);d.dispose();});

test('editing archived point text keeps its fractional origin and replaces native text content',()=>{const b=bitmap(33,27),text={text:'A',transform:[1,0,0,1,.25,20.5],shapeType:'point',style:{font:{name:'ArialMT'},fontSize:18,leading:23,fillColor:{r:0,g:0,b:0}},paragraphStyle:{justification:'left'}};const bytes=writePsdUint8Array({width:33,height:27,children:[{id:5,name:'type',text,imageData:b}],imageData:b},{noBackground:true,compress:false}),d=new ImageDocument(importPagedPsd(bytes,'text.psd',new Uint8Array()));d.setContent(d.selected.id,{...d.selected.content,text:'B'},b);const raw=readPsd(exportPsd(d.state).bytes,{useRawData:true,skipCompositeImageData:true});assert.equal(raw.children[0].text.text,'B');assert.deepEqual(raw.children[0].text.transform,[1,0,0,1,.25,20.5]);d.dispose();});
