import test from 'node:test';
import assert from 'node:assert/strict';
import {writePsdUint8Array} from 'ag-psd';
import {ImageDocument,allLayers,validateState} from '../dist/document.js';
import {importPsd,exportPsd} from '../dist/psdAdapter.js';
import {readPsdMetadata} from '../dist/highDepthPsd.js';
import {serializeProject,deserializeProject} from '../dist/projectFile.js';
import {RecoveryCodec,decodeRecovery} from '../dist/recoveryCodec.js';
import {transformedLayer,commitTransform} from '../dist/freeTransform.js';
import {replaceSmart} from '../dist/smartObject.js';
import {openSmartSource,originalSmartSource} from '../dist/smartSource.js';
import {mapQuadPoint,quadCoordinates} from '../dist/projective.js';
import {validateContent} from '../dist/layerFeatures.js';
const sourceId='a7d625e8-9932-11d9-9047-99f2050cf3c5',data=new TextEncoder().encode('%PDF-1.4\n% preserved opaque source\n%%EOF'),bitmap={width:4,height:3,data:new Uint8ClampedArray(48).fill(255)};
function fixture({legacy=false,global=false,relative=false}={}){const placedLayer={id:sourceId,type:'vector',transform:[10,20,14,20,14,23,10,23],warp:{style:'none',uOrder:4,vOrder:4,bounds:{left:{value:0,units:'Pixels'},top:{value:0,units:'Pixels'},right:{value:4,units:'Pixels'},bottom:{value:3,units:'Pixels'}}},...(!legacy?{width:4,height:3}:{})};return writePsdUint8Array({width:30,height:30,linkedFiles:[{id:sourceId,name:'vector.ai',type:'PDF',data}],globalLayerMaskInfo:{overlayColorSpace:0,colorSpace1:65535,colorSpace2:0,colorSpace3:0,colorSpace4:0,opacity:50/255,kind:128},children:['one','two'].map((name,i)=>({name,id:11+i,left:10,top:20,imageData:bitmap,placedLayer,layerMaskAsGlobalMask:global,mask:{left:10,top:20,imageData:bitmap,defaultColor:0,positionRelativeToLayer:relative}}))},{noBackground:true});}
test('PDF sources and shared IDs survive native roundtrip, project and recovery',async()=>{const r=importPsd(fixture(),'vector.psd');assert(r.layered,r.blockers.join());const d=new ImageDocument(r.layered),l=d.state.layers[0];assert.equal(l.content.sourcePdf.data.length,data.length);assert.match(r.warnings[0],/像素缓存/);assert.throws(()=>openSmartSource(l.content),/矢量/);const project=serializeProject(d.state);assert.equal(JSON.parse(project).version,16);const restored=deserializeProject(project);assert.deepEqual(restored.layers[0].content.sourcePdf.data,data);const input={version:2,activeId:d.identity.id,documents:[{state:d.state,dirty:true}]},r2=await new RecoveryCodec().encode(input,new Set());assert.deepEqual((await decodeRecovery(r2.session,r2.chunks)).documents[0].state.layers[0].content.sourcePdf.data,data);
 for(const state of [d.state,restored]){const out=exportPsd(state).bytes,p=readPsdMetadata(out);assert.equal(p.linkedFiles.length,1);assert.deepEqual(p.linkedFiles[0].data,data);for(const layer of p.children){assert.equal(layer.placedLayer.type,'vector');assert.equal(layer.placedLayer.id,sourceId);assert.deepEqual(layer.placedLayer.transform,[10,20,14,20,14,23,10,23]);assert.equal(layer.placedLayer.width,4);}assert(importPsd(out,'again.psd').layered);}d.dispose();});
test('masked vector smart transform retains source, native geometry and undo, including flips',()=>{for(const flipX of [false,true]){const d=new ImageDocument(importPsd(fixture(),'vector.psd').layered),id=d.state.layers[0].id,before=d.state;commitTransform(d,transformedLayer(d.state,id,{width:8,height:6,angle:0,dx:0,dy:0,flipX}));const l=d.state.layers[0];assert.deepEqual([l.mask.x,l.mask.y,l.mask.width,l.mask.height],[0,0,8,6]);const out=readPsdMetadata(exportPsd(d.state).bytes);assert.deepEqual(out.linkedFiles[0].data,data);assert.deepEqual(out.children[0].placedLayer.transform,flipX?[16,19,8,19,8,25,16,25]:[8,19,16,19,16,25,8,25]);d.history.undo();assert.equal(d.state,before);d.dispose();}});
test('replacing one vector instance explicitly detaches its PDF without changing other instances',()=>{const d=new ImageDocument(importPsd(fixture(),'vector.psd').layered),before=d.state,l=d.state.layers[0];replaceSmart(d,l.id,bitmap,'replacement');assert.equal(d.state.layers[0].content.sourcePdf,undefined);assert(d.state.layers[1].content.sourcePdf);const p=readPsdMetadata(exportPsd(d.state).bytes);assert.equal(p.children[0].placedLayer.type,'raster');assert.equal(p.children[1].placedLayer.type,'vector');assert.notEqual(p.children[0].placedLayer.id,p.children[1].placedLayer.id);d.history.undo();assert.equal(d.state,before);d.dispose();});
test('PDF validation and depth conversion remain bounded',()=>{const r=importPsd(fixture(),'vector.psd'),c=r.layered.layers[0].content;assert.throws(()=>validateContent({...c,sourcePdf:{...c.sourcePdf,data:new Uint8Array(12)}}),/PDF/);assert.throws(()=>validateContent({...c,sourcePdf:{...c.sourcePdf,pageNumber:2}}),/PDF/);assert.throws(()=>validateContent({...c,sourcePdf:{...c.sourcePdf,bounds:[0,0,0,1]}}),/尺寸/);const d=new ImageDocument(r.layered);assert.throws(()=>d.setDepth(16),/智能对象/);d.dispose();});
test('forward/inverse quad maps agree for affine and perspective coordinates',()=>{for(const q of [[0,0,10,0,10,20,0,20],[2,1,9,3,8,20,0,14],[10,0,0,0,0,20,10,20]])for(const [u,v] of [[0,0],[1,1],[.37,.61]]){const p=mapQuadPoint(q,u,v),b=quadCoordinates(q,...p);assert(Math.abs(b[0]-u)<1e-10);assert(Math.abs(b[1]-v)<1e-10);}});
test('original smart source API returns native bytes with explicit format and capability query',async()=>{const {ImageWorkspace}=await import('../dist/workspace.js'),{operationClient}=await import('../../scripts/editor-e2e/operationWorkflow.mjs'),w=new ImageWorkspace();await w.start();try{const d=new ImageDocument(importPsd(fixture(),'vector.psd').layered);w.add(d);const call=operationClient(w.platform,d.identity.id),r=await call('image.smart.source.read',{layerId:d.state.layers[0].id,format:'original'});assert.equal(r.format,'pdf');assert.deepEqual(w.platform.resources.read(r.resourceId),data);w.platform.resources.release(r.resourceId);const q=await call('image.document.query');assert.equal(q.layers[0].content.sourceFormat,'pdf');assert.equal(q.layers[0].content.preview,'cached');}finally{await w.dispose();}});

test('legacy placed masks use document bounds; modern relative masks retain their local coordinates',()=>{for(const legacy of [true,false]){const r=importPsd(fixture({legacy,relative:true}),'mask.psd');assert(r.layered,r.blockers.join());assert.deepEqual([r.layered.layers[0].mask.x,r.layered.layers[0].mask.y],legacy?[0,0]:[10,20]);}});

test('selecting archived layers keeps lazy native archive access through source replacement and undo',()=>{const d=new ImageDocument(importPsd(fixture(),'vector.psd').layered);for(const multi of [false,true]){const id=d.state.layers[0].id;if(multi)d.selectMany([id]);else d.select(id);const before=d.state;validateState(before);assert(before.psdArchive);replaceSmart(d,id,bitmap,'replacement');d.history.undo();assert.equal(d.state,before);validateState(d.state);assert(d.state.psdArchive);exportPsd(d.state);}d.dispose();});

test('original source extraction distinguishes PSB from PSD without mutating source bytes',()=>{const c=importPsd(fixture(),'v.psd').layered.layers[0].content;for(const version of [1,2]){const data=new Uint8Array(26),v=new DataView(data.buffer);v.setUint32(0,0x38425053);v.setUint16(4,version);const source={...c,sourcePdf:undefined,sourcePsd:data};const r=originalSmartSource(source);assert.equal(r.format,version===2?'psb':'psd');r.bytes.fill(0);assert.equal(v.getUint32(0),0x38425053);}});
