import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync,readFileSync,readdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {runEditorBrowserScenario} from '../../scripts/editor-e2e/browserDriver.mjs';
const root=resolve(import.meta.dirname,'../..'),output=resolve(root,'imageEditor/artifacts/professional');mkdirSync(output,{recursive:true});
const report=await runEditorBrowserScenario({root,route:'imageEditor/app-dist/index.html',downloadDirectory:output,failureScreenshotPath:resolve(output,'failure.png'),readinessExpression:'Boolean(globalThis.haiyueEditor?.listOperations().some(e=>e.descriptor.id==="image.batch.run")&&document.querySelector("#app")?.getAttribute("aria-busy")==="false")',scenario:async driver=>{
 const {evaluate,click,cdp,nextPaint,waitFor}=driver,e=s=>`document.querySelector(${JSON.stringify(s)})`,act=a=>click(e(`[data-action="${a}"]`)),tool=t=>click(e(`[data-tool="${t}"]`));
 await evaluate(`globalThis.proId=null;globalThis.seq=0;globalThis.call=async(suffix,params={})=>{const d=haiyueEditor.listDocuments().documents.find(d=>d.identity.id===proId);const r=await haiyueEditor.execute({apiVersion:'1',requestId:'pro-'+(++seq),operation:'image.'+suffix,params,...(d&&!['document.create','document.open','batch.run'].includes(suffix)?{documentId:proId,expectedRevision:d.revision}:{})});if(r.status!=='completed')throw Error(JSON.stringify(r));return r.value;};`);
 const call=(s,p={})=>evaluate(`call(${JSON.stringify(s)},${JSON.stringify(p)})`),created=await call('document.create',{name:'专业修图',width:400,height:300});await evaluate(`proId=${JSON.stringify(created.documentId)}`);await call('layer.create',{name:'笔画',kind:'pixel'});await nextPaint();await act('actual');const id=(await call('document.query')).selectedId;
 const point=async(x,y)=>evaluate(`(()=>{const r=document.querySelector('#image-canvas').getBoundingClientRect();return {x:r.x+${x}*r.width/400,y:r.y+${y}*r.height/300}})()`),mouse=(type,p,extra={})=>cdp.call('Input.dispatchMouseEvent',{type,...p,button:'left',buttons:type==='mouseReleased'?0:1,clickCount:1,...extra}),tap=async(x,y,extra={})=>{const p=await point(x,y);await mouse('mousePressed',p,extra);await mouse('mouseReleased',p,extra);await nextPaint();},drag=async(a,b,extra={})=>{await mouse('mousePressed',await point(...a),extra);await mouse('mouseMoved',await point(...b),extra);await mouse('mouseReleased',await point(...b),extra);await nextPaint();},key=async key=>{await cdp.call('Input.dispatchKeyEvent',{type:'keyDown',key});await cdp.call('Input.dispatchKeyEvent',{type:'keyUp',key});await nextPaint();};
 console.log('[professional] brush/pen');await tool('brush');await evaluate(`document.querySelector('#brush-size').value='40';document.querySelector('#brush-hardness').value='0';document.querySelector('#brush-pressure').value='both';document.querySelector('#paint-color').value='#ff0000';`);await tap(100.5,100.5,{pointerType:'pen',force:.5});let sample=await call('color.sample',{x:100,y:100});assert(sample.rgba[3]>110&&sample.rgba[3]<145,JSON.stringify(sample));assert.equal((await call('color.sample',{x:113,y:100})).rgba[3],0);await call('history.undo');assert.equal((await call('color.sample',{x:100,y:100})).rgba[3],0);
 await call('pixels.stroke',{layerId:id,color:'#ff0000',points:[{x:100,y:100}],size:40});await tool('clone');await evaluate(`document.querySelector('#brush-hardness').value='100';document.querySelector('#brush-pressure').value='none'`);await tap(100,100,{modifiers:1});await tap(160,100);assert.deepEqual((await call('color.sample',{x:160,y:100})).rgba,[255,0,0,255]);await call('history.undo');assert.equal((await call('color.sample',{x:160,y:100})).rgba[3],0);
 await tool('heal');await tap(100,100,{modifiers:1});await tap(160,100);assert((await call('color.sample',{x:160,y:100})).rgba[3]>0);await call('history.undo');
 console.log('[professional] refine');await call('selection.set',{shape:'rectangle',x:70,y:70,width:60,height:60});await evaluate(`document.querySelector('[data-action="menu-refine-selection"]').click()`);await nextPaint();await click(e('#professional-run'));await waitFor(()=>evaluate(`!document.querySelector('#professional-dialog').open`),'professional operation',20000);assert((await call('document.query')).selection.pixels>0);await call('history.undo');await call('selection.clear');
 console.log('[professional] path');await tool('path');await drag([210,60],[230,60]);await tap(310,140);await tap(210,160);await key('Enter');let q=await call('document.query'),path=q.layers.at(-1);assert.equal(path.content.type,'path');assert.equal(path.content.nodes.length,3);assert.notEqual(path.content.nodes[0].outX,path.content.nodes[0].x);assert.deepEqual((await call('color.sample',{x:220,y:120})).rgba,[255,0,0,255]);assert.equal((await call('color.sample',{x:300,y:80})).rgba[3],0);await act('edit-content');await drag([310,140],[320,150]);await key('Escape');assert.deepEqual((await call('document.query')).layers.at(-1).content,path.content);await act('edit-content');await drag([310,140],[320,150]);await key('Enter');assert.notDeepEqual((await call('document.query')).layers.at(-1).content,path.content);await call('history.undo');
 const psd=await call('document.export',{format:'psd'});assert.equal((await evaluate(`Array.from(haiyueEditor.readResource(${JSON.stringify(psd.resourceId)}).slice(0,4))`)).join(),'56,66,80,83');await evaluate(`haiyueEditor.releaseResource(${JSON.stringify(psd.resourceId)})`);
 console.log('[professional] rich text');await act('text');await evaluate(`(()=>{const t=document.querySelector('#text-content');t.value='海月 Rich text';t.dispatchEvent(new Event('input',{bubbles:true}));t.setSelectionRange(0,2);document.querySelector('#text-color').value='#00ff00';document.querySelector('#text-size').value='32';document.querySelector('#text-underline').checked=true;document.querySelector('#text-wrap').value='140';})()`);await click(e('#text-format-range'));await click(e('#text-form button[type=submit]'));await nextPaint();q=await call('document.query');const rich=q.layers.at(-1);assert.equal(rich.content.runs[0].color,'#00ff00');assert.equal(rich.content.runs[0].end,2);assert.notEqual(rich.content.color,'#00ff00');assert.equal(rich.content.wrapWidth,140);await act('edit-content');await evaluate(`(()=>{const t=document.querySelector('#text-content');t.value='X'+t.value;t.dispatchEvent(new Event('input',{bubbles:true}));})()`);await click(e('#text-form button[type=submit]'));await nextPaint();assert.equal((await call('document.query')).layers.at(-1).content.runs[0].end,3);await call('history.undo');
 console.log('[professional] ICC');await evaluate(`document.querySelector('#production-menu').shadowRoot.querySelector('[data-action="menu-color-management"]').click();document.querySelector('#profile-source').value='display-p3'`);await nextPaint();await click(e('#professional-run'));await waitFor(()=>evaluate(`!document.querySelector('#professional-dialog').open`),'professional operation',20000);assert.equal((await call('color.query')).convertedFrom,'display-p3');await call('history.undo');assert.equal((await call('color.query')).convertedFrom,null);
 console.log('[professional] batch');const project=await call('document.export',{format:'project'}),bytes=await evaluate(`Array.from(haiyueEditor.readResource(${JSON.stringify(project.resourceId)}))`);writeFileSync(resolve(output,'input.hyimage'),Buffer.from(bytes));
 const batch=await call('batch.run',{inputs:[{resourceId:project.resourceId,name:'input.hyimage',format:'project'}],steps:[{type:'fit',width:200,height:200},{type:'filter',kind:'grayscale',amount:100}],format:'png'});assert(batch[0].resourceId);assert.equal((await evaluate(`haiyueEditor.readResource(${JSON.stringify(batch[0].resourceId)})[0]`)),137);await evaluate(`haiyueEditor.releaseResource(${JSON.stringify(batch[0].resourceId)});haiyueEditor.releaseResource(${JSON.stringify(project.resourceId)})`);
 await evaluate(`document.querySelector('[data-action="menu-batch"]').click()`);const node=await cdp.call('DOM.getDocument',{}),input=await cdp.call('DOM.querySelector',{nodeId:node.result.root.nodeId,selector:'#batch-files'});await cdp.call('DOM.setFileInputFiles',{nodeId:input.result.nodeId,files:[resolve(output,'input.hyimage')]});await nextPaint();await click(e('#professional-run'));await waitFor(()=>evaluate(`Boolean(document.querySelector('#batch-results a'))`),'batch output',20000);assert.equal(await evaluate(`document.querySelector('#batch-results a').download`),'input.png');await click(e('#professional-close'));
 // Cancel an active real worker through the public API before commit.
 const rev=await evaluate(`haiyueEditor.listDocuments().documents.find(d=>d.identity.id===proId).revision`);const cancelled=await evaluate(`(async()=>{const Original=Worker;let created=0,terminated=0;globalThis.Worker=class extends Original{constructor(...args){super(...args);created++;}terminate(){terminated++;super.terminate();}};try{const d=haiyueEditor.listDocuments().documents.find(d=>d.identity.id===proId);const promise=haiyueEditor.execute({apiVersion:'1',requestId:'cancel-color',operation:'image.color.convert',documentId:proId,expectedRevision:d.revision,params:{source:'srgb'}});setTimeout(()=>haiyueEditor.cancel('cancel-color'),10);return {result:await promise,created,terminated};}finally{globalThis.Worker=Original;}})()`);assert.equal(cancelled.result.status,'cancelled');assert.equal(cancelled.created,1);assert.equal(cancelled.terminated,1);assert.equal(await evaluate(`haiyueEditor.listDocuments().documents.find(d=>d.identity.id===proId).revision`),rev);
 driver.assertNoBrowserErrors();await evaluate(`document.querySelector('[data-action="menu-batch"]').click()`);const screenshot=await cdp.call('Page.captureScreenshot',{format:'png'});writeFileSync(resolve(output,'professional.png'),Buffer.from(screenshot.result.data,'base64'));
 return {status:'passed',runner:{chrome:driver.chrome,angleBackend:driver.angleBackend,node:process.version,platform:process.platform,arch:process.arch},cases:['real-pen-pressure','clone-alt-source','healing','refine-worker','Bezier-drag-edit-cancel-undo-native-PSD','rich-text-range-wrap-edit','ICC-worker-undo','batch-API-and-file-picker','operation-cancellation'],buildHash:JSON.parse(readFileSync(resolve(root,'imageEditor/app-dist/app-manifest.json'))).buildHash};
}});
const hash=b=>createHash('sha256').update(b).digest('hex');writeFileSync(resolve(output,'browser.json'),JSON.stringify({...report,schemaVersion:1,generatedAt:new Date().toISOString(),revision:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),dirty:true,sourceFingerprints:Object.fromEntries([...readdirSync(resolve(root,'imageEditor/src')).map(f=>'imageEditor/src/'+f),'imageEditor/test/professional-browser.mjs','imageEditor/index.html','imageEditor/styles.css','imageEditor/rollup.config.js','imageEditor/app/descriptor.json','config/rollup.shared.js','package-lock.json'].map(f=>[f,hash(readFileSync(resolve(root,f)))]))},null,2));console.log(report);
