import test from 'node:test';import assert from 'node:assert/strict';import{writePsdUint8Array,readPsd}from'ag-psd';
import{importPsd,exportPsd}from'../dist/psdAdapter.js';import{readPsdMetadata}from'../dist/highDepthPsd.js';import{ImageDocument,allLayers}from'../dist/document.js';import{readEditableText}from'../dist/psdText.js';import{nativeWritable,validateContent}from'../dist/layerFeatures.js';import{readSmartSource,openSmartSource,prepareSmartSource}from'../dist/smartSource.js';import{serializeProject,deserializeProject}from'../dist/projectFile.js';
const image=(width=64,height=64)=>({width,height,data:Uint8ClampedArray.from({length:width*height*4},(_,i)=>i%4===3?255:80)}),units=value=>({units:'Pixels',value});
function fixture(deform=false){const id='01234567-89ab-cdef-0123-456789abcdef',source=writePsdUint8Array({width:8,height:8,imageData:image(8,8),children:[{name:'source',imageData:image(8,8)}],annotations:[{type:'text',open:false,iconLocation:{left:0,top:0,right:1,bottom:1},popupLocation:{left:0,top:0,right:5,bottom:5},color:{r:255,g:0,b:0},author:'Haiyue',name:'Note',date:'',data:'Keep annotation'}]},{noBackground:true,psb:true});return writePsdUint8Array({width:64,height:64,imageData:image(),linkedFiles:[{id,name:'source.psb',type:'8BPB',data:source}],children:[
 {name:'rich',imageData:image(),text:{text:'Red blue\nIndented',shapeType:'box',boxBounds:[0,0,50,50],transform:[1.2,-.2,.3,1.1,4,6],style:{font:{name:'ArialMT'},fontSize:12.5,autoLeading:false,leading:16,fillColor:{r:255,g:0,b:0}},styleRuns:[{length:4,style:{font:{name:'Arial-BoldMT'}}},{length:13,style:{font:{name:'Arial-ItalicMT'},fontSize:14.25,fillColor:{r:0,g:0,b:255},underline:true}}],paragraphStyle:{justification:'left',firstLineIndent:3,startIndent:2,endIndent:1,spaceBefore:2,spaceAfter:4}}},
 {name:'inside',imageData:image(),vectorFill:{type:'color',color:{r:255,g:255,b:255}},vectorStroke:{strokeEnabled:true,fillEnabled:true,lineWidth:{units:'Points',value:.48},resolution:150,lineAlignment:'inside',lineCapType:'butt',lineJoinType:'miter',opacity:1,blendMode:'normal',content:{type:'color',color:{r:0,g:0,b:0}}},vectorMask:{paths:[{open:false,operation:'combine',fillRule:'even-odd',knots:[[1,1],[63,1],[63,63],[1,63]].map(([x,y])=>({linked:false,points:[x,y,x,y,x,y]}))}]},mask:{left:0,top:0,defaultColor:0,fromVectorData:true,imageData:image()}},
 {name:'embedded',imageData:image(),placedLayer:{id,type:'raster',width:8,height:8,transform:[0,0,64,0,64,64,0,64],warp:{style:'custom',value:0,perspective:0,perspectiveOther:0,uOrder:4,vOrder:4,bounds:{left:units(20),top:units(30),right:units(28),bottom:units(38)},customEnvelopeWarp:{meshPoints:Array.from({length:16},(_,i)=>({x:20+i%4*8/3+(deform&&i===5?1:0),y:30+Math.floor(i/4)*8/3}))}}}}
 ]},{noBackground:true});}
test('box rich text, affine placement, inside Point stroke and annotated embedded PSB roundtrip natively',()=>{
 const bytes=fixture(),r=importPsd(bytes,'rich.psd');assert(r.layered,r.blockers.join('\n'));const ls=allLayers(r.layered.layers),text=ls.find(l=>l.name==='rich'),path=ls.find(l=>l.name==='inside'),smart=ls.find(l=>l.name==='embedded');
 assert.equal(text.content.runs.length,2);assert.equal(text.content.runs[0].bold,true);assert.equal(text.content.runs[1].italic,true);assert.equal(text.content.runs[1].color,'#0000ff');assert.deepEqual(text.content.layout.transform,[1.2,-.2,.3,1.1]);assert.deepEqual(text.content.layout.box,[0,0,50,50]);assert.equal(text.content.layout.firstLineIndent,3);assert(nativeWritable(text.content));assert.equal(path.content.strokeAlignment,'inside');assert.equal(path.content.strokeWidth,1);assert(path.mask.vector);
 assert.equal(new DataView(smart.content.sourcePsd.buffer,smart.content.sourcePsd.byteOffset).getUint16(4),2);const source=openSmartSource(smart.content);assert.equal(source.width,8);assert.equal(readPsdMetadata(source.psdArchive).annotations[0].data,'Keep annotation');
 const restored=deserializeProject(serializeProject(r.layered)),out=exportPsd(restored).bytes,old=readPsdMetadata(bytes),next=readPsdMetadata(out);for(let i=0;i<3;i++)for(const key of ['text','vectorMask','vectorStroke','placedLayer'])assert.deepEqual(next.children[i][key],old.children[i][key]);assert.deepEqual(next.linkedFiles[0].data,old.linkedFiles[0].data);assert(importPsd(out,'again.psd').layered);
});
test('edits preserve native text ranges and matrix, replace stale vector mask, and undo exactly',()=>{
 const r=importPsd(fixture(),'rich.psd'),d=new ImageDocument(r.layered),ls=allLayers(d.state.layers),text=ls.find(l=>l.name==='rich'),path=ls.find(l=>l.name==='inside'),before=d.state;
 d.setContent(text.id,{...text.content,text:'Red cyan\nIndented',runs:text.content.runs.map((r,i)=>i?{...r,color:'#00ffff'}:r)},image());const out=readPsdMetadata(exportPsd(d.state).bytes),t=out.children[0].text;assert.equal(t.text,'Red cyan\nIndented');assert.deepEqual(t.transform,[1.2,-.2,.3,1.1,4,6]);assert.deepEqual(t.boxBounds,[0,0,50,50]);assert.equal(t.paragraphStyle.firstLineIndent,3);assert.equal(t.styleRuns[0].style.fauxBold??false,false,'intrinsic bold must not be synthesized twice');assert.equal(t.styleRuns[1].style.fauxItalic??false,false,'intrinsic italic must not be synthesized twice');assert.equal(t.styleRuns[1].style.fillColor.g,255);assert.equal(t.styleRuns[1].style.fontSize,14.25);assert.equal(out.engineData,undefined);assert(importPsd(exportPsd(d.state).bytes,'edited.psd').layered);d.history.undo();assert.equal(d.state,before);
 d.setContent(path.id,{...path.content,strokeWidth:2.5},image());assert.equal(allLayers(d.state.layers).find(l=>l.id===path.id).mask,undefined);const p=readPsdMetadata(exportPsd(d.state).bytes).children[1];assert.equal(p.vectorStroke.lineAlignment,'inside');assert.equal(p.vectorStroke.lineWidth.value,2.5);d.history.undo();assert.equal(d.state,before);d.dispose();
});
test('embedded PSB edits become editable PSD source; actual mesh deformation and invalid layouts stay blocked',()=>{
 const r=importPsd(fixture(),'rich.psd'),smart=allLayers(r.layered.layers).find(l=>l.content?.type==='smart').content,source=openSmartSource(smart),d=new ImageDocument(source);d.updateLayer(d.state.layers[0].id,{name:'Edited source'});const changed=prepareSmartSource(smart,d.state);assert.equal(new DataView(changed.sourcePsd.buffer).getUint16(4),1);assert.equal(readSmartSource(changed.sourcePsd,'edited').state.layers[0].name,'Edited source');d.dispose();
 const bad=importPsd(fixture(true),'warp.psd');assert(!bad.layered);assert(bad.blockers.some(b=>b.includes('变形网格')));
 const c=allLayers(r.layered.layers).find(l=>l.content?.type==='text').content;for(const layout of [{...c.layout,transform:[1,1,1,1]},{...c.layout,box:[1,2,0,3]}])assert.throws(()=>validateContent({...c,layout}));assert(!nativeWritable({...c,wrapWidth:50}));assert.throws(()=>readEditableText({...readPsdMetadata(fixture()).children[0].text,textPath:{data:{textRange:[0,2]}}},{left:0,top:0,right:64,bottom:64}),/沿路径/);
});
