export const EDITOR_LOCALE_STORAGE_KEY = 'haiyue.voxel-editor.locale';

export const EDITOR_LOCALES = ['zh-CN', 'en-US'] as const;
export type EditorLocale = typeof EDITOR_LOCALES[number];

const zhCN = {
  'app.title': '海月体素编辑器',
  'app.brand': '海月体素',
  'app.settings': '编辑器设置',
  'app.help': '操作帮助',
  'app.save': '保存到浏览器',
  'app.saveShortcut': '保存到浏览器 (Ctrl/⌘ S)',
  'app.unsavedSuffix': ' · 有未保存修改',
  'app.recent': '最近打开工程',
  'app.undo': '撤销',
  'app.redo': '重做',
  'history.undoLabel': '撤销：{label} (Ctrl/⌘ Z)',
  'history.redoLabel': '重做：{label} (Ctrl/⌘ Shift Z)',
  'history.noUndo': '没有可撤销的操作',
  'history.noRedo': '没有可重做的操作',
  'app.importProject': '导入工程',
  'app.importProjectFormats': '导入工程（JSON / VOX）',
  'app.importImage': '导入图片为模块',
  'app.export': '导出',
  'app.moreInfo': '查看说明',
  'panel.tools': '工具',
  'panel.editMode': '编辑模式',
  'panel.currentColor': '当前颜色',
  'panel.sceneSettings': '场景设置',
  'common.size': '尺寸',
  'common.mode': '模式',
  'common.name': '名称',
  'common.width': '宽',
  'common.height': '高',
  'common.delete': '删除',
  'common.cancel': '取消',
  'common.copy': '复制',
  'common.move': '移动',
  'common.rename': '重命名',
  'project.current': '当前工程',
  'project.untitled': '未命名工程',
  'tool.add': '添加',
  'tool.erase': '擦除',
  'tool.paint': '着色',
  'tool.select': '选择',
  'brush.label': '笔刷',
  'brush.voxel': '连续体素',
  'brush.line': '拖拽直线',
  'brush.box': '拖拽立方体',
  'brush.flood': 'Flood Fill 连通填充',
  'brush.surface': 'Surface Paint 外露表面',
  'brush.mirror': '镜像绘制',
  'brush.mirrorAxes': '镜像绘制轴',
  'brush.sizeNotUsed': '连通与表面笔刷不使用尺寸参数',
  'selection.kind': '选择方式',
  'selection.single': '单体 / 屏幕框选',
  'selection.connected': '连通同色区域',
  'selection.color': '所有同色体素',
  'selection.depth': '框选深度',
  'selection.visible': '仅可见体素',
  'selection.through': '穿透选择',
  'selection.all': '全选',
  'selection.invert': '反选',
  'selection.count': '个体素已选择',
  'selection.gizmo': '交互式 Gizmo',
  'selection.moveDrag': '拖动平移',
  'selection.duplicateDrag': '复制拖动',
  'selection.rotateRing': '90° 旋转环',
  'selection.integerScale': '包围盒整数缩放',
  'selection.snap': '吸附',
  'selection.unit1': '1 单位',
  'selection.unit5': '5 单位',
  'selection.unit10': '10 单位',
  'selection.center': '选区中心',
  'selection.minimum': '最小角点',
  'selection.custom': '自定义坐标',
  'selection.offset': '偏移变换',
  'selection.duplicateOffset': '复制偏移',
  'selection.rotate90': '旋转 90°',
  'selection.aroundX': '绕 X',
  'selection.aroundY': '绕 Y',
  'selection.aroundZ': '绕 Z',
  'selection.flip': '镜像翻转',
  'selection.cut': '剪切',
  'selection.paste': '粘贴',
  'material.name': '材质名',
  'material.metallic': '金属度',
  'material.roughness': '粗糙度',
  'material.savePbr': '保存 PBR',
  'material.duplicate': '复制材质',
  'material.unused': '当前材质未被使用',
  'material.colorAria': '选择颜色',
  'material.hexAria': '十六进制颜色',
  'material.paletteAria': '预设调色板',
  'material.select': '选择材质 {name}',
  'material.usage': '{count} 个定义体素使用此材质',
  'material.voxPartial': 'VOX {type}（部分兼容，PBR 近似预览）',
  'material.voxPartialDetail': 'VOX {type} 材质：原始 MATL 已保留，当前 PBR 视口仅近似显示。',
  'paint.replaceTitle': '替换颜色',
  'paint.replaceSource': '要被替换的颜色',
  'paint.replaceWith': '替换为',
  'paint.replaceTarget': '替换后的当前颜色',
  'paint.scope': '范围',
  'paint.scopeGlobal': '当前场景 / 模块',
  'paint.scopeSelection': '仅当前选区',
  'paint.replaceAction': '执行颜色替换',
  'paint.selectionRequired': '请先选择要替换颜色的体素。',
  'paint.noMatch': '没有找到需要替换的体素。',
  'paint.replaceSelectionCommand': '替换选区颜色',
  'paint.replaceGlobalCommand': '全局替换颜色',
  'paint.replaced': '已将 {count} 个体素替换为 {color}。',
  'viewport.perspectiveView': '透视视图',
  'viewport.orthographicView': '正交视图',
  'viewport.addVoxel': '添加方块',
  'viewport.eraseVoxel': '擦除方块',
  'viewport.paintVoxel': '方块着色',
  'viewport.selectCount': '选择 · {count}',
  'viewport.orthographicPreset': '正交 · {view}',
  'viewport.focusRequired': '请先选择要聚焦的体素。',
  'viewport.coordinate': '格子 X {x} · Y {y} · Z {z}',
  'viewport.perspective': '透视',
  'viewport.orthographic': '正交',
  'viewport.projectionAria': '投影模式',
  'viewport.orbit': '环绕视角',
  'viewport.exitOrbit': '退出环绕',
  'viewport.orbitTitle': '切换环绕视角；也可以按住 Space 临时环绕',
  'viewport.reset': '重置视角',
  'viewport.drop': '拖放文件以导入',
  'viewport.dropFormats': 'JSON / VOX 完整工程 · PNG / JPG / WebP / GIF 图片模块',
  'viewport.standardViews': '标准视图与聚焦',
  'viewport.orthographicViews': '标准正交视图',
  'viewport.front': '前',
  'viewport.back': '后',
  'viewport.left': '左',
  'viewport.right': '右',
  'viewport.top': '顶',
  'viewport.bottom': '底',
  'viewport.frontView': '前视图',
  'viewport.backView': '后视图',
  'viewport.leftView': '左视图',
  'viewport.rightView': '右视图',
  'viewport.topView': '顶视图',
  'viewport.bottomView': '底视图',
  'viewport.frameSelected': '聚焦选择',
  'viewport.frameSelectedTitle': '聚焦选中体素（Frame Selected）',
  'viewport.frameAll': '显示全部',
  'viewport.frameAllTitle': '显示全部模型（Frame All）',
  'viewport.initializing': '正在初始化 WebGPU',
  'viewport.preparing': '准备体素工作区…',
  'viewport.coordinateEmpty': '格子 —',
  'viewport.axisAria': '相机方向坐标轴',
  'recovery.found': '发现自动恢复快照',
  'recovery.restore': '恢复',
  'recovery.ignore': '忽略',
  'export.preparing': '正在准备导出…',
  'export.cancel': '取消导出',
  'scene.size': '场景尺寸',
  'scene.applySize': '应用尺寸',
  'scene.background': '场景背景色',
  'scene.backgroundColorAria': '选择场景背景色',
  'scene.backgroundHexAria': '场景背景色十六进制值',
  'scene.backgroundReset': '默认',
  'scene.backgroundResetTitle': '恢复默认背景色',
  'scene.backgroundCommand': '修改场景背景色',
  'scene.backgroundUpdated': '场景背景色已更新。',
  'slice.title': '切片与工作平面',
  'slice.axisAria': '当前切片轴',
  'slice.display': '显示',
  'slice.all': '全部体素',
  'slice.single': '仅当前层',
  'slice.context': '当前层 + 半透明上下文',
  'slice.workPlane': '启用可移动工作平面',
  'shape.title': '批量生成',
  'shape.kind': '形状',
  'shape.box': '填充立方体',
  'shape.boxShell': '空心立方体',
  'shape.disk': '圆盘（XZ）',
  'shape.ring': '圆环（XZ）',
  'shape.sphere': '填充球体',
  'shape.sphereShell': '空心球体',
  'shape.cylinder': '圆柱体（Y 轴）',
  'shape.start': '起点',
  'shape.end': '终点',
  'shape.generate': '使用当前颜色生成',
  'image.title': '图片模块',
  'image.colorLimit': '颜色上限',
  'image.colors': '{count} 色',
  'image.dither': '抖动',
  'image.merge': '合并近色',
  'image.create': '选择图片并创建模块',
  'module.title': '模块',
  'module.scene': '主场景',
  'module.search': '搜索模块…',
  'module.searchAria': '搜索模块',
  'module.sortAria': '模块排序',
  'module.assetsAria': '模块资产',
  'module.libraryAria': '模块库',
  'module.nameAsc': '名称 A–Z',
  'module.nameDesc': '名称 Z–A',
  'module.empty': '尚未创建模块',
  'module.noMatch': '没有匹配的模块',
  'module.summary': '{name} · {count} 体素',
  'module.assetMeta': '{count} 体素 · {size}',
  'module.editing': '编辑：{name}',
  'module.sceneLayers': '场景图层 ({count})',
  'module.baseVoxels': '基础体素 ({count})',
  'module.layerSummary': '{name} ({voxels} 体素 · {instances} 实例)',
  'module.showSelected': '显示选中实例',
  'module.showLayer': '显示图层',
  'module.unlockLayer': '解锁图层',
  'module.collisionSummary': '冲突 {count} 格',
  'module.new': '新建',
  'module.edit': '编辑模块',
  'module.return': '返回场景',
  'module.duplicateDefinition': '复制定义',
  'module.removeUnused': '删除未使用',
  'module.locate': '定位该模块的所有实例',
  'module.position': '位置 / 粘贴坐标',
  'module.rotation': '旋转角度',
  'module.integerScale': '整数缩放',
  'module.applyTransform': '应用选中实例变换',
  'module.hideSelected': '隐藏选中实例',
  'module.copy': '复制模块',
  'module.paste': '粘贴到场景',
  'module.tree': '场景模块树',
  'module.noConflict': '当前实例没有重合冲突。',
  'module.highlightConflict': '定位并高亮冲突体素',
  'module.removeInstance': '删除选中的模块实例',
  'layer.title': '图层',
  'layer.sceneAria': '场景图层',
  'layer.default': '默认图层',
  'layer.new': '新建图层',
  'layer.remove': '删除图层',
  'layer.hide': '隐藏图层',
  'layer.lock': '锁定图层',
  'layer.assign': '将选中基础体素移至当前图层',
  'gizmo.instance': '实例 Gizmo',
  'gizmo.modeAria': 'Gizmo 模式',
  'gizmo.move': '移动 · 拖动轴',
  'gizmo.rotate': '旋转 · 点击轴 90°',
  'gizmo.scale': '缩放 · 拖动轴',
  'animation.title': '动画',
  'animation.frame': '帧 {current} / {total}',
  'animation.libraryAria': '动画片段',
  'animation.empty': '尚未创建动画',
  'animation.clipSummary': '{name} · {count} 帧',
  'animation.statusSelect': '○ 选择动画和模块实例后可记录关键帧',
  'animation.statusInherited': '○ 当前帧未保存 · 沿用前一状态 · 轨道 {count} 帧',
  'animation.statusModified': '△ 属性输入已修改，尚未应用或重新记录',
  'animation.statusSaved': '● 当前帧已保存 · 轨道 {count} 帧',
  'animation.timelineEmpty': '新建或选择动画后显示实例轨道',
  'animation.timelineNoInstances': '在场景中添加模块实例后，这里会生成实例轨道',
  'animation.timelineCorner': '实例 / 帧',
  'animation.keyframeTitle': '{name} · 第 {frame} 帧',
  'animation.keysCopied': '已复制 {count} 个关键帧。',
  'animation.keysPasted': '已粘贴 {count} 个关键帧。',
  'animation.keysDeleted': '已删除 {count} 个关键帧。',
  'animation.keysMoved': '已移动 {count} 个关键帧。',
  'animation.keysDuplicated': '已复制 {count} 个关键帧。',
  'animation.new': '新建动画',
  'animation.duplicate': '复制片段',
  'animation.remove': '删除动画',
  'animation.frameCount': '帧数',
  'animation.loop': '循环播放',
  'animation.rangeStart': '区间起点',
  'animation.rangeEnd': '区间终点',
  'animation.apply': '应用动画设置',
  'animation.playbackAria': '动画播放',
  'animation.previous': '上一帧',
  'animation.play': '播放',
  'animation.pause': '暂停',
  'animation.next': '下一帧',
  'animation.tracks': '实例轨道',
  'animation.previousOnion': '前一帧',
  'animation.nextOnion': '后一帧',
  'animation.timelineAria': '动画时间线',
  'animation.copyKeys': '复制关键帧',
  'animation.pasteKeys': '粘贴到当前帧',
  'animation.removeKeys': '删除选中',
  'animation.record': '记录选中实例',
  'animation.selectKey': '选中当前关键帧',
  'animation.unsaved': '○ 当前帧未保存',
  'glb.title': 'GLB 输出',
  'glb.structure': '场景结构',
  'glb.merged': '静态合并（当前帧）',
  'glb.instances': '保留模块实例',
  'glb.animations': '输出实例动画轨道',
  'sprite.title': 'Sprite 输出',
  'sprite.view': '视角',
  'sprite.isometric': '等距视角',
  'sprite.front': '正面',
  'sprite.side': '侧面',
  'sprite.top': '顶视',
  'sprite.direction': '方向输出',
  'sprite.resolution': '分辨率倍率',
  'sprite.resolution1x': '1× · 标准',
  'sprite.resolution2x': '2× · 高清',
  'sprite.resolution4x': '4× · 超高清',
  'sprite.resolution8x': '8× · 极清',
  'sprite.resolution16x': '16× · 最大',
  'sprite.resolutionHint': '最终单帧尺寸等于宽、高乘以分辨率倍率；边距也会同比缩放。',
  'sprite.current': '当前视角',
  'sprite.four': '角色四方向',
  'sprite.six': '六方向',
  'sprite.layout': '排列',
  'sprite.horizontal': '横向',
  'sprite.vertical': '纵向',
  'sprite.grid': '网格',
  'sprite.padding': '边距',
  'sprite.columns': '列数',
  'sprite.start': '起始帧',
  'sprite.end': '结束帧',
  'sprite.transparent': '透明背景',
  'sprite.currentPng': '当前帧 PNG',
  'sprite.sheet': '动画 Sprite Sheet',
  'stats.title': '场景统计',
  'stats.voxels': '体素数量',
  'stats.unit': '单位边长',
  'project.panel': '工程',
  'project.complete': '完整工程',
  'project.completeDescription': 'JSON / VOX 均包含场景、模块与动画',
  'project.imageDescription': '导入为可重复放置的独立模块',
  'project.importFormats': '导入 JSON / VOX',
  'project.chooseExport': '选择导出格式',
  'project.recentEmpty': '暂无最近工程',
  'project.recentClear': '清除最近记录',
  'project.recoveryMessage': '发现“{name}”在 {time} 的未保存自动快照。',
  'project.confirmReplace': '“{name}”有未保存修改，仍要打开另一个工程吗？',
  'export.jsonProject': 'JSON 完整工程',
  'export.voxProject': 'VOX 完整工程',
  'export.glbModel': 'GLB 渲染模型',
  'export.spriteSheet': 'Sprite Sheet',
  'export.progress.project': '正在准备工程数据…',
  'export.progress.json': '正在序列化 JSON 工程…',
  'export.progress.vox': '正在编码 VOX 场景…',
  'export.progress.compose': '正在组合场景体素…',
  'export.progress.glb': '正在合并网格并生成 GLB…',
  'export.progress.spriteBounds': '正在计算 Sprite 统一边界 {current}/{total}…',
  'export.progress.spriteFrame': '正在生成 Sprite 帧 {current}/{total}…',
  'export.progress.png': '正在编码 PNG…',
  'scene.clear': '清空场景',
  'status.grid': '网格 1 unit · 强调 5 / 10 units',
  'status.engine': '海月引擎',
  'project.savedToBrowser': '工程已保存到浏览器。',
  'settings.title': '编辑器设置',
  'settings.language': '界面语言',
  'settings.languageHint': '语言设置会保存在当前浏览器中。',
  'settings.done': '完成',
  'help.title': '操作帮助',
  'help.editing': '编辑',
  'help.tools': '1 / 2 / 3 / 4 或 B / E / G / N',
  'help.toolsAction': '切换添加、擦除、着色和选择工具',
  'help.primaryPointer': '左键单击或拖动',
  'help.primaryPointerAction': '使用当前工具；拖动可连续绘制或框选',
  'help.brushSize': '[ / ]',
  'help.brushSizeAction': '减小或增大笔刷尺寸',
  'help.viewport': '视图导航',
  'help.orbit': 'Space + 左键拖动',
  'help.orbitAction': '临时旋转视角',
  'help.pan': '右键拖动',
  'help.panAction': '平移视角',
  'help.zoom': '鼠标滚轮',
  'help.zoomAction': '缩放视角',
  'help.selectionHistory': '选择与历史',
  'help.extendSelection': 'Shift / Alt + 选择',
  'help.extendSelectionAction': '添加到选区 / 从选区减去',
  'help.duplicateDrag': 'Alt + 拖动 Gizmo',
  'help.duplicateDragAction': '复制并移动选中体素',
  'help.undoRedo': 'Ctrl/⌘ Z · Ctrl/⌘ Shift Z',
  'help.undoRedoAction': '撤销 / 重做',
  'help.save': 'Ctrl/⌘ S',
  'help.saveAction': '保存当前工程到浏览器',
  'help.escape': 'Esc',
  'help.escapeAction': '取消当前操作、清除选择或退出环绕',
  'help.done': '知道了',
  'hint.brushSpecial': 'Flood Fill 和 Surface Paint 只对已有体素生效，应配合着色或擦除模式使用。',
  'hint.mirror': 'X、Y、Z 镜像轴可以组合使用；一次绘制产生的所有镜像结果会合并为一条撤销记录。',
  'hint.selectionModifiers': '框选时按 Shift 可以追加选择，按 Alt/Option 可以从当前选区中减去。',
  'hint.selectionGizmo': '拖动 Gizmo 时会先显示幽灵预览；移动模式下按 Alt/Option 拖动可以复制选中体素。',
  'hint.grid': '细网格间隔为 1 单位；每 5 单位使用中等强调线，每 10 单位使用更粗、更亮的线。',
  'hint.slice': '拖动任一轴滑块会切换当前切片轴。启用工作平面后，添加笔刷会固定在对应层。',
  'hint.generator': '起点和终点都包含在生成范围内；范围内已有方块会更新为当前颜色。',
  'hint.imageImport': '图片会经过最近邻缩放和颜色量化，再生成 X–Y 平面模块。透明像素会跳过，照片和渐变也不会生成海量材质。',
  'hint.layers': '图层同时管理基础体素和模块实例。红色节点表示存在重合，可以查看冲突坐标并在视口中定位。',
  'hint.glb': '静态合并适合追求最小运行时开销；保留模块实例会共享模块网格，并输出 STEP 变换、显隐和模块切换轨道。',
  'hint.sprite': 'Sprite Sheet 会同时输出 atlas JSON，其中包含帧名、Pivot 和按不透明投影计算的碰撞框。结束帧设为 0 表示动画最后一帧。',
  'hint.export': '导出菜单支持 JSON、VOX、GLB 和 Sprite Sheet。大型导出可以查看进度并随时取消。',
  'hint.lastFrame': '0 表示动画最后一帧',
} as const;

export type TranslationKey = keyof typeof zhCN;

const enUS: Record<TranslationKey, string> = {
  'app.title': 'HaiYue Voxel Editor',
  'app.brand': 'HaiYue Voxel',
  'app.settings': 'Editor settings',
  'app.help': 'Help',
  'app.save': 'Save to browser',
  'app.saveShortcut': 'Save to browser (Ctrl/⌘ S)',
  'app.unsavedSuffix': ' · Unsaved changes',
  'app.recent': 'Recent projects',
  'app.undo': 'Undo',
  'app.redo': 'Redo',
  'history.undoLabel': 'Undo: {label} (Ctrl/⌘ Z)',
  'history.redoLabel': 'Redo: {label} (Ctrl/⌘ Shift Z)',
  'history.noUndo': 'Nothing to undo',
  'history.noRedo': 'Nothing to redo',
  'app.importProject': 'Import project',
  'app.importProjectFormats': 'Import project (JSON / VOX)',
  'app.importImage': 'Import image as module',
  'app.export': 'Export',
  'app.moreInfo': 'Show help',
  'panel.tools': 'Tools',
  'panel.editMode': 'Edit mode',
  'panel.currentColor': 'Current color',
  'panel.sceneSettings': 'Scene settings',
  'tool.add': 'Add',
  'tool.erase': 'Erase',
  'tool.paint': 'Paint',
  'tool.select': 'Select',
  'paint.replaceTitle': 'Replace Color',
  'paint.replaceSource': 'Color to replace',
  'paint.replaceWith': 'Replace with',
  'paint.replaceTarget': 'Current replacement color',
  'paint.scope': 'Scope',
  'paint.scopeGlobal': 'Current scene / module',
  'paint.scopeSelection': 'Selection only',
  'paint.replaceAction': 'Replace color',
  'paint.selectionRequired': 'Select voxels before replacing their color.',
  'paint.noMatch': 'No voxels matched the source color.',
  'paint.replaceSelectionCommand': 'Replace selection color',
  'paint.replaceGlobalCommand': 'Replace color globally',
  'paint.replaced': 'Replaced {count} voxels with {color}.',
  'project.savedToBrowser': 'Project saved to this browser.',
  'settings.title': 'Editor settings',
  'settings.language': 'Interface language',
  'settings.languageHint': 'The language setting is saved in this browser.',
  'settings.done': 'Done',
  'help.title': 'Controls',
  'help.editing': 'Editing',
  'help.tools': '1 / 2 / 3 / 4 or B / E / G / N',
  'help.toolsAction': 'Switch between add, erase, paint, and select',
  'help.primaryPointer': 'Left click or drag',
  'help.primaryPointerAction': 'Use the active tool; drag to paint continuously or box-select',
  'help.brushSize': '[ / ]',
  'help.brushSizeAction': 'Decrease or increase brush size',
  'help.viewport': 'Viewport navigation',
  'help.orbit': 'Space + left drag',
  'help.orbitAction': 'Temporarily orbit the camera',
  'help.pan': 'Right drag',
  'help.panAction': 'Pan the camera',
  'help.zoom': 'Mouse wheel',
  'help.zoomAction': 'Zoom the camera',
  'help.selectionHistory': 'Selection and history',
  'help.extendSelection': 'Shift / Alt + select',
  'help.extendSelectionAction': 'Add to / subtract from the selection',
  'help.duplicateDrag': 'Alt + drag Gizmo',
  'help.duplicateDragAction': 'Duplicate and move selected voxels',
  'help.undoRedo': 'Ctrl/⌘ Z · Ctrl/⌘ Shift Z',
  'help.undoRedoAction': 'Undo / redo',
  'help.save': 'Ctrl/⌘ S',
  'help.saveAction': 'Save the current project to this browser',
  'help.escape': 'Esc',
  'help.escapeAction': 'Cancel, clear the selection, or leave orbit mode',
  'help.done': 'Got it',
  'hint.brushSpecial': 'Flood Fill and Surface Paint only affect existing voxels and should be used in paint or erase mode.',
  'hint.mirror': 'The X, Y, and Z mirror axes can be combined. All mirrored results from one stroke are grouped into a single undo entry.',
  'hint.selectionModifiers': 'Hold Shift while box-selecting to add voxels, or Alt/Option to subtract them from the current selection.',
  'hint.selectionGizmo': 'Dragging the Gizmo shows a ghost preview first. In move mode, hold Alt/Option while dragging to duplicate selected voxels.',
  'hint.grid': 'Minor grid lines are spaced 1 unit apart. Lines at 5 units are emphasized, while 10-unit lines are thicker and brighter.',
  'hint.slice': 'Moving an axis slider makes it the active slice axis. When the work plane is enabled, the add brush is constrained to that layer.',
  'hint.generator': 'Both endpoints are included in the generated bounds. Existing voxels inside the bounds are updated to the current color.',
  'hint.imageImport': 'Images are nearest-neighbor resized and color-quantized into an X–Y plane module. Transparent pixels are skipped, and photos or gradients will not create excessive materials.',
  'hint.layers': 'Layers manage both base voxels and module instances. Red nodes indicate overlaps; inspect their coordinates or locate them in the viewport.',
  'hint.glb': 'Static merging minimizes runtime overhead. Preserved module instances share module meshes and export STEP transform, visibility, and module-switch tracks.',
  'hint.sprite': 'Sprite Sheet also exports atlas JSON with frame names, pivots, and collision boxes derived from opaque projections. An end frame of 0 means the final animation frame.',
  'hint.export': 'The export menu supports JSON, VOX, GLB, and Sprite Sheet. Large exports show progress and can be cancelled.',
  'hint.lastFrame': '0 means the final animation frame',
  'common.size': 'Size',
  'common.mode': 'Mode',
  'common.name': 'Name',
  'common.width': 'Width',
  'common.height': 'Height',
  'common.delete': 'Delete',
  'common.cancel': 'Cancel',
  'common.copy': 'Copy',
  'common.move': 'Move',
  'common.rename': 'Rename',
  'project.current': 'Current project',
  'project.untitled': 'Untitled project',
  'brush.label': 'Brush',
  'brush.voxel': 'Continuous voxels',
  'brush.line': 'Drag line',
  'brush.box': 'Drag box',
  'brush.flood': 'Flood Fill',
  'brush.surface': 'Surface Paint',
  'brush.mirror': 'Mirror drawing',
  'brush.mirrorAxes': 'Mirror drawing axes',
  'brush.sizeNotUsed': 'Connected and surface brushes do not use the size setting',
  'selection.kind': 'Selection mode',
  'selection.single': 'Single / screen box',
  'selection.connected': 'Connected same-color region',
  'selection.color': 'All voxels with same color',
  'selection.depth': 'Box selection depth',
  'selection.visible': 'Visible voxels only',
  'selection.through': 'Select through',
  'selection.all': 'Select all',
  'selection.invert': 'Invert',
  'selection.count': 'voxels selected',
  'selection.gizmo': 'Interactive Gizmo',
  'selection.moveDrag': 'Drag to move',
  'selection.duplicateDrag': 'Drag to duplicate',
  'selection.rotateRing': '90° rotation ring',
  'selection.integerScale': 'Integer bounding-box scale',
  'selection.snap': 'Snap',
  'selection.unit1': '1 unit',
  'selection.unit5': '5 units',
  'selection.unit10': '10 units',
  'selection.center': 'Selection center',
  'selection.minimum': 'Minimum corner',
  'selection.custom': 'Custom coordinates',
  'selection.offset': 'Offset transform',
  'selection.duplicateOffset': 'Duplicate with offset',
  'selection.rotate90': 'Rotate 90°',
  'selection.aroundX': 'Around X',
  'selection.aroundY': 'Around Y',
  'selection.aroundZ': 'Around Z',
  'selection.flip': 'Mirror flip',
  'selection.cut': 'Cut',
  'selection.paste': 'Paste',
  'material.name': 'Material name',
  'material.metallic': 'Metallic',
  'material.roughness': 'Roughness',
  'material.savePbr': 'Save PBR',
  'material.duplicate': 'Duplicate material',
  'material.unused': 'Current material is unused',
  'material.colorAria': 'Choose color',
  'material.hexAria': 'Hex color',
  'material.paletteAria': 'Preset palette',
  'material.select': 'Select material {name}',
  'material.usage': '{count} definition voxels use this material',
  'material.voxPartial': 'VOX {type} (partially supported; approximate PBR preview)',
  'material.voxPartialDetail': 'VOX {type}: original MATL data is preserved; the PBR viewport is an approximation.',
  'viewport.perspectiveView': 'Perspective view',
  'viewport.orthographicView': 'Orthographic view',
  'viewport.addVoxel': 'Add voxel',
  'viewport.eraseVoxel': 'Erase voxel',
  'viewport.paintVoxel': 'Paint voxel',
  'viewport.selectCount': 'Select · {count}',
  'viewport.orthographicPreset': 'Orthographic · {view}',
  'viewport.focusRequired': 'Select voxels to frame first.',
  'viewport.coordinate': 'Cell X {x} · Y {y} · Z {z}',
  'viewport.perspective': 'Perspective',
  'viewport.orthographic': 'Orthographic',
  'viewport.projectionAria': 'Projection mode',
  'viewport.orbit': 'Orbit view',
  'viewport.exitOrbit': 'Exit orbit',
  'viewport.orbitTitle': 'Toggle orbit view; hold Space for temporary orbit',
  'viewport.reset': 'Reset view',
  'viewport.drop': 'Drop files to import',
  'viewport.dropFormats': 'JSON / VOX projects · PNG / JPG / WebP / GIF image modules',
  'viewport.standardViews': 'Standard views and framing',
  'viewport.orthographicViews': 'Standard orthographic views',
  'viewport.front': 'Front',
  'viewport.back': 'Back',
  'viewport.left': 'Left',
  'viewport.right': 'Right',
  'viewport.top': 'Top',
  'viewport.bottom': 'Bottom',
  'viewport.frontView': 'Front view',
  'viewport.backView': 'Back view',
  'viewport.leftView': 'Left view',
  'viewport.rightView': 'Right view',
  'viewport.topView': 'Top view',
  'viewport.bottomView': 'Bottom view',
  'viewport.frameSelected': 'Frame selection',
  'viewport.frameSelectedTitle': 'Frame selected voxels',
  'viewport.frameAll': 'Frame all',
  'viewport.frameAllTitle': 'Frame all models',
  'viewport.initializing': 'Initializing WebGPU',
  'viewport.preparing': 'Preparing voxel workspace…',
  'viewport.coordinateEmpty': 'Cell —',
  'viewport.axisAria': 'Camera orientation axes',
  'recovery.found': 'Recovery snapshot found',
  'recovery.restore': 'Restore',
  'recovery.ignore': 'Ignore',
  'export.preparing': 'Preparing export…',
  'export.cancel': 'Cancel export',
  'scene.size': 'Scene size',
  'scene.applySize': 'Apply size',
  'scene.background': 'Scene background',
  'scene.backgroundColorAria': 'Choose scene background color',
  'scene.backgroundHexAria': 'Scene background hex color',
  'scene.backgroundReset': 'Default',
  'scene.backgroundResetTitle': 'Restore the default background color',
  'scene.backgroundCommand': 'Change scene background color',
  'scene.backgroundUpdated': 'Scene background color updated.',
  'slice.title': 'Slices and work plane',
  'slice.axisAria': 'Active slice axis',
  'slice.display': 'Display',
  'slice.all': 'All voxels',
  'slice.single': 'Current layer only',
  'slice.context': 'Current layer + transparent context',
  'slice.workPlane': 'Enable movable work plane',
  'shape.title': 'Batch generation',
  'shape.kind': 'Shape',
  'shape.box': 'Filled box',
  'shape.boxShell': 'Hollow box',
  'shape.disk': 'Disk (XZ)',
  'shape.ring': 'Ring (XZ)',
  'shape.sphere': 'Filled sphere',
  'shape.sphereShell': 'Hollow sphere',
  'shape.cylinder': 'Cylinder (Y axis)',
  'shape.start': 'Start',
  'shape.end': 'End',
  'shape.generate': 'Generate with current color',
  'image.title': 'Image module',
  'image.colorLimit': 'Color limit',
  'image.colors': '{count} colors',
  'image.dither': 'Dither',
  'image.merge': 'Merge similar colors',
  'image.create': 'Choose image and create module',
  'module.title': 'Modules',
  'module.scene': 'Main scene',
  'module.search': 'Search modules…',
  'module.searchAria': 'Search modules',
  'module.sortAria': 'Module sorting',
  'module.assetsAria': 'Module assets',
  'module.libraryAria': 'Module library',
  'module.nameAsc': 'Name A–Z',
  'module.nameDesc': 'Name Z–A',
  'module.empty': 'No modules created',
  'module.noMatch': 'No matching modules',
  'module.summary': '{name} · {count} voxels',
  'module.assetMeta': '{count} voxels · {size}',
  'module.editing': 'Editing: {name}',
  'module.sceneLayers': 'Scene layers ({count})',
  'module.baseVoxels': 'Base voxels ({count})',
  'module.layerSummary': '{name} ({voxels} voxels · {instances} instances)',
  'module.showSelected': 'Show selected instance',
  'module.showLayer': 'Show layer',
  'module.unlockLayer': 'Unlock layer',
  'module.collisionSummary': '{count} overlapping cells',
  'module.new': 'New',
  'module.edit': 'Edit module',
  'module.return': 'Return to scene',
  'module.duplicateDefinition': 'Duplicate definition',
  'module.removeUnused': 'Remove unused',
  'module.locate': 'Locate all instances of this module',
  'module.position': 'Position / paste coordinates',
  'module.rotation': 'Rotation',
  'module.integerScale': 'Integer scale',
  'module.applyTransform': 'Apply selected instance transform',
  'module.hideSelected': 'Hide selected instance',
  'module.copy': 'Copy module',
  'module.paste': 'Paste into scene',
  'module.tree': 'Scene module tree',
  'module.noConflict': 'The current instance has no overlap conflicts.',
  'module.highlightConflict': 'Locate and highlight conflicting voxels',
  'module.removeInstance': 'Remove selected module instance',
  'layer.title': 'Layers',
  'layer.sceneAria': 'Scene layers',
  'layer.default': 'Default layer',
  'layer.new': 'New layer',
  'layer.remove': 'Delete layer',
  'layer.hide': 'Hide layer',
  'layer.lock': 'Lock layer',
  'layer.assign': 'Move selected base voxels to current layer',
  'gizmo.instance': 'Instance Gizmo',
  'gizmo.modeAria': 'Gizmo mode',
  'gizmo.move': 'Move · drag axis',
  'gizmo.rotate': 'Rotate · click axis for 90°',
  'gizmo.scale': 'Scale · drag axis',
  'animation.title': 'Animation',
  'animation.frame': 'Frame {current} / {total}',
  'animation.libraryAria': 'Animation clips',
  'animation.empty': 'No animation created',
  'animation.clipSummary': '{name} · {count} frames',
  'animation.statusSelect': '○ Select an animation and module instance to record a keyframe',
  'animation.statusInherited': '○ Current frame is not saved · Inheriting previous state · {count} track frames',
  'animation.statusModified': '△ Property inputs changed and have not been applied or recorded',
  'animation.statusSaved': '● Current frame saved · {count} track frames',
  'animation.timelineEmpty': 'Create or select an animation to show instance tracks',
  'animation.timelineNoInstances': 'Add module instances to the scene to create instance tracks',
  'animation.timelineCorner': 'Instance / frame',
  'animation.keyframeTitle': '{name} · Frame {frame}',
  'animation.keysCopied': 'Copied {count} keyframes.',
  'animation.keysPasted': 'Pasted {count} keyframes.',
  'animation.keysDeleted': 'Deleted {count} keyframes.',
  'animation.keysMoved': 'Moved {count} keyframes.',
  'animation.keysDuplicated': 'Duplicated {count} keyframes.',
  'animation.new': 'New animation',
  'animation.duplicate': 'Duplicate clip',
  'animation.remove': 'Delete animation',
  'animation.frameCount': 'Frames',
  'animation.loop': 'Loop playback',
  'animation.rangeStart': 'Range start',
  'animation.rangeEnd': 'Range end',
  'animation.apply': 'Apply animation settings',
  'animation.playbackAria': 'Animation playback',
  'animation.previous': 'Previous frame',
  'animation.play': 'Play',
  'animation.pause': 'Pause',
  'animation.next': 'Next frame',
  'animation.tracks': 'Instance tracks',
  'animation.previousOnion': 'Previous frame',
  'animation.nextOnion': 'Next frame',
  'animation.timelineAria': 'Animation timeline',
  'animation.copyKeys': 'Copy keyframes',
  'animation.pasteKeys': 'Paste at current frame',
  'animation.removeKeys': 'Delete selected',
  'animation.record': 'Record selected instance',
  'animation.selectKey': 'Select current keyframe',
  'animation.unsaved': '○ Current frame not saved',
  'glb.title': 'GLB output',
  'glb.structure': 'Scene structure',
  'glb.merged': 'Static merge (current frame)',
  'glb.instances': 'Preserve module instances',
  'glb.animations': 'Export instance animation tracks',
  'sprite.title': 'Sprite output',
  'sprite.view': 'View',
  'sprite.isometric': 'Isometric',
  'sprite.front': 'Front',
  'sprite.side': 'Side',
  'sprite.top': 'Top',
  'sprite.direction': 'Directions',
  'sprite.resolution': 'Resolution scale',
  'sprite.resolution1x': '1× · Standard',
  'sprite.resolution2x': '2× · High resolution',
  'sprite.resolution4x': '4× · Ultra high resolution',
  'sprite.resolution8x': '8× · Very high resolution',
  'sprite.resolution16x': '16× · Maximum',
  'sprite.resolutionHint': 'Final frame dimensions equal width and height multiplied by this scale; padding scales proportionally.',
  'sprite.current': 'Current view',
  'sprite.four': 'Four character directions',
  'sprite.six': 'Six directions',
  'sprite.layout': 'Layout',
  'sprite.horizontal': 'Horizontal',
  'sprite.vertical': 'Vertical',
  'sprite.grid': 'Grid',
  'sprite.padding': 'Padding',
  'sprite.columns': 'Columns',
  'sprite.start': 'Start frame',
  'sprite.end': 'End frame',
  'sprite.transparent': 'Transparent background',
  'sprite.currentPng': 'Current frame PNG',
  'sprite.sheet': 'Animation Sprite Sheet',
  'stats.title': 'Scene statistics',
  'stats.voxels': 'Voxel count',
  'stats.unit': 'Unit edge length',
  'project.panel': 'Project',
  'project.complete': 'Complete project',
  'project.completeDescription': 'JSON / VOX include scene, modules, and animations',
  'project.imageDescription': 'Import as an independently reusable module',
  'project.importFormats': 'Import JSON / VOX',
  'project.chooseExport': 'Choose export format',
  'project.recentEmpty': 'No recent projects',
  'project.recentClear': 'Clear recent projects',
  'project.recoveryMessage': 'Found an unsaved autosave for “{name}” from {time}.',
  'project.confirmReplace': '“{name}” has unsaved changes. Open another project anyway?',
  'export.jsonProject': 'JSON project',
  'export.voxProject': 'VOX project',
  'export.glbModel': 'GLB render model',
  'export.spriteSheet': 'Sprite Sheet',
  'export.progress.project': 'Preparing project data…',
  'export.progress.json': 'Serializing JSON project…',
  'export.progress.vox': 'Encoding VOX scene…',
  'export.progress.compose': 'Composing scene voxels…',
  'export.progress.glb': 'Merging geometry and generating GLB…',
  'export.progress.spriteBounds': 'Calculating shared Sprite bounds {current}/{total}…',
  'export.progress.spriteFrame': 'Generating Sprite frame {current}/{total}…',
  'export.progress.png': 'Encoding PNG…',
  'scene.clear': 'Clear scene',
  'status.grid': 'Grid 1 unit · emphasized at 5 / 10 units',
  'status.engine': 'HaiYue Engine',
};

const catalogs: Record<EditorLocale, Record<TranslationKey, string>> = {
  'zh-CN': zhCN,
  'en-US': enUS,
};

let activeLocale: EditorLocale = 'zh-CN';

export function normalizeEditorLocale(value: string | null | undefined): EditorLocale | null {
  if (!value) return null;
  const normalized = value.toLowerCase();
  if (normalized === 'zh' || normalized.startsWith('zh-')) return 'zh-CN';
  if (normalized === 'en' || normalized.startsWith('en-')) return 'en-US';
  return null;
}

export function getEditorLocale(): EditorLocale {
  return activeLocale;
}

export function translate(
  key: TranslationKey,
  values: Readonly<Record<string, string | number>> = {},
  locale: EditorLocale = activeLocale,
): string {
  return catalogs[locale][key].replace(/\{([^}]+)\}/g, (match, name: string) => {
    const value = values[name];
    return value === undefined ? match : String(value);
  });
}

export interface EditorLocalizationController {
  readonly locale: EditorLocale;
  setLocale(locale: EditorLocale): void;
  apply(): void;
}

class DomEditorLocalizationController implements EditorLocalizationController {
  private readonly _root: Document;
  private readonly _storage: Storage | null;
  private readonly _dialog: HTMLDialogElement;
  private readonly _language: HTMLSelectElement;

  constructor(root: Document, storage: Storage | null) {
    this._root = root;
    this._storage = storage;
    this._dialog = requiredElement<HTMLDialogElement>(root, 'editor-settings-dialog');
    this._language = requiredElement<HTMLSelectElement>(root, 'editor-language');

    const stored = this._readStoredLocale();
    activeLocale = stored ?? 'zh-CN';
    this._language.value = activeLocale;
    requiredElement(root, 'editor-settings').addEventListener('click', () => this._openSettings());
    this._language.addEventListener('change', () => {
      this.setLocale(normalizeEditorLocale(this._language.value) ?? 'zh-CN');
    });
    requiredElement(root, 'close-editor-settings').addEventListener('click', () => this._closeSettings());
    this.apply();
  }

  get locale(): EditorLocale {
    return activeLocale;
  }

  setLocale(locale: EditorLocale): void {
    if (!EDITOR_LOCALES.includes(locale)) return;
    activeLocale = locale;
    this._language.value = locale;
    try { this._storage?.setItem(EDITOR_LOCALE_STORAGE_KEY, locale); }
    catch { /* Private browsing or a storage policy must not break the editor. */ }
    this.apply();
    this._root.dispatchEvent(new CustomEvent('voxel-editor-locale-change', { detail: { locale } }));
  }

  apply(): void {
    this._root.documentElement.lang = activeLocale;
    for (const node of this._root.querySelectorAll<HTMLElement>('[data-i18n]')) {
      const key = translationKey(node.dataset.i18n);
      if (key) node.textContent = translate(key, translationValues(node));
    }
    this._applyAttribute('data-i18n-title', 'title');
    this._applyAttribute('data-i18n-aria-label', 'aria-label');
    this._applyAttribute('data-i18n-placeholder', 'placeholder');
    this._applyAttribute('data-i18n-label', 'label');
  }

  private _applyAttribute(dataAttribute: string, attribute: string): void {
    for (const node of this._root.querySelectorAll<HTMLElement>(`[${dataAttribute}]`)) {
      const key = translationKey(node.getAttribute(dataAttribute));
      if (key) node.setAttribute(attribute, translate(key));
    }
  }

  private _readStoredLocale(): EditorLocale | null {
    try { return normalizeEditorLocale(this._storage?.getItem(EDITOR_LOCALE_STORAGE_KEY)); }
    catch { return null; }
  }

  private _openSettings(): void {
    if (this._dialog.open) return;
    if (typeof this._dialog.showModal === 'function') this._dialog.showModal();
    else this._dialog.setAttribute('open', '');
    this._language.focus();
  }

  private _closeSettings(): void {
    if (typeof this._dialog.close === 'function') this._dialog.close();
    else this._dialog.removeAttribute('open');
  }
}

let controller: EditorLocalizationController | null = null;

export function initializeEditorLocalization(
  root: Document = document,
  storage: Storage | null = safeLocalStorage(),
): EditorLocalizationController {
  controller ??= new DomEditorLocalizationController(root, storage);
  return controller;
}

function safeLocalStorage(): Storage | null {
  try { return window.localStorage; }
  catch { return null; }
}

function translationKey(value: string | null | undefined): TranslationKey | null {
  return value && value in zhCN ? value as TranslationKey : null;
}

function translationValues(node: HTMLElement): Record<string, string> | undefined {
  let values: Record<string, string> | undefined;
  for (const [name, value] of Object.entries(node.dataset)) {
    if (!name.startsWith('i18n') || name.length === 4 || value === undefined) continue;
    const parameterName = `${name.charAt(4).toLowerCase()}${name.slice(5)}`;
    (values ??= {})[parameterName] = value;
  }
  return values;
}

function requiredElement<T extends Element = HTMLElement>(root: Document, id: string): T {
  const value = root.getElementById(id);
  if (!value) throw new Error(`Missing #${id}`);
  return value as unknown as T;
}
